Header header



float64 fb_a_x
float64 fb_a_y
float64 fb_a_z

float64 des_p_x
float64 des_p_y
float64 des_p_z

float64 des_v_x
float64 des_v_y
float64 des_v_z

float64 des_a_x
float64 des_a_y
float64 des_a_z


float64 des_q_x
float64 des_q_y
float64 des_q_z
float64 des_q_w

float64 est_r
float64 est_p
float64 est_y

float64 ref_r
float64 ref_p
float64 ref_y

float64 des_r
float64 des_p
float64 des_y

float64 exec_err_axisang_x
float64 exec_err_axisang_y
float64 exec_err_axisang_z
float64 exec_err_axisang_ang

float64 fb_axisang_x
float64 fb_axisang_y
float64 fb_axisang_z
float64 fb_axisang_ang

float64 fb_rate_x
float64 fb_rate_y
float64 fb_rate_z

float64 des_bodyrates_x
float64 des_bodyrates_y
float64 des_bodyrates_z

float64 des_bodyaccs_x
float64 des_bodyaccs_y
float64 des_bodyaccs_z

float64 imu_af_x
float64 imu_af_y
float64 imu_af_z

float64 imu_wf_x
float64 imu_wf_y
float64 imu_wf_z

float64 imu_dw_x
float64 imu_dw_y
float64 imu_dw_z

float64 rpm_f1
float64 rpm_f2
float64 rpm_f3
float64 rpm_f4

float64 cmd_rpm1
float64 cmd_rpm2
float64 cmd_rpm3
float64 cmd_rpm4

float64 ref_thrust1
float64 ref_thrust2
float64 ref_thrust3
float64 ref_thrust4

float64 des_rpm_ave
float64 rpm_ave

float64 des_yaw
float64 des_yaw_rate
float64 des_yaw_acc

float64 thro1
float64 thro2
float64 thro3
float64 thro4

float64 delta_q_ang
float64 des_q_ang
float64 des_F
float64 indi_F
float64 hover_percentage
float64 thr_scale_compensate
float64 voltage

float64 ref_v_x
float64 ref_v_y
float64 ref_v_z

float64 ref_a_x
float64 ref_a_y
float64 ref_a_z

float64 ref_j_x
float64 ref_j_y
float64 ref_j_z

float64 ref_s_x
float64 ref_s_y
float64 ref_s_z

float64 x_pos_error
float64 y_pos_error 
float64 z_pos_error 
float64 x_vel_error 
float64 y_vel_error 
float64 z_vel_error 
float64 ref_thr
float64 des_thr
float64 est_thr
float64 des_torque_x
float64 des_torque_y
float64 des_torque_z
float64 cont_torque_x
float64 cont_torque_y
float64 cont_torque_z
float64 z_jwj

float64 fbp_thrust1
float64 fbi_thrust1
float64 fbp_thrust2
float64 fbi_thrust2
float64 fbp_thrust3
float64 fbi_thrust3
float64 fbp_thrust4
float64 fbi_thrust4

float64 fbp_thrust
float64 fbi_thrust
float64 fb_thrust

float64 rpm_error1
float64 rpm_error_sum1
float64 rpm_error2
float64 rpm_error_sum2
float64 rpm_error3
float64 rpm_error_sum3
float64 rpm_error4
float64 rpm_error_sum4

float64 rate_error_z
float64 rate_error_sum_z

float64 fbp_bodyacc_z
float64 fbi_bodyacc_z

float64 des_est_bodyrates_x
float64 des_est_bodyrates_y
float64 des_est_bodyrates_z


float64 acc_error1
float64 acc_error2
float64 acc_error3
float64 acc_error4

float64 acc_errorsum1
float64 acc_errorsum2
float64 acc_errorsum3
float64 acc_errorsum4

float64 window_ave1
float64 window_ave2
float64 window_ave3
float64 window_ave4

float64 pos_error_all
float64 pos_error_xy
float64 pos_error_rmse
float64 vel_error_all
float64 des_v_all

float64 ref_bodyrates_x
float64 ref_bodyrates_y
float64 ref_bodyrates_z

float64 extTotalAccIndi_x
float64 extTotalAccIndi_y
float64 extTotalAccIndi_z

float64 aw_x
float64 aw_y
float64 aw_z

float64 fb_a_x_fil
float64 fb_a_y_fil
float64 fb_a_z_fil

float64 extF_psi
float64 extF_theta

float64 des_Fq_psi
float64 des_Fq_theta

float64 indi_q_err_ang

float64 fb_F_x
float64 fb_F_y
float64 fb_F_z

uint8 flag

float64 indi_acc_q_error_x
float64 indi_acc_q_error_y
float64 indi_acc_q_error_z
float64 F_error

float64 indi_acc_F_error_x
float64 indi_acc_F_error_y
float64 indi_acc_F_error_z

float64 indiF_x
float64 indiF_y
float64 indiF_z

float64 desFq_x
float64 desFq_y
float64 desFq_z

float64 fb_pv_x
float64 fb_pv_y
float64 fb_pv_z

float64 fb_q_x
float64 fb_q_y
float64 fb_q_z

float64 fb_Fq_x
float64 fb_Fq_y
float64 fb_Fq_z

float64 v_modi_x
float64 v_modi_y
float64 v_modi_z

float64 fb_Fq_error_fil_x
float64 fb_Fq_error_fil_y
float64 fb_Fq_error_fil_z

float64 FUpper
float64 FLower
float64 ref_rpm1
float64 ref_rpm2
float64 ref_rpm3
float64 ref_rpm4
float64 ref_torque_x
float64 ref_torque_y
float64 ref_torque_z
float64 indi_F_Limit
