(cl:in-package quadrotor_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          POLYTOPES-VAL
          POLYTOPES
          TRANSITION_CENTERS-VAL
          TRANSITION_CENTERS
          TRANSITION_RADII-VAL
          TRANSITION_RADII
          TRANSITION_TANGENTS-VAL
          TRANSITION_TANGENTS
          TRANSITION_LONGITUDINAL_RADII-VAL
          TRANSITION_LONGITUDINAL_RADII
          TRANSITION_TRANSVERSE_RADII-VAL
          TRANSITION_TRANSVERSE_RADII
))