(cl:in-package quadrotor_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          POSITION-VAL
          POSITION
          VELOCITY-VAL
          VELOCITY
          ACCELERATION-VAL
          ACCELERATION
          JERK-VAL
          JERK
          SNAP-VAL
          SNAP
          ANGT-VAL
          ANGT
          DANGT-VAL
          DANGT
          D2ANGT-VAL
          D2ANGT
          D3ANGT-VAL
          D3ANGT
          D4ANGT-VAL
          D4ANGT
          YAW-VAL
          YAW
          YAW_DOT-VAL
          YAW_DOT
          YAW_ACC-VAL
          YAW_ACC
          TRAJECTORY_ID-VAL
          TRAJECTORY_ID
          TRAJECTORY_FLAG-VAL
          TRAJECTORY_FLAG
          FLAG-VAL
          FLAG
))