(cl:in-package quadrotor_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          ODOM_ROLL-VAL
          ODOM_ROLL
          ODOM_PITCH-VAL
          ODOM_PITCH
          ODOM_YAW-VAL
          ODOM_YAW
          ODOMC_ROLL-VAL
          ODOMC_ROLL
          ODOMC_PITCH-VAL
          ODOMC_PITCH
          ODOMC_YAW-VAL
          ODOMC_YAW
          GE_ANGLE_ROLL-VAL
          GE_ANGLE_ROLL
          GE_ANGLE_PITCH-VAL
          GE_ANGLE_PITCH
          GE_ANGLE_YAW-VAL
          GE_ANGLE_YAW
          IMU_A_X-VAL
          IMU_A_X
          IMU_A_Y-VAL
          IMU_A_Y
          IMU_A_Z-VAL
          IMU_A_Z
          IMU_A_FIL_X-VAL
          IMU_A_FIL_X
          IMU_A_FIL_Y-VAL
          IMU_A_FIL_Y
          IMU_A_FIL_Z-VAL
          IMU_A_FIL_Z
          IMU_W_X-VAL
          IMU_W_X
          IMU_W_Y-VAL
          IMU_W_Y
          IMU_W_Z-VAL
          IMU_W_Z
          IMU_W_FIL_X-VAL
          IMU_W_FIL_X
          IMU_W_FIL_Y-VAL
          IMU_W_FIL_Y
          IMU_W_FIL_Z-VAL
          IMU_W_FIL_Z
          IMU_W_C_X-VAL
          IMU_W_C_X
          IMU_W_C_Y-VAL
          IMU_W_C_Y
          IMU_W_C_Z-VAL
          IMU_W_C_Z
          IMU_BETA_FIL_X-VAL
          IMU_BETA_FIL_X
          IMU_BETA_FIL_Y-VAL
          IMU_BETA_FIL_Y
          IMU_BETA_FIL_Z-VAL
          IMU_BETA_FIL_Z
          RPM1-VAL
          RPM1
          RPM2-VAL
          RPM2
          RPM3-VAL
          RPM3
          RPM4-VAL
          RPM4
          RPM1_FIL-VAL
          RPM1_FIL
          RPM2_FIL-VAL
          RPM2_FIL
          RPM3_FIL-VAL
          RPM3_FIL
          RPM4_FIL-VAL
          RPM4_FIL
          SUMRPM2-VAL
          SUMRPM2
          THRUST_FORCE-VAL
          THRUST_FORCE
          THRUST_ACC-VAL
          THRUST_ACC
          SUMRPM2_FIL-VAL
          SUMRPM2_FIL
          THRUST_FORCE_FIL-VAL
          THRUST_FORCE_FIL
          THRUST_ACC_FIL-VAL
          THRUST_ACC_FIL
          ACC_WORLD_X-VAL
          ACC_WORLD_X
          ACC_WORLD_Y-VAL
          ACC_WORLD_Y
          ACC_WORLD_Z-VAL
          ACC_WORLD_Z
          GE_ACC_X-VAL
          GE_ACC_X
          GE_ACC_Y-VAL
          GE_ACC_Y
          GE_ACC_Z-VAL
          GE_ACC_Z
          GE_BODYTORQUE_X-VAL
          GE_BODYTORQUE_X
          GE_BODYTORQUE_Y-VAL
          GE_BODYTORQUE_Y
          GE_BODYTORQUE_Z-VAL
          GE_BODYTORQUE_Z
          DES_GE_BODYTORQUE_X-VAL
          DES_GE_BODYTORQUE_X
          DES_GE_BODYTORQUE_Y-VAL
          DES_GE_BODYTORQUE_Y
          DES_GE_BODYTORQUE_Z-VAL
          DES_GE_BODYTORQUE_Z
          D_GE_TORQUE_X-VAL
          D_GE_TORQUE_X
          D_GE_TORQUE_Y-VAL
          D_GE_TORQUE_Y
          D_GE_TORQUE_Z-VAL
          D_GE_TORQUE_Z
          DIFF_GE_TORQUE_X-VAL
          DIFF_GE_TORQUE_X
          DIFF_GE_TORQUE_Y-VAL
          DIFF_GE_TORQUE_Y
          DIFF_GE_TORQUE_Z-VAL
          DIFF_GE_TORQUE_Z
          EXT_TORQUE_X-VAL
          EXT_TORQUE_X
          EXT_TORQUE_Y-VAL
          EXT_TORQUE_Y
          EXT_TORQUE_Z-VAL
          EXT_TORQUE_Z
          PREDICT_EXT_TORQUE_X-VAL
          PREDICT_EXT_TORQUE_X
          PREDICT_EXT_TORQUE_Y-VAL
          PREDICT_EXT_TORQUE_Y
          PREDICT_EXT_TORQUE_Z-VAL
          PREDICT_EXT_TORQUE_Z
          DES_P_X-VAL
          DES_P_X
          DES_P_Y-VAL
          DES_P_Y
          DES_P_Z-VAL
          DES_P_Z
          DES_V_X-VAL
          DES_V_X
          DES_V_Y-VAL
          DES_V_Y
          DES_V_Z-VAL
          DES_V_Z
          DES_A_X-VAL
          DES_A_X
          DES_A_Y-VAL
          DES_A_Y
          DES_A_Z-VAL
          DES_A_Z
          DES_J_X-VAL
          DES_J_X
          DES_J_Y-VAL
          DES_J_Y
          DES_J_Z-VAL
          DES_J_Z
          DES_S_X-VAL
          DES_S_X
          DES_S_Y-VAL
          DES_S_Y
          DES_S_Z-VAL
          DES_S_Z
          DES_YAW-VAL
          DES_YAW
          DES_YAW_RATE-VAL
          DES_YAW_RATE
          DES_YAW_ACC-VAL
          DES_YAW_ACC
          FLATCTRL_Q_W-VAL
          FLATCTRL_Q_W
          FLATCTRL_Q_X-VAL
          FLATCTRL_Q_X
          FLATCTRL_Q_Y-VAL
          FLATCTRL_Q_Y
          FLATCTRL_Q_Z-VAL
          FLATCTRL_Q_Z
          FLATCTRL_ROLL-VAL
          FLATCTRL_ROLL
          FLATCTRL_PITCH-VAL
          FLATCTRL_PITCH
          FLATCTRL_YAW-VAL
          FLATCTRL_YAW
          FLATCTRL_BODYRATE_X-VAL
          FLATCTRL_BODYRATE_X
          FLATCTRL_BODYRATE_Y-VAL
          FLATCTRL_BODYRATE_Y
          FLATCTRL_BODYRATE_Z-VAL
          FLATCTRL_BODYRATE_Z
          FLATCTRL_BETA_X-VAL
          FLATCTRL_BETA_X
          FLATCTRL_BETA_Y-VAL
          FLATCTRL_BETA_Y
          FLATCTRL_BETA_Z-VAL
          FLATCTRL_BETA_Z
          FLATCTRL_THRUST-VAL
          FLATCTRL_THRUST
          FLATCTRL_TORQUE_X-VAL
          FLATCTRL_TORQUE_X
          FLATCTRL_TORQUE_Y-VAL
          FLATCTRL_TORQUE_Y
          FLATCTRL_TORQUE_Z-VAL
          FLATCTRL_TORQUE_Z
          FLATCTRL_GE_ACC_X-VAL
          FLATCTRL_GE_ACC_X
          FLATCTRL_GE_ACC_Y-VAL
          FLATCTRL_GE_ACC_Y
          FLATCTRL_GE_ACC_Z-VAL
          FLATCTRL_GE_ACC_Z
          FLATCTRL_DRAG_ACC_X-VAL
          FLATCTRL_DRAG_ACC_X
          FLATCTRL_DRAG_ACC_Y-VAL
          FLATCTRL_DRAG_ACC_Y
          FLATCTRL_DRAG_ACC_Z-VAL
          FLATCTRL_DRAG_ACC_Z
          FLATCTRL_EXT_ACC_X-VAL
          FLATCTRL_EXT_ACC_X
          FLATCTRL_EXT_ACC_Y-VAL
          FLATCTRL_EXT_ACC_Y
          FLATCTRL_EXT_ACC_Z-VAL
          FLATCTRL_EXT_ACC_Z
          GE_LIMIT_K-VAL
          GE_LIMIT_K
          FB_VEL_X-VAL
          FB_VEL_X
          FB_VEL_Y-VAL
          FB_VEL_Y
          FB_VEL_Z-VAL
          FB_VEL_Z
          CMD_VEL_X-VAL
          CMD_VEL_X
          CMD_VEL_Y-VAL
          CMD_VEL_Y
          CMD_VEL_Z-VAL
          CMD_VEL_Z
          COMPENSATE_ACC_X-VAL
          COMPENSATE_ACC_X
          COMPENSATE_ACC_Y-VAL
          COMPENSATE_ACC_Y
          COMPENSATE_ACC_Z-VAL
          COMPENSATE_ACC_Z
          FB_ACC_X-VAL
          FB_ACC_X
          FB_ACC_Y-VAL
          FB_ACC_Y
          FB_ACC_Z-VAL
          FB_ACC_Z
          CMD_ACC_X-VAL
          CMD_ACC_X
          CMD_ACC_Y-VAL
          CMD_ACC_Y
          CMD_ACC_Z-VAL
          CMD_ACC_Z
          CMD_ACC_NORM-VAL
          CMD_ACC_NORM
          CMD_ACC_NORM_BY_BODY-VAL
          CMD_ACC_NORM_BY_BODY
          CMD_Q_W-VAL
          CMD_Q_W
          CMD_Q_X-VAL
          CMD_Q_X
          CMD_Q_Y-VAL
          CMD_Q_Y
          CMD_Q_Z-VAL
          CMD_Q_Z
          CMD_ROLL-VAL
          CMD_ROLL
          CMD_PITCH-VAL
          CMD_PITCH
          CMD_YAW-VAL
          CMD_YAW
          FB_BODYRATE_X-VAL
          FB_BODYRATE_X
          FB_BODYRATE_Y-VAL
          FB_BODYRATE_Y
          FB_BODYRATE_Z-VAL
          FB_BODYRATE_Z
          CMD_BODYRATE_X-VAL
          CMD_BODYRATE_X
          CMD_BODYRATE_Y-VAL
          CMD_BODYRATE_Y
          CMD_BODYRATE_Z-VAL
          CMD_BODYRATE_Z
          FB_BETA_X-VAL
          FB_BETA_X
          FB_BETA_Y-VAL
          FB_BETA_Y
          FB_BETA_Z-VAL
          FB_BETA_Z
          CMD_BETA_X-VAL
          CMD_BETA_X
          CMD_BETA_Y-VAL
          CMD_BETA_Y
          CMD_BETA_Z-VAL
          CMD_BETA_Z
          COMPENSATE_TORQUE_X-VAL
          COMPENSATE_TORQUE_X
          COMPENSATE_TORQUE_Y-VAL
          COMPENSATE_TORQUE_Y
          COMPENSATE_TORQUE_Z-VAL
          COMPENSATE_TORQUE_Z
          BODYTORQUE_X-VAL
          BODYTORQUE_X
          BODYTORQUE_Y-VAL
          BODYTORQUE_Y
          BODYTORQUE_Z-VAL
          BODYTORQUE_Z
          CMD_TORQUE_BODY_X-VAL
          CMD_TORQUE_BODY_X
          CMD_TORQUE_BODY_Y-VAL
          CMD_TORQUE_BODY_Y
          CMD_TORQUE_BODY_Z-VAL
          CMD_TORQUE_BODY_Z
          DIFF_INDI_TORQUE_X-VAL
          DIFF_INDI_TORQUE_X
          DIFF_INDI_TORQUE_Y-VAL
          DIFF_INDI_TORQUE_Y
          DIFF_INDI_TORQUE_Z-VAL
          DIFF_INDI_TORQUE_Z
          DIFF_TORQUE_X-VAL
          DIFF_TORQUE_X
          DIFF_TORQUE_Y-VAL
          DIFF_TORQUE_Y
          DIFF_TORQUE_Z-VAL
          DIFF_TORQUE_Z
          CMD_RPM1-VAL
          CMD_RPM1
          CMD_RPM2-VAL
          CMD_RPM2
          CMD_RPM3-VAL
          CMD_RPM3
          CMD_RPM4-VAL
          CMD_RPM4
          CMD_SUMRPM2-VAL
          CMD_SUMRPM2
          CMD_SUMRPM2_TO_ACC-VAL
          CMD_SUMRPM2_TO_ACC
          FB_THRUST1-VAL
          FB_THRUST1
          FB_THRUST2-VAL
          FB_THRUST2
          FB_THRUST3-VAL
          FB_THRUST3
          FB_THRUST4-VAL
          FB_THRUST4
          REF_THRUST1-VAL
          REF_THRUST1
          REF_THRUST2-VAL
          REF_THRUST2
          REF_THRUST3-VAL
          REF_THRUST3
          REF_THRUST4-VAL
          REF_THRUST4
          CMD_THRUST1-VAL
          CMD_THRUST1
          CMD_THRUST2-VAL
          CMD_THRUST2
          CMD_THRUST3-VAL
          CMD_THRUST3
          CMD_THRUST4-VAL
          CMD_THRUST4
          FGH-VAL
          FGH
          REF_THRUST_ACC-VAL
          REF_THRUST_ACC
          THRUST_ACC_FIL_X-VAL
          THRUST_ACC_FIL_X
          THRUST_ACC_FIL_Y-VAL
          THRUST_ACC_FIL_Y
          THRUST_ACC_FIL_Z-VAL
          THRUST_ACC_FIL_Z
          IMU_ACC_FIL_X-VAL
          IMU_ACC_FIL_X
          IMU_ACC_FIL_Y-VAL
          IMU_ACC_FIL_Y
          IMU_ACC_FIL_Z-VAL
          IMU_ACC_FIL_Z
          EXTFORCE_ACC_X-VAL
          EXTFORCE_ACC_X
          EXTFORCE_ACC_Y-VAL
          EXTFORCE_ACC_Y
          EXTFORCE_ACC_Z-VAL
          EXTFORCE_ACC_Z
          EXTFORCE_ACC_FIL_X-VAL
          EXTFORCE_ACC_FIL_X
          EXTFORCE_ACC_FIL_Y-VAL
          EXTFORCE_ACC_FIL_Y
          EXTFORCE_ACC_FIL_Z-VAL
          EXTFORCE_ACC_FIL_Z
          POLY_THRUST-VAL
          POLY_THRUST
          FB_THRUST-VAL
          FB_THRUST
          SUM_THRUST-VAL
          SUM_THRUST
))