(cl:in-package quadrotor_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          ID-VAL
          ID
          FORCE-VAL
          FORCE
          ORIENTATION-VAL
          ORIENTATION
          OMG-VAL
          OMG
          DOMG-VAL
          DOMG
          AUX-VAL
          AUX
          REF_P-VAL
          REF_P
          REF_V-VAL
          REF_V
          REF_A-VAL
          REF_A
          REF_Q-VAL
          REF_Q
          REF_RPY-VAL
          REF_RPY
          REF_F-VAL
          REF_F
          REF_QT-VAL
          REF_QT
          REF_QY-VAL
          REF_QY
))