(cl:in-package quadrotor_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          FB_A_X-VAL
          FB_A_X
          FB_A_Y-VAL
          FB_A_Y
          FB_A_Z-VAL
          FB_A_Z
          DES_P_X-VAL
          DES_P_X
          DES_P_Y-VAL
          DES_P_Y
          DES_P_Z-VAL
          DES_P_Z
          DES_V_X-VAL
          DES_V_X
          DES_V_Y-VAL
          DES_V_Y
          DES_V_Z-VAL
          DES_V_Z
          DES_A_X-VAL
          DES_A_X
          DES_A_Y-VAL
          DES_A_Y
          DES_A_Z-VAL
          DES_A_Z
          DES_Q_X-VAL
          DES_Q_X
          DES_Q_Y-VAL
          DES_Q_Y
          DES_Q_Z-VAL
          DES_Q_Z
          DES_Q_W-VAL
          DES_Q_W
          EST_R-VAL
          EST_R
          EST_P-VAL
          EST_P
          EST_Y-VAL
          EST_Y
          REF_R-VAL
          REF_R
          REF_P-VAL
          REF_P
          REF_Y-VAL
          REF_Y
          DES_R-VAL
          DES_R
          DES_P-VAL
          DES_P
          DES_Y-VAL
          DES_Y
          EXEC_ERR_AXISANG_X-VAL
          EXEC_ERR_AXISANG_X
          EXEC_ERR_AXISANG_Y-VAL
          EXEC_ERR_AXISANG_Y
          EXEC_ERR_AXISANG_Z-VAL
          EXEC_ERR_AXISANG_Z
          EXEC_ERR_AXISANG_ANG-VAL
          EXEC_ERR_AXISANG_ANG
          FB_AXISANG_X-VAL
          FB_AXISANG_X
          FB_AXISANG_Y-VAL
          FB_AXISANG_Y
          FB_AXISANG_Z-VAL
          FB_AXISANG_Z
          FB_AXISANG_ANG-VAL
          FB_AXISANG_ANG
          FB_RATE_X-VAL
          FB_RATE_X
          FB_RATE_Y-VAL
          FB_RATE_Y
          FB_RATE_Z-VAL
          FB_RATE_Z
          DES_BODYRATES_X-VAL
          DES_BODYRATES_X
          DES_BODYRATES_Y-VAL
          DES_BODYRATES_Y
          DES_BODYRATES_Z-VAL
          DES_BODYRATES_Z
          DES_BODYACCS_X-VAL
          DES_BODYACCS_X
          DES_BODYACCS_Y-VAL
          DES_BODYACCS_Y
          DES_BODYACCS_Z-VAL
          DES_BODYACCS_Z
          IMU_AF_X-VAL
          IMU_AF_X
          IMU_AF_Y-VAL
          IMU_AF_Y
          IMU_AF_Z-VAL
          IMU_AF_Z
          IMU_WF_X-VAL
          IMU_WF_X
          IMU_WF_Y-VAL
          IMU_WF_Y
          IMU_WF_Z-VAL
          IMU_WF_Z
          IMU_DW_X-VAL
          IMU_DW_X
          IMU_DW_Y-VAL
          IMU_DW_Y
          IMU_DW_Z-VAL
          IMU_DW_Z
          RPM_F1-VAL
          RPM_F1
          RPM_F2-VAL
          RPM_F2
          RPM_F3-VAL
          RPM_F3
          RPM_F4-VAL
          RPM_F4
          CMD_RPM1-VAL
          CMD_RPM1
          CMD_RPM2-VAL
          CMD_RPM2
          CMD_RPM3-VAL
          CMD_RPM3
          CMD_RPM4-VAL
          CMD_RPM4
          REF_THRUST1-VAL
          REF_THRUST1
          REF_THRUST2-VAL
          REF_THRUST2
          REF_THRUST3-VAL
          REF_THRUST3
          REF_THRUST4-VAL
          REF_THRUST4
          DES_RPM_AVE-VAL
          DES_RPM_AVE
          RPM_AVE-VAL
          RPM_AVE
          DES_YAW-VAL
          DES_YAW
          DES_YAW_RATE-VAL
          DES_YAW_RATE
          DES_YAW_ACC-VAL
          DES_YAW_ACC
          THRO1-VAL
          THRO1
          THRO2-VAL
          THRO2
          THRO3-VAL
          THRO3
          THRO4-VAL
          THRO4
          DELTA_Q_ANG-VAL
          DELTA_Q_ANG
          DES_Q_ANG-VAL
          DES_Q_ANG
          DES_F-VAL
          DES_F
          INDI_F-VAL
          INDI_F
          HOVER_PERCENTAGE-VAL
          HOVER_PERCENTAGE
          THR_SCALE_COMPENSATE-VAL
          THR_SCALE_COMPENSATE
          VOLTAGE-VAL
          VOLTAGE
          REF_V_X-VAL
          REF_V_X
          REF_V_Y-VAL
          REF_V_Y
          REF_V_Z-VAL
          REF_V_Z
          REF_A_X-VAL
          REF_A_X
          REF_A_Y-VAL
          REF_A_Y
          REF_A_Z-VAL
          REF_A_Z
          REF_J_X-VAL
          REF_J_X
          REF_J_Y-VAL
          REF_J_Y
          REF_J_Z-VAL
          REF_J_Z
          REF_S_X-VAL
          REF_S_X
          REF_S_Y-VAL
          REF_S_Y
          REF_S_Z-VAL
          REF_S_Z
          X_POS_ERROR-VAL
          X_POS_ERROR
          Y_POS_ERROR-VAL
          Y_POS_ERROR
          Z_POS_ERROR-VAL
          Z_POS_ERROR
          X_VEL_ERROR-VAL
          X_VEL_ERROR
          Y_VEL_ERROR-VAL
          Y_VEL_ERROR
          Z_VEL_ERROR-VAL
          Z_VEL_ERROR
          REF_THR-VAL
          REF_THR
          DES_THR-VAL
          DES_THR
          EST_THR-VAL
          EST_THR
          DES_TORQUE_X-VAL
          DES_TORQUE_X
          DES_TORQUE_Y-VAL
          DES_TORQUE_Y
          DES_TORQUE_Z-VAL
          DES_TORQUE_Z
          CONT_TORQUE_X-VAL
          CONT_TORQUE_X
          CONT_TORQUE_Y-VAL
          CONT_TORQUE_Y
          CONT_TORQUE_Z-VAL
          CONT_TORQUE_Z
          Z_JWJ-VAL
          Z_JWJ
          FBP_THRUST1-VAL
          FBP_THRUST1
          FBI_THRUST1-VAL
          FBI_THRUST1
          FBP_THRUST2-VAL
          FBP_THRUST2
          FBI_THRUST2-VAL
          FBI_THRUST2
          FBP_THRUST3-VAL
          FBP_THRUST3
          FBI_THRUST3-VAL
          FBI_THRUST3
          FBP_THRUST4-VAL
          FBP_THRUST4
          FBI_THRUST4-VAL
          FBI_THRUST4
          FBP_THRUST-VAL
          FBP_THRUST
          FBI_THRUST-VAL
          FBI_THRUST
          FB_THRUST-VAL
          FB_THRUST
          RPM_ERROR1-VAL
          RPM_ERROR1
          RPM_ERROR_SUM1-VAL
          RPM_ERROR_SUM1
          RPM_ERROR2-VAL
          RPM_ERROR2
          RPM_ERROR_SUM2-VAL
          RPM_ERROR_SUM2
          RPM_ERROR3-VAL
          RPM_ERROR3
          RPM_ERROR_SUM3-VAL
          RPM_ERROR_SUM3
          RPM_ERROR4-VAL
          RPM_ERROR4
          RPM_ERROR_SUM4-VAL
          RPM_ERROR_SUM4
          RATE_ERROR_Z-VAL
          RATE_ERROR_Z
          RATE_ERROR_SUM_Z-VAL
          RATE_ERROR_SUM_Z
          FBP_BODYACC_Z-VAL
          FBP_BODYACC_Z
          FBI_BODYACC_Z-VAL
          FBI_BODYACC_Z
          DES_EST_BODYRATES_X-VAL
          DES_EST_BODYRATES_X
          DES_EST_BODYRATES_Y-VAL
          DES_EST_BODYRATES_Y
          DES_EST_BODYRATES_Z-VAL
          DES_EST_BODYRATES_Z
          ACC_ERROR1-VAL
          ACC_ERROR1
          ACC_ERROR2-VAL
          ACC_ERROR2
          ACC_ERROR3-VAL
          ACC_ERROR3
          ACC_ERROR4-VAL
          ACC_ERROR4
          ACC_ERRORSUM1-VAL
          ACC_ERRORSUM1
          ACC_ERRORSUM2-VAL
          ACC_ERRORSUM2
          ACC_ERRORSUM3-VAL
          ACC_ERRORSUM3
          ACC_ERRORSUM4-VAL
          ACC_ERRORSUM4
          WINDOW_AVE1-VAL
          WINDOW_AVE1
          WINDOW_AVE2-VAL
          WINDOW_AVE2
          WINDOW_AVE3-VAL
          WINDOW_AVE3
          WINDOW_AVE4-VAL
          WINDOW_AVE4
          POS_ERROR_ALL-VAL
          POS_ERROR_ALL
          POS_ERROR_XY-VAL
          POS_ERROR_XY
          POS_ERROR_RMSE-VAL
          POS_ERROR_RMSE
          VEL_ERROR_ALL-VAL
          VEL_ERROR_ALL
          DES_V_ALL-VAL
          DES_V_ALL
          REF_BODYRATES_X-VAL
          REF_BODYRATES_X
          REF_BODYRATES_Y-VAL
          REF_BODYRATES_Y
          REF_BODYRATES_Z-VAL
          REF_BODYRATES_Z
          EXTTOTALACCINDI_X-VAL
          EXTTOTALACCINDI_X
          EXTTOTALACCINDI_Y-VAL
          EXTTOTALACCINDI_Y
          EXTTOTALACCINDI_Z-VAL
          EXTTOTALACCINDI_Z
          AW_X-VAL
          AW_X
          AW_Y-VAL
          AW_Y
          AW_Z-VAL
          AW_Z
          FB_A_X_FIL-VAL
          FB_A_X_FIL
          FB_A_Y_FIL-VAL
          FB_A_Y_FIL
          FB_A_Z_FIL-VAL
          FB_A_Z_FIL
          EXTF_PSI-VAL
          EXTF_PSI
          EXTF_THETA-VAL
          EXTF_THETA
          DES_FQ_PSI-VAL
          DES_FQ_PSI
          DES_FQ_THETA-VAL
          DES_FQ_THETA
          INDI_Q_ERR_ANG-VAL
          INDI_Q_ERR_ANG
          FB_F_X-VAL
          FB_F_X
          FB_F_Y-VAL
          FB_F_Y
          FB_F_Z-VAL
          FB_F_Z
          FLAG-VAL
          FLAG
          INDI_ACC_Q_ERROR_X-VAL
          INDI_ACC_Q_ERROR_X
          INDI_ACC_Q_ERROR_Y-VAL
          INDI_ACC_Q_ERROR_Y
          INDI_ACC_Q_ERROR_Z-VAL
          INDI_ACC_Q_ERROR_Z
          F_ERROR-VAL
          F_ERROR
          INDI_ACC_F_ERROR_X-VAL
          INDI_ACC_F_ERROR_X
          INDI_ACC_F_ERROR_Y-VAL
          INDI_ACC_F_ERROR_Y
          INDI_ACC_F_ERROR_Z-VAL
          INDI_ACC_F_ERROR_Z
          INDIF_X-VAL
          INDIF_X
          INDIF_Y-VAL
          INDIF_Y
          INDIF_Z-VAL
          INDIF_Z
          DESFQ_X-VAL
          DESFQ_X
          DESFQ_Y-VAL
          DESFQ_Y
          DESFQ_Z-VAL
          DESFQ_Z
          FB_PV_X-VAL
          FB_PV_X
          FB_PV_Y-VAL
          FB_PV_Y
          FB_PV_Z-VAL
          FB_PV_Z
          FB_Q_X-VAL
          FB_Q_X
          FB_Q_Y-VAL
          FB_Q_Y
          FB_Q_Z-VAL
          FB_Q_Z
          FB_FQ_X-VAL
          FB_FQ_X
          FB_FQ_Y-VAL
          FB_FQ_Y
          FB_FQ_Z-VAL
          FB_FQ_Z
          V_MODI_X-VAL
          V_MODI_X
          V_MODI_Y-VAL
          V_MODI_Y
          V_MODI_Z-VAL
          V_MODI_Z
          FB_FQ_ERROR_FIL_X-VAL
          FB_FQ_ERROR_FIL_X
          FB_FQ_ERROR_FIL_Y-VAL
          FB_FQ_ERROR_FIL_Y
          FB_FQ_ERROR_FIL_Z-VAL
          FB_FQ_ERROR_FIL_Z
          FUPPER-VAL
          FUPPER
          FLOWER-VAL
          FLOWER
          REF_RPM1-VAL
          REF_RPM1
          REF_RPM2-VAL
          REF_RPM2
          REF_RPM3-VAL
          REF_RPM3
          REF_RPM4-VAL
          REF_RPM4
          REF_TORQUE_X-VAL
          REF_TORQUE_X
          REF_TORQUE_Y-VAL
          REF_TORQUE_Y
          REF_TORQUE_Z-VAL
          REF_TORQUE_Z
          INDI_F_LIMIT-VAL
          INDI_F_LIMIT
))