
(cl:in-package :asdf)

(defsystem "quadrotor_msgs-msg"
  :depends-on (:roslisp-msg-protocol :roslisp-utils :geometry_msgs-msg
               :nav_msgs-msg
               :std_msgs-msg
)
  :components ((:file "_package")
    (:file "AstarPath" :depends-on ("_package_AstarPath"))
    (:file "_package_AstarPath" :depends-on ("_package"))
    (:file "AstarPathPoint" :depends-on ("_package_AstarPathPoint"))
    (:file "_package_AstarPathPoint" :depends-on ("_package"))
    (:file "AuxCommand" :depends-on ("_package_AuxCommand"))
    (:file "_package_AuxCommand" :depends-on ("_package"))
    (:file "Corrections" :depends-on ("_package_Corrections"))
    (:file "_package_Corrections" :depends-on ("_package"))
    (:file "CorridorPolytope" :depends-on ("_package_CorridorPolytope"))
    (:file "_package_CorridorPolytope" :depends-on ("_package"))
    (:file "Gains" :depends-on ("_package_Gains"))
    (:file "_package_Gains" :depends-on ("_package"))
    (:file "IndiState" :depends-on ("_package_IndiState"))
    (:file "_package_IndiState" :depends-on ("_package"))
    (:file "LQRTrajectory" :depends-on ("_package_LQRTrajectory"))
    (:file "_package_LQRTrajectory" :depends-on ("_package"))
    (:file "LoadCorridor" :depends-on ("_package_LoadCorridor"))
    (:file "_package_LoadCorridor" :depends-on ("_package"))
    (:file "Odometry" :depends-on ("_package_Odometry"))
    (:file "_package_Odometry" :depends-on ("_package"))
    (:file "OutputData" :depends-on ("_package_OutputData"))
    (:file "_package_OutputData" :depends-on ("_package"))
    (:file "PPROutputData" :depends-on ("_package_PPROutputData"))
    (:file "_package_PPROutputData" :depends-on ("_package"))
    (:file "PolyTraj" :depends-on ("_package_PolyTraj"))
    (:file "_package_PolyTraj" :depends-on ("_package"))
    (:file "PolynomialTrajectory" :depends-on ("_package_PolynomialTrajectory"))
    (:file "_package_PolynomialTrajectory" :depends-on ("_package"))
    (:file "PositionCommand" :depends-on ("_package_PositionCommand"))
    (:file "_package_PositionCommand" :depends-on ("_package"))
    (:file "PositionCommandLoad" :depends-on ("_package_PositionCommandLoad"))
    (:file "_package_PositionCommandLoad" :depends-on ("_package"))
    (:file "PositionCommandNew" :depends-on ("_package_PositionCommandNew"))
    (:file "_package_PositionCommandNew" :depends-on ("_package"))
    (:file "Px4ctrlDebug" :depends-on ("_package_Px4ctrlDebug"))
    (:file "_package_Px4ctrlDebug" :depends-on ("_package"))
    (:file "Rpms" :depends-on ("_package_Rpms"))
    (:file "_package_Rpms" :depends-on ("_package"))
    (:file "SO3Command" :depends-on ("_package_SO3Command"))
    (:file "_package_SO3Command" :depends-on ("_package"))
    (:file "Serial" :depends-on ("_package_Serial"))
    (:file "_package_Serial" :depends-on ("_package"))
    (:file "SimState" :depends-on ("_package_SimState"))
    (:file "_package_SimState" :depends-on ("_package"))
    (:file "StatusData" :depends-on ("_package_StatusData"))
    (:file "_package_StatusData" :depends-on ("_package"))
    (:file "TRPYCommand" :depends-on ("_package_TRPYCommand"))
    (:file "_package_TRPYCommand" :depends-on ("_package"))
    (:file "TakeoffLand" :depends-on ("_package_TakeoffLand"))
    (:file "_package_TakeoffLand" :depends-on ("_package"))
    (:file "geDebug" :depends-on ("_package_geDebug"))
    (:file "_package_geDebug" :depends-on ("_package"))
    (:file "trigger" :depends-on ("_package_trigger"))
    (:file "_package_trigger" :depends-on ("_package"))
  ))