// Generated by gencpp from file grid_path_searcher/AstarPath.msg
// DO NOT EDIT!


#ifndef GRID_PATH_SEARCHER_MESSAGE_ASTARPATH_H
#define GRID_PATH_SEARCHER_MESSAGE_ASTARPATH_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <grid_path_searcher/AstarPathPoint.h>

namespace grid_path_searcher
{
template <class ContainerAllocator>
struct AstarPath_
{
  typedef AstarPath_<ContainerAllocator> Type;

  AstarPath_()
    : header()
    , points()  {
    }
  AstarPath_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , points(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::grid_path_searcher::AstarPathPoint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::grid_path_searcher::AstarPathPoint_<ContainerAllocator> >> _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::grid_path_searcher::AstarPath_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grid_path_searcher::AstarPath_<ContainerAllocator> const> ConstPtr;

}; // struct AstarPath_

typedef ::grid_path_searcher::AstarPath_<std::allocator<void> > AstarPath;

typedef boost::shared_ptr< ::grid_path_searcher::AstarPath > AstarPathPtr;
typedef boost::shared_ptr< ::grid_path_searcher::AstarPath const> AstarPathConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grid_path_searcher::AstarPath_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grid_path_searcher::AstarPath_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::grid_path_searcher::AstarPath_<ContainerAllocator1> & lhs, const ::grid_path_searcher::AstarPath_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::grid_path_searcher::AstarPath_<ContainerAllocator1> & lhs, const ::grid_path_searcher::AstarPath_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace grid_path_searcher

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::grid_path_searcher::AstarPath_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grid_path_searcher::AstarPath_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grid_path_searcher::AstarPath_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grid_path_searcher::AstarPath_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grid_path_searcher::AstarPath_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grid_path_searcher::AstarPath_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grid_path_searcher::AstarPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89c845f19440f2177b6bb178d87c77c4";
  }

  static const char* value(const ::grid_path_searcher::AstarPath_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89c845f19440f217ULL;
  static const uint64_t static_value2 = 0x7b6bb178d87c77c4ULL;
};

template<class ContainerAllocator>
struct DataType< ::grid_path_searcher::AstarPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grid_path_searcher/AstarPath";
  }

  static const char* value(const ::grid_path_searcher::AstarPath_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grid_path_searcher::AstarPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"grid_path_searcher/AstarPathPoint[] points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: grid_path_searcher/AstarPathPoint\n"
"geometry_msgs/Point position\n"
"float64 angle_deg\n"
"float64 clearance_m\n"
"float64 arc_length_m\n"
"float64 curvature\n"
"float64 complexity\n"
"float64 desired_spacing_m\n"
"bool selected_as_waypoint\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::grid_path_searcher::AstarPath_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grid_path_searcher::AstarPath_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AstarPath_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grid_path_searcher::AstarPath_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grid_path_searcher::AstarPath_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "points: ";
    if (v.points.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::grid_path_searcher::AstarPathPoint_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.points[i]);
    }
    if (v.points.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRID_PATH_SEARCHER_MESSAGE_ASTARPATH_H
