// Generated by gencpp from file grid_path_searcher/AstarPathPoint.msg
// DO NOT EDIT!


#ifndef GRID_PATH_SEARCHER_MESSAGE_ASTARPATHPOINT_H
#define GRID_PATH_SEARCHER_MESSAGE_ASTARPATHPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace grid_path_searcher
{
template <class ContainerAllocator>
struct AstarPathPoint_
{
  typedef AstarPathPoint_<ContainerAllocator> Type;

  AstarPathPoint_()
    : position()
    , angle_deg(0.0)
    , clearance_m(0.0)
    , arc_length_m(0.0)
    , curvature(0.0)
    , complexity(0.0)
    , desired_spacing_m(0.0)
    , selected_as_waypoint(false)  {
    }
  AstarPathPoint_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , angle_deg(0.0)
    , clearance_m(0.0)
    , arc_length_m(0.0)
    , curvature(0.0)
    , complexity(0.0)
    , desired_spacing_m(0.0)
    , selected_as_waypoint(false)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef double _angle_deg_type;
  _angle_deg_type angle_deg;

   typedef double _clearance_m_type;
  _clearance_m_type clearance_m;

   typedef double _arc_length_m_type;
  _arc_length_m_type arc_length_m;

   typedef double _curvature_type;
  _curvature_type curvature;

   typedef double _complexity_type;
  _complexity_type complexity;

   typedef double _desired_spacing_m_type;
  _desired_spacing_m_type desired_spacing_m;

   typedef uint8_t _selected_as_waypoint_type;
  _selected_as_waypoint_type selected_as_waypoint;





  typedef boost::shared_ptr< ::grid_path_searcher::AstarPathPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grid_path_searcher::AstarPathPoint_<ContainerAllocator> const> ConstPtr;

}; // struct AstarPathPoint_

typedef ::grid_path_searcher::AstarPathPoint_<std::allocator<void> > AstarPathPoint;

typedef boost::shared_ptr< ::grid_path_searcher::AstarPathPoint > AstarPathPointPtr;
typedef boost::shared_ptr< ::grid_path_searcher::AstarPathPoint const> AstarPathPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grid_path_searcher::AstarPathPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grid_path_searcher::AstarPathPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::grid_path_searcher::AstarPathPoint_<ContainerAllocator1> & lhs, const ::grid_path_searcher::AstarPathPoint_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.angle_deg == rhs.angle_deg &&
    lhs.clearance_m == rhs.clearance_m &&
    lhs.arc_length_m == rhs.arc_length_m &&
    lhs.curvature == rhs.curvature &&
    lhs.complexity == rhs.complexity &&
    lhs.desired_spacing_m == rhs.desired_spacing_m &&
    lhs.selected_as_waypoint == rhs.selected_as_waypoint;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::grid_path_searcher::AstarPathPoint_<ContainerAllocator1> & lhs, const ::grid_path_searcher::AstarPathPoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace grid_path_searcher

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::grid_path_searcher::AstarPathPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grid_path_searcher::AstarPathPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grid_path_searcher::AstarPathPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grid_path_searcher::AstarPathPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grid_path_searcher::AstarPathPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grid_path_searcher::AstarPathPoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grid_path_searcher::AstarPathPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d8313e5fbfae9cb5949798e6a59c10b3";
  }

  static const char* value(const ::grid_path_searcher::AstarPathPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd8313e5fbfae9cb5ULL;
  static const uint64_t static_value2 = 0x949798e6a59c10b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::grid_path_searcher::AstarPathPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grid_path_searcher/AstarPathPoint";
  }

  static const char* value(const ::grid_path_searcher::AstarPathPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grid_path_searcher::AstarPathPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point position\n"
"float64 angle_deg\n"
"float64 clearance_m\n"
"float64 arc_length_m\n"
"float64 curvature\n"
"float64 complexity\n"
"float64 desired_spacing_m\n"
"bool selected_as_waypoint\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::grid_path_searcher::AstarPathPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grid_path_searcher::AstarPathPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.angle_deg);
      stream.next(m.clearance_m);
      stream.next(m.arc_length_m);
      stream.next(m.curvature);
      stream.next(m.complexity);
      stream.next(m.desired_spacing_m);
      stream.next(m.selected_as_waypoint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AstarPathPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grid_path_searcher::AstarPathPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grid_path_searcher::AstarPathPoint_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "position: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "angle_deg: ";
    Printer<double>::stream(s, indent + "  ", v.angle_deg);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "clearance_m: ";
    Printer<double>::stream(s, indent + "  ", v.clearance_m);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "arc_length_m: ";
    Printer<double>::stream(s, indent + "  ", v.arc_length_m);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "curvature: ";
    Printer<double>::stream(s, indent + "  ", v.curvature);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "complexity: ";
    Printer<double>::stream(s, indent + "  ", v.complexity);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "desired_spacing_m: ";
    Printer<double>::stream(s, indent + "  ", v.desired_spacing_m);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "selected_as_waypoint: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.selected_as_waypoint);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRID_PATH_SEARCHER_MESSAGE_ASTARPATHPOINT_H
