// Generated by gencpp from file quadrotor_msgs/AstarPathPoint.msg
// DO NOT EDIT!


#ifndef QUADROTOR_MSGS_MESSAGE_ASTARPATHPOINT_H
#define QUADROTOR_MSGS_MESSAGE_ASTARPATHPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace quadrotor_msgs
{
template <class ContainerAllocator>
struct AstarPathPoint_
{
  typedef AstarPathPoint_<ContainerAllocator> Type;

  AstarPathPoint_()
    : position()
    , angle(0.0)
    , clearance(0.0)
    , waypoint(false)  {
    }
  AstarPathPoint_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , angle(0.0)
    , clearance(0.0)
    , waypoint(false)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef double _angle_type;
  _angle_type angle;

   typedef double _clearance_type;
  _clearance_type clearance;

   typedef uint8_t _waypoint_type;
  _waypoint_type waypoint;





  typedef boost::shared_ptr< ::quadrotor_msgs::AstarPathPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotor_msgs::AstarPathPoint_<ContainerAllocator> const> ConstPtr;

}; // struct AstarPathPoint_

typedef ::quadrotor_msgs::AstarPathPoint_<std::allocator<void> > AstarPathPoint;

typedef boost::shared_ptr< ::quadrotor_msgs::AstarPathPoint > AstarPathPointPtr;
typedef boost::shared_ptr< ::quadrotor_msgs::AstarPathPoint const> AstarPathPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quadrotor_msgs::AstarPathPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quadrotor_msgs::AstarPathPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quadrotor_msgs::AstarPathPoint_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::AstarPathPoint_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.angle == rhs.angle &&
    lhs.clearance == rhs.clearance &&
    lhs.waypoint == rhs.waypoint;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quadrotor_msgs::AstarPathPoint_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::AstarPathPoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quadrotor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::AstarPathPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::AstarPathPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::AstarPathPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::AstarPathPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::AstarPathPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::AstarPathPoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quadrotor_msgs::AstarPathPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4f3f50b66c9f55c6a0c57168ac23576a";
  }

  static const char* value(const ::quadrotor_msgs::AstarPathPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4f3f50b66c9f55c6ULL;
  static const uint64_t static_value2 = 0xa0c57168ac23576aULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotor_msgs::AstarPathPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quadrotor_msgs/AstarPathPoint";
  }

  static const char* value(const ::quadrotor_msgs::AstarPathPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quadrotor_msgs::AstarPathPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point position\n"
"float64 angle\n"
"float64 clearance\n"
"bool waypoint\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::quadrotor_msgs::AstarPathPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quadrotor_msgs::AstarPathPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.angle);
      stream.next(m.clearance);
      stream.next(m.waypoint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AstarPathPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadrotor_msgs::AstarPathPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quadrotor_msgs::AstarPathPoint_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "position: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "clearance: ";
    Printer<double>::stream(s, indent + "  ", v.clearance);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "waypoint: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.waypoint);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUADROTOR_MSGS_MESSAGE_ASTARPATHPOINT_H
