// Generated by gencpp from file quadrotor_msgs/AstarPath.msg
// DO NOT EDIT!


#ifndef QUADROTOR_MSGS_MESSAGE_ASTARPATH_H
#define QUADROTOR_MSGS_MESSAGE_ASTARPATH_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <quadrotor_msgs/AstarPathPoint.h>

namespace quadrotor_msgs
{
template <class ContainerAllocator>
struct AstarPath_
{
  typedef AstarPath_<ContainerAllocator> Type;

  AstarPath_()
    : header()
    , start()
    , goal()
    , points()  {
    }
  AstarPath_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , start(_alloc)
    , goal(_alloc)
    , points(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _start_type;
  _start_type start;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _goal_type;
  _goal_type goal;

   typedef std::vector< ::quadrotor_msgs::AstarPathPoint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::quadrotor_msgs::AstarPathPoint_<ContainerAllocator> >> _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::quadrotor_msgs::AstarPath_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotor_msgs::AstarPath_<ContainerAllocator> const> ConstPtr;

}; // struct AstarPath_

typedef ::quadrotor_msgs::AstarPath_<std::allocator<void> > AstarPath;

typedef boost::shared_ptr< ::quadrotor_msgs::AstarPath > AstarPathPtr;
typedef boost::shared_ptr< ::quadrotor_msgs::AstarPath const> AstarPathConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quadrotor_msgs::AstarPath_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quadrotor_msgs::AstarPath_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quadrotor_msgs::AstarPath_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::AstarPath_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.start == rhs.start &&
    lhs.goal == rhs.goal &&
    lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quadrotor_msgs::AstarPath_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::AstarPath_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quadrotor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::AstarPath_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::AstarPath_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::AstarPath_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::AstarPath_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::AstarPath_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::AstarPath_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quadrotor_msgs::AstarPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c042622e5284a67df730df6129bec0d8";
  }

  static const char* value(const ::quadrotor_msgs::AstarPath_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc042622e5284a67dULL;
  static const uint64_t static_value2 = 0xf730df6129bec0d8ULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotor_msgs::AstarPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quadrotor_msgs/AstarPath";
  }

  static const char* value(const ::quadrotor_msgs::AstarPath_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quadrotor_msgs::AstarPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"geometry_msgs/Point start\n"
"geometry_msgs/Point goal\n"
"quadrotor_msgs/AstarPathPoint[] points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: quadrotor_msgs/AstarPathPoint\n"
"geometry_msgs/Point position\n"
"float64 angle\n"
"float64 clearance\n"
"bool waypoint\n"
;
  }

  static const char* value(const ::quadrotor_msgs::AstarPath_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quadrotor_msgs::AstarPath_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.start);
      stream.next(m.goal);
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AstarPath_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadrotor_msgs::AstarPath_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quadrotor_msgs::AstarPath_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "start: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.start);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "goal: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "points: ";
    if (v.points.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::quadrotor_msgs::AstarPathPoint_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.points[i]);
    }
    if (v.points.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUADROTOR_MSGS_MESSAGE_ASTARPATH_H
