// Generated by gencpp from file quadrotor_msgs/CorridorPolytope.msg
// DO NOT EDIT!


#ifndef QUADROTOR_MSGS_MESSAGE_CORRIDORPOLYTOPE_H
#define QUADROTOR_MSGS_MESSAGE_CORRIDORPOLYTOPE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Point.h>

namespace quadrotor_msgs
{
template <class ContainerAllocator>
struct CorridorPolytope_
{
  typedef CorridorPolytope_<ContainerAllocator> Type;

  CorridorPolytope_()
    : path_begin(0)
    , path_end(0)
    , normals()
    , offsets()
    , vertices()
    , clearance_bridge(false)
    , complexity(0.0)
    , local_extent(0.0)
    , minimum_system_margin(0.0)
    , maximum_system_margin(0.0)  {
    }
  CorridorPolytope_(const ContainerAllocator& _alloc)
    : path_begin(0)
    , path_end(0)
    , normals(_alloc)
    , offsets(_alloc)
    , vertices(_alloc)
    , clearance_bridge(false)
    , complexity(0.0)
    , local_extent(0.0)
    , minimum_system_margin(0.0)
    , maximum_system_margin(0.0)  {
  (void)_alloc;
    }



   typedef uint32_t _path_begin_type;
  _path_begin_type path_begin;

   typedef uint32_t _path_end_type;
  _path_end_type path_end;

   typedef std::vector< ::geometry_msgs::Vector3_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Vector3_<ContainerAllocator> >> _normals_type;
  _normals_type normals;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _offsets_type;
  _offsets_type offsets;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _vertices_type;
  _vertices_type vertices;

   typedef uint8_t _clearance_bridge_type;
  _clearance_bridge_type clearance_bridge;

   typedef double _complexity_type;
  _complexity_type complexity;

   typedef double _local_extent_type;
  _local_extent_type local_extent;

   typedef double _minimum_system_margin_type;
  _minimum_system_margin_type minimum_system_margin;

   typedef double _maximum_system_margin_type;
  _maximum_system_margin_type maximum_system_margin;





  typedef boost::shared_ptr< ::quadrotor_msgs::CorridorPolytope_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotor_msgs::CorridorPolytope_<ContainerAllocator> const> ConstPtr;

}; // struct CorridorPolytope_

typedef ::quadrotor_msgs::CorridorPolytope_<std::allocator<void> > CorridorPolytope;

typedef boost::shared_ptr< ::quadrotor_msgs::CorridorPolytope > CorridorPolytopePtr;
typedef boost::shared_ptr< ::quadrotor_msgs::CorridorPolytope const> CorridorPolytopeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quadrotor_msgs::CorridorPolytope_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quadrotor_msgs::CorridorPolytope_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quadrotor_msgs::CorridorPolytope_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::CorridorPolytope_<ContainerAllocator2> & rhs)
{
  return lhs.path_begin == rhs.path_begin &&
    lhs.path_end == rhs.path_end &&
    lhs.normals == rhs.normals &&
    lhs.offsets == rhs.offsets &&
    lhs.vertices == rhs.vertices &&
    lhs.clearance_bridge == rhs.clearance_bridge &&
    lhs.complexity == rhs.complexity &&
    lhs.local_extent == rhs.local_extent &&
    lhs.minimum_system_margin == rhs.minimum_system_margin &&
    lhs.maximum_system_margin == rhs.maximum_system_margin;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quadrotor_msgs::CorridorPolytope_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::CorridorPolytope_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quadrotor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::CorridorPolytope_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::CorridorPolytope_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::CorridorPolytope_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::CorridorPolytope_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::CorridorPolytope_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::CorridorPolytope_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quadrotor_msgs::CorridorPolytope_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f1ee3021eb38c109bf2fef158ffb37a4";
  }

  static const char* value(const ::quadrotor_msgs::CorridorPolytope_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf1ee3021eb38c109ULL;
  static const uint64_t static_value2 = 0xbf2fef158ffb37a4ULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotor_msgs::CorridorPolytope_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quadrotor_msgs/CorridorPolytope";
  }

  static const char* value(const ::quadrotor_msgs::CorridorPolytope_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quadrotor_msgs::CorridorPolytope_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 path_begin\n"
"uint32 path_end\n"
"geometry_msgs/Vector3[] normals\n"
"float64[] offsets\n"
"geometry_msgs/Point[] vertices\n"
"bool clearance_bridge\n"
"float64 complexity\n"
"float64 local_extent\n"
"float64 minimum_system_margin\n"
"float64 maximum_system_margin\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::quadrotor_msgs::CorridorPolytope_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quadrotor_msgs::CorridorPolytope_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path_begin);
      stream.next(m.path_end);
      stream.next(m.normals);
      stream.next(m.offsets);
      stream.next(m.vertices);
      stream.next(m.clearance_bridge);
      stream.next(m.complexity);
      stream.next(m.local_extent);
      stream.next(m.minimum_system_margin);
      stream.next(m.maximum_system_margin);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CorridorPolytope_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadrotor_msgs::CorridorPolytope_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quadrotor_msgs::CorridorPolytope_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "path_begin: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.path_begin);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "path_end: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.path_end);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "normals: ";
    if (v.normals.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.normals.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.normals[i]);
    }
    if (v.normals.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "offsets: ";
    if (v.offsets.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.offsets.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.offsets[i]);
    }
    if (v.offsets.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vertices: ";
    if (v.vertices.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.vertices.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.vertices[i]);
    }
    if (v.vertices.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "clearance_bridge: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.clearance_bridge);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "complexity: ";
    Printer<double>::stream(s, indent + "  ", v.complexity);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "local_extent: ";
    Printer<double>::stream(s, indent + "  ", v.local_extent);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "minimum_system_margin: ";
    Printer<double>::stream(s, indent + "  ", v.minimum_system_margin);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "maximum_system_margin: ";
    Printer<double>::stream(s, indent + "  ", v.maximum_system_margin);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUADROTOR_MSGS_MESSAGE_CORRIDORPOLYTOPE_H
