// Generated by gencpp from file quadrotor_msgs/geDebug.msg
// DO NOT EDIT!


#ifndef QUADROTOR_MSGS_MESSAGE_GEDEBUG_H
#define QUADROTOR_MSGS_MESSAGE_GEDEBUG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace quadrotor_msgs
{
template <class ContainerAllocator>
struct geDebug_
{
  typedef geDebug_<ContainerAllocator> Type;

  geDebug_()
    : header()
    , odom_roll(0.0)
    , odom_pitch(0.0)
    , odom_yaw(0.0)
    , odomC_roll(0.0)
    , odomC_pitch(0.0)
    , odomC_yaw(0.0)
    , ge_angle_roll(0.0)
    , ge_angle_pitch(0.0)
    , ge_angle_yaw(0.0)
    , imu_a_x(0.0)
    , imu_a_y(0.0)
    , imu_a_z(0.0)
    , imu_a_fil_x(0.0)
    , imu_a_fil_y(0.0)
    , imu_a_fil_z(0.0)
    , imu_w_x(0.0)
    , imu_w_y(0.0)
    , imu_w_z(0.0)
    , imu_w_fil_x(0.0)
    , imu_w_fil_y(0.0)
    , imu_w_fil_z(0.0)
    , imu_w_c_x(0.0)
    , imu_w_c_y(0.0)
    , imu_w_c_z(0.0)
    , imu_beta_fil_x(0.0)
    , imu_beta_fil_y(0.0)
    , imu_beta_fil_z(0.0)
    , rpm1(0.0)
    , rpm2(0.0)
    , rpm3(0.0)
    , rpm4(0.0)
    , rpm1_fil(0.0)
    , rpm2_fil(0.0)
    , rpm3_fil(0.0)
    , rpm4_fil(0.0)
    , sumrpm2(0.0)
    , thrust_force(0.0)
    , thrust_acc(0.0)
    , sumrpm2_fil(0.0)
    , thrust_force_fil(0.0)
    , thrust_acc_fil(0.0)
    , acc_world_x(0.0)
    , acc_world_y(0.0)
    , acc_world_z(0.0)
    , ge_acc_x(0.0)
    , ge_acc_y(0.0)
    , ge_acc_z(0.0)
    , ge_bodytorque_x(0.0)
    , ge_bodytorque_y(0.0)
    , ge_bodytorque_z(0.0)
    , des_ge_bodytorque_x(0.0)
    , des_ge_bodytorque_y(0.0)
    , des_ge_bodytorque_z(0.0)
    , d_ge_torque_x(0.0)
    , d_ge_torque_y(0.0)
    , d_ge_torque_z(0.0)
    , diff_ge_torque_x(0.0)
    , diff_ge_torque_y(0.0)
    , diff_ge_torque_z(0.0)
    , ext_torque_x(0.0)
    , ext_torque_y(0.0)
    , ext_torque_z(0.0)
    , predict_ext_torque_x(0.0)
    , predict_ext_torque_y(0.0)
    , predict_ext_torque_z(0.0)
    , des_p_x(0.0)
    , des_p_y(0.0)
    , des_p_z(0.0)
    , des_v_x(0.0)
    , des_v_y(0.0)
    , des_v_z(0.0)
    , des_a_x(0.0)
    , des_a_y(0.0)
    , des_a_z(0.0)
    , des_j_x(0.0)
    , des_j_y(0.0)
    , des_j_z(0.0)
    , des_s_x(0.0)
    , des_s_y(0.0)
    , des_s_z(0.0)
    , des_yaw(0.0)
    , des_yaw_rate(0.0)
    , des_yaw_acc(0.0)
    , flatctrl_q_w(0.0)
    , flatctrl_q_x(0.0)
    , flatctrl_q_y(0.0)
    , flatctrl_q_z(0.0)
    , flatctrl_roll(0.0)
    , flatctrl_pitch(0.0)
    , flatctrl_yaw(0.0)
    , flatctrl_bodyrate_x(0.0)
    , flatctrl_bodyrate_y(0.0)
    , flatctrl_bodyrate_z(0.0)
    , flatctrl_beta_x(0.0)
    , flatctrl_beta_y(0.0)
    , flatctrl_beta_z(0.0)
    , flatctrl_thrust(0.0)
    , flatctrl_torque_x(0.0)
    , flatctrl_torque_y(0.0)
    , flatctrl_torque_z(0.0)
    , flatctrl_ge_acc_x(0.0)
    , flatctrl_ge_acc_y(0.0)
    , flatctrl_ge_acc_z(0.0)
    , flatctrl_drag_acc_x(0.0)
    , flatctrl_drag_acc_y(0.0)
    , flatctrl_drag_acc_z(0.0)
    , flatctrl_ext_acc_x(0.0)
    , flatctrl_ext_acc_y(0.0)
    , flatctrl_ext_acc_z(0.0)
    , ge_limit_k(0.0)
    , fb_vel_x(0.0)
    , fb_vel_y(0.0)
    , fb_vel_z(0.0)
    , cmd_vel_x(0.0)
    , cmd_vel_y(0.0)
    , cmd_vel_z(0.0)
    , compensate_acc_x(0.0)
    , compensate_acc_y(0.0)
    , compensate_acc_z(0.0)
    , fb_acc_x(0.0)
    , fb_acc_y(0.0)
    , fb_acc_z(0.0)
    , cmd_acc_x(0.0)
    , cmd_acc_y(0.0)
    , cmd_acc_z(0.0)
    , cmd_acc_norm(0.0)
    , cmd_acc_norm_by_body(0.0)
    , cmd_q_w(0.0)
    , cmd_q_x(0.0)
    , cmd_q_y(0.0)
    , cmd_q_z(0.0)
    , cmd_roll(0.0)
    , cmd_pitch(0.0)
    , cmd_yaw(0.0)
    , fb_bodyrate_x(0.0)
    , fb_bodyrate_y(0.0)
    , fb_bodyrate_z(0.0)
    , cmd_bodyrate_x(0.0)
    , cmd_bodyrate_y(0.0)
    , cmd_bodyrate_z(0.0)
    , fb_beta_x(0.0)
    , fb_beta_y(0.0)
    , fb_beta_z(0.0)
    , cmd_beta_x(0.0)
    , cmd_beta_y(0.0)
    , cmd_beta_z(0.0)
    , compensate_torque_x(0.0)
    , compensate_torque_y(0.0)
    , compensate_torque_z(0.0)
    , bodytorque_x(0.0)
    , bodytorque_y(0.0)
    , bodytorque_z(0.0)
    , cmd_torque_body_x(0.0)
    , cmd_torque_body_y(0.0)
    , cmd_torque_body_z(0.0)
    , diff_indi_torque_x(0.0)
    , diff_indi_torque_y(0.0)
    , diff_indi_torque_z(0.0)
    , diff_torque_x(0.0)
    , diff_torque_y(0.0)
    , diff_torque_z(0.0)
    , cmd_rpm1(0.0)
    , cmd_rpm2(0.0)
    , cmd_rpm3(0.0)
    , cmd_rpm4(0.0)
    , cmd_sumrpm2(0.0)
    , cmd_sumrpm2_to_acc(0.0)
    , fb_thrust1(0.0)
    , fb_thrust2(0.0)
    , fb_thrust3(0.0)
    , fb_thrust4(0.0)
    , ref_thrust1(0.0)
    , ref_thrust2(0.0)
    , ref_thrust3(0.0)
    , ref_thrust4(0.0)
    , cmd_thrust1(0.0)
    , cmd_thrust2(0.0)
    , cmd_thrust3(0.0)
    , cmd_thrust4(0.0)
    , Fgh(0.0)
    , ref_thrust_acc(0.0)
    , thrust_acc_fil_x(0.0)
    , thrust_acc_fil_y(0.0)
    , thrust_acc_fil_z(0.0)
    , imu_acc_fil_x(0.0)
    , imu_acc_fil_y(0.0)
    , imu_acc_fil_z(0.0)
    , extforce_acc_x(0.0)
    , extforce_acc_y(0.0)
    , extforce_acc_z(0.0)
    , extforce_acc_fil_x(0.0)
    , extforce_acc_fil_y(0.0)
    , extforce_acc_fil_z(0.0)
    , poly_thrust(0.0)
    , fb_thrust(0.0)
    , sum_thrust(0.0)  {
    }
  geDebug_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , odom_roll(0.0)
    , odom_pitch(0.0)
    , odom_yaw(0.0)
    , odomC_roll(0.0)
    , odomC_pitch(0.0)
    , odomC_yaw(0.0)
    , ge_angle_roll(0.0)
    , ge_angle_pitch(0.0)
    , ge_angle_yaw(0.0)
    , imu_a_x(0.0)
    , imu_a_y(0.0)
    , imu_a_z(0.0)
    , imu_a_fil_x(0.0)
    , imu_a_fil_y(0.0)
    , imu_a_fil_z(0.0)
    , imu_w_x(0.0)
    , imu_w_y(0.0)
    , imu_w_z(0.0)
    , imu_w_fil_x(0.0)
    , imu_w_fil_y(0.0)
    , imu_w_fil_z(0.0)
    , imu_w_c_x(0.0)
    , imu_w_c_y(0.0)
    , imu_w_c_z(0.0)
    , imu_beta_fil_x(0.0)
    , imu_beta_fil_y(0.0)
    , imu_beta_fil_z(0.0)
    , rpm1(0.0)
    , rpm2(0.0)
    , rpm3(0.0)
    , rpm4(0.0)
    , rpm1_fil(0.0)
    , rpm2_fil(0.0)
    , rpm3_fil(0.0)
    , rpm4_fil(0.0)
    , sumrpm2(0.0)
    , thrust_force(0.0)
    , thrust_acc(0.0)
    , sumrpm2_fil(0.0)
    , thrust_force_fil(0.0)
    , thrust_acc_fil(0.0)
    , acc_world_x(0.0)
    , acc_world_y(0.0)
    , acc_world_z(0.0)
    , ge_acc_x(0.0)
    , ge_acc_y(0.0)
    , ge_acc_z(0.0)
    , ge_bodytorque_x(0.0)
    , ge_bodytorque_y(0.0)
    , ge_bodytorque_z(0.0)
    , des_ge_bodytorque_x(0.0)
    , des_ge_bodytorque_y(0.0)
    , des_ge_bodytorque_z(0.0)
    , d_ge_torque_x(0.0)
    , d_ge_torque_y(0.0)
    , d_ge_torque_z(0.0)
    , diff_ge_torque_x(0.0)
    , diff_ge_torque_y(0.0)
    , diff_ge_torque_z(0.0)
    , ext_torque_x(0.0)
    , ext_torque_y(0.0)
    , ext_torque_z(0.0)
    , predict_ext_torque_x(0.0)
    , predict_ext_torque_y(0.0)
    , predict_ext_torque_z(0.0)
    , des_p_x(0.0)
    , des_p_y(0.0)
    , des_p_z(0.0)
    , des_v_x(0.0)
    , des_v_y(0.0)
    , des_v_z(0.0)
    , des_a_x(0.0)
    , des_a_y(0.0)
    , des_a_z(0.0)
    , des_j_x(0.0)
    , des_j_y(0.0)
    , des_j_z(0.0)
    , des_s_x(0.0)
    , des_s_y(0.0)
    , des_s_z(0.0)
    , des_yaw(0.0)
    , des_yaw_rate(0.0)
    , des_yaw_acc(0.0)
    , flatctrl_q_w(0.0)
    , flatctrl_q_x(0.0)
    , flatctrl_q_y(0.0)
    , flatctrl_q_z(0.0)
    , flatctrl_roll(0.0)
    , flatctrl_pitch(0.0)
    , flatctrl_yaw(0.0)
    , flatctrl_bodyrate_x(0.0)
    , flatctrl_bodyrate_y(0.0)
    , flatctrl_bodyrate_z(0.0)
    , flatctrl_beta_x(0.0)
    , flatctrl_beta_y(0.0)
    , flatctrl_beta_z(0.0)
    , flatctrl_thrust(0.0)
    , flatctrl_torque_x(0.0)
    , flatctrl_torque_y(0.0)
    , flatctrl_torque_z(0.0)
    , flatctrl_ge_acc_x(0.0)
    , flatctrl_ge_acc_y(0.0)
    , flatctrl_ge_acc_z(0.0)
    , flatctrl_drag_acc_x(0.0)
    , flatctrl_drag_acc_y(0.0)
    , flatctrl_drag_acc_z(0.0)
    , flatctrl_ext_acc_x(0.0)
    , flatctrl_ext_acc_y(0.0)
    , flatctrl_ext_acc_z(0.0)
    , ge_limit_k(0.0)
    , fb_vel_x(0.0)
    , fb_vel_y(0.0)
    , fb_vel_z(0.0)
    , cmd_vel_x(0.0)
    , cmd_vel_y(0.0)
    , cmd_vel_z(0.0)
    , compensate_acc_x(0.0)
    , compensate_acc_y(0.0)
    , compensate_acc_z(0.0)
    , fb_acc_x(0.0)
    , fb_acc_y(0.0)
    , fb_acc_z(0.0)
    , cmd_acc_x(0.0)
    , cmd_acc_y(0.0)
    , cmd_acc_z(0.0)
    , cmd_acc_norm(0.0)
    , cmd_acc_norm_by_body(0.0)
    , cmd_q_w(0.0)
    , cmd_q_x(0.0)
    , cmd_q_y(0.0)
    , cmd_q_z(0.0)
    , cmd_roll(0.0)
    , cmd_pitch(0.0)
    , cmd_yaw(0.0)
    , fb_bodyrate_x(0.0)
    , fb_bodyrate_y(0.0)
    , fb_bodyrate_z(0.0)
    , cmd_bodyrate_x(0.0)
    , cmd_bodyrate_y(0.0)
    , cmd_bodyrate_z(0.0)
    , fb_beta_x(0.0)
    , fb_beta_y(0.0)
    , fb_beta_z(0.0)
    , cmd_beta_x(0.0)
    , cmd_beta_y(0.0)
    , cmd_beta_z(0.0)
    , compensate_torque_x(0.0)
    , compensate_torque_y(0.0)
    , compensate_torque_z(0.0)
    , bodytorque_x(0.0)
    , bodytorque_y(0.0)
    , bodytorque_z(0.0)
    , cmd_torque_body_x(0.0)
    , cmd_torque_body_y(0.0)
    , cmd_torque_body_z(0.0)
    , diff_indi_torque_x(0.0)
    , diff_indi_torque_y(0.0)
    , diff_indi_torque_z(0.0)
    , diff_torque_x(0.0)
    , diff_torque_y(0.0)
    , diff_torque_z(0.0)
    , cmd_rpm1(0.0)
    , cmd_rpm2(0.0)
    , cmd_rpm3(0.0)
    , cmd_rpm4(0.0)
    , cmd_sumrpm2(0.0)
    , cmd_sumrpm2_to_acc(0.0)
    , fb_thrust1(0.0)
    , fb_thrust2(0.0)
    , fb_thrust3(0.0)
    , fb_thrust4(0.0)
    , ref_thrust1(0.0)
    , ref_thrust2(0.0)
    , ref_thrust3(0.0)
    , ref_thrust4(0.0)
    , cmd_thrust1(0.0)
    , cmd_thrust2(0.0)
    , cmd_thrust3(0.0)
    , cmd_thrust4(0.0)
    , Fgh(0.0)
    , ref_thrust_acc(0.0)
    , thrust_acc_fil_x(0.0)
    , thrust_acc_fil_y(0.0)
    , thrust_acc_fil_z(0.0)
    , imu_acc_fil_x(0.0)
    , imu_acc_fil_y(0.0)
    , imu_acc_fil_z(0.0)
    , extforce_acc_x(0.0)
    , extforce_acc_y(0.0)
    , extforce_acc_z(0.0)
    , extforce_acc_fil_x(0.0)
    , extforce_acc_fil_y(0.0)
    , extforce_acc_fil_z(0.0)
    , poly_thrust(0.0)
    , fb_thrust(0.0)
    , sum_thrust(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _odom_roll_type;
  _odom_roll_type odom_roll;

   typedef double _odom_pitch_type;
  _odom_pitch_type odom_pitch;

   typedef double _odom_yaw_type;
  _odom_yaw_type odom_yaw;

   typedef double _odomC_roll_type;
  _odomC_roll_type odomC_roll;

   typedef double _odomC_pitch_type;
  _odomC_pitch_type odomC_pitch;

   typedef double _odomC_yaw_type;
  _odomC_yaw_type odomC_yaw;

   typedef double _ge_angle_roll_type;
  _ge_angle_roll_type ge_angle_roll;

   typedef double _ge_angle_pitch_type;
  _ge_angle_pitch_type ge_angle_pitch;

   typedef double _ge_angle_yaw_type;
  _ge_angle_yaw_type ge_angle_yaw;

   typedef double _imu_a_x_type;
  _imu_a_x_type imu_a_x;

   typedef double _imu_a_y_type;
  _imu_a_y_type imu_a_y;

   typedef double _imu_a_z_type;
  _imu_a_z_type imu_a_z;

   typedef double _imu_a_fil_x_type;
  _imu_a_fil_x_type imu_a_fil_x;

   typedef double _imu_a_fil_y_type;
  _imu_a_fil_y_type imu_a_fil_y;

   typedef double _imu_a_fil_z_type;
  _imu_a_fil_z_type imu_a_fil_z;

   typedef double _imu_w_x_type;
  _imu_w_x_type imu_w_x;

   typedef double _imu_w_y_type;
  _imu_w_y_type imu_w_y;

   typedef double _imu_w_z_type;
  _imu_w_z_type imu_w_z;

   typedef double _imu_w_fil_x_type;
  _imu_w_fil_x_type imu_w_fil_x;

   typedef double _imu_w_fil_y_type;
  _imu_w_fil_y_type imu_w_fil_y;

   typedef double _imu_w_fil_z_type;
  _imu_w_fil_z_type imu_w_fil_z;

   typedef double _imu_w_c_x_type;
  _imu_w_c_x_type imu_w_c_x;

   typedef double _imu_w_c_y_type;
  _imu_w_c_y_type imu_w_c_y;

   typedef double _imu_w_c_z_type;
  _imu_w_c_z_type imu_w_c_z;

   typedef double _imu_beta_fil_x_type;
  _imu_beta_fil_x_type imu_beta_fil_x;

   typedef double _imu_beta_fil_y_type;
  _imu_beta_fil_y_type imu_beta_fil_y;

   typedef double _imu_beta_fil_z_type;
  _imu_beta_fil_z_type imu_beta_fil_z;

   typedef double _rpm1_type;
  _rpm1_type rpm1;

   typedef double _rpm2_type;
  _rpm2_type rpm2;

   typedef double _rpm3_type;
  _rpm3_type rpm3;

   typedef double _rpm4_type;
  _rpm4_type rpm4;

   typedef double _rpm1_fil_type;
  _rpm1_fil_type rpm1_fil;

   typedef double _rpm2_fil_type;
  _rpm2_fil_type rpm2_fil;

   typedef double _rpm3_fil_type;
  _rpm3_fil_type rpm3_fil;

   typedef double _rpm4_fil_type;
  _rpm4_fil_type rpm4_fil;

   typedef double _sumrpm2_type;
  _sumrpm2_type sumrpm2;

   typedef double _thrust_force_type;
  _thrust_force_type thrust_force;

   typedef double _thrust_acc_type;
  _thrust_acc_type thrust_acc;

   typedef double _sumrpm2_fil_type;
  _sumrpm2_fil_type sumrpm2_fil;

   typedef double _thrust_force_fil_type;
  _thrust_force_fil_type thrust_force_fil;

   typedef double _thrust_acc_fil_type;
  _thrust_acc_fil_type thrust_acc_fil;

   typedef double _acc_world_x_type;
  _acc_world_x_type acc_world_x;

   typedef double _acc_world_y_type;
  _acc_world_y_type acc_world_y;

   typedef double _acc_world_z_type;
  _acc_world_z_type acc_world_z;

   typedef double _ge_acc_x_type;
  _ge_acc_x_type ge_acc_x;

   typedef double _ge_acc_y_type;
  _ge_acc_y_type ge_acc_y;

   typedef double _ge_acc_z_type;
  _ge_acc_z_type ge_acc_z;

   typedef double _ge_bodytorque_x_type;
  _ge_bodytorque_x_type ge_bodytorque_x;

   typedef double _ge_bodytorque_y_type;
  _ge_bodytorque_y_type ge_bodytorque_y;

   typedef double _ge_bodytorque_z_type;
  _ge_bodytorque_z_type ge_bodytorque_z;

   typedef double _des_ge_bodytorque_x_type;
  _des_ge_bodytorque_x_type des_ge_bodytorque_x;

   typedef double _des_ge_bodytorque_y_type;
  _des_ge_bodytorque_y_type des_ge_bodytorque_y;

   typedef double _des_ge_bodytorque_z_type;
  _des_ge_bodytorque_z_type des_ge_bodytorque_z;

   typedef double _d_ge_torque_x_type;
  _d_ge_torque_x_type d_ge_torque_x;

   typedef double _d_ge_torque_y_type;
  _d_ge_torque_y_type d_ge_torque_y;

   typedef double _d_ge_torque_z_type;
  _d_ge_torque_z_type d_ge_torque_z;

   typedef double _diff_ge_torque_x_type;
  _diff_ge_torque_x_type diff_ge_torque_x;

   typedef double _diff_ge_torque_y_type;
  _diff_ge_torque_y_type diff_ge_torque_y;

   typedef double _diff_ge_torque_z_type;
  _diff_ge_torque_z_type diff_ge_torque_z;

   typedef double _ext_torque_x_type;
  _ext_torque_x_type ext_torque_x;

   typedef double _ext_torque_y_type;
  _ext_torque_y_type ext_torque_y;

   typedef double _ext_torque_z_type;
  _ext_torque_z_type ext_torque_z;

   typedef double _predict_ext_torque_x_type;
  _predict_ext_torque_x_type predict_ext_torque_x;

   typedef double _predict_ext_torque_y_type;
  _predict_ext_torque_y_type predict_ext_torque_y;

   typedef double _predict_ext_torque_z_type;
  _predict_ext_torque_z_type predict_ext_torque_z;

   typedef double _des_p_x_type;
  _des_p_x_type des_p_x;

   typedef double _des_p_y_type;
  _des_p_y_type des_p_y;

   typedef double _des_p_z_type;
  _des_p_z_type des_p_z;

   typedef double _des_v_x_type;
  _des_v_x_type des_v_x;

   typedef double _des_v_y_type;
  _des_v_y_type des_v_y;

   typedef double _des_v_z_type;
  _des_v_z_type des_v_z;

   typedef double _des_a_x_type;
  _des_a_x_type des_a_x;

   typedef double _des_a_y_type;
  _des_a_y_type des_a_y;

   typedef double _des_a_z_type;
  _des_a_z_type des_a_z;

   typedef double _des_j_x_type;
  _des_j_x_type des_j_x;

   typedef double _des_j_y_type;
  _des_j_y_type des_j_y;

   typedef double _des_j_z_type;
  _des_j_z_type des_j_z;

   typedef double _des_s_x_type;
  _des_s_x_type des_s_x;

   typedef double _des_s_y_type;
  _des_s_y_type des_s_y;

   typedef double _des_s_z_type;
  _des_s_z_type des_s_z;

   typedef double _des_yaw_type;
  _des_yaw_type des_yaw;

   typedef double _des_yaw_rate_type;
  _des_yaw_rate_type des_yaw_rate;

   typedef double _des_yaw_acc_type;
  _des_yaw_acc_type des_yaw_acc;

   typedef double _flatctrl_q_w_type;
  _flatctrl_q_w_type flatctrl_q_w;

   typedef double _flatctrl_q_x_type;
  _flatctrl_q_x_type flatctrl_q_x;

   typedef double _flatctrl_q_y_type;
  _flatctrl_q_y_type flatctrl_q_y;

   typedef double _flatctrl_q_z_type;
  _flatctrl_q_z_type flatctrl_q_z;

   typedef double _flatctrl_roll_type;
  _flatctrl_roll_type flatctrl_roll;

   typedef double _flatctrl_pitch_type;
  _flatctrl_pitch_type flatctrl_pitch;

   typedef double _flatctrl_yaw_type;
  _flatctrl_yaw_type flatctrl_yaw;

   typedef double _flatctrl_bodyrate_x_type;
  _flatctrl_bodyrate_x_type flatctrl_bodyrate_x;

   typedef double _flatctrl_bodyrate_y_type;
  _flatctrl_bodyrate_y_type flatctrl_bodyrate_y;

   typedef double _flatctrl_bodyrate_z_type;
  _flatctrl_bodyrate_z_type flatctrl_bodyrate_z;

   typedef double _flatctrl_beta_x_type;
  _flatctrl_beta_x_type flatctrl_beta_x;

   typedef double _flatctrl_beta_y_type;
  _flatctrl_beta_y_type flatctrl_beta_y;

   typedef double _flatctrl_beta_z_type;
  _flatctrl_beta_z_type flatctrl_beta_z;

   typedef double _flatctrl_thrust_type;
  _flatctrl_thrust_type flatctrl_thrust;

   typedef double _flatctrl_torque_x_type;
  _flatctrl_torque_x_type flatctrl_torque_x;

   typedef double _flatctrl_torque_y_type;
  _flatctrl_torque_y_type flatctrl_torque_y;

   typedef double _flatctrl_torque_z_type;
  _flatctrl_torque_z_type flatctrl_torque_z;

   typedef double _flatctrl_ge_acc_x_type;
  _flatctrl_ge_acc_x_type flatctrl_ge_acc_x;

   typedef double _flatctrl_ge_acc_y_type;
  _flatctrl_ge_acc_y_type flatctrl_ge_acc_y;

   typedef double _flatctrl_ge_acc_z_type;
  _flatctrl_ge_acc_z_type flatctrl_ge_acc_z;

   typedef double _flatctrl_drag_acc_x_type;
  _flatctrl_drag_acc_x_type flatctrl_drag_acc_x;

   typedef double _flatctrl_drag_acc_y_type;
  _flatctrl_drag_acc_y_type flatctrl_drag_acc_y;

   typedef double _flatctrl_drag_acc_z_type;
  _flatctrl_drag_acc_z_type flatctrl_drag_acc_z;

   typedef double _flatctrl_ext_acc_x_type;
  _flatctrl_ext_acc_x_type flatctrl_ext_acc_x;

   typedef double _flatctrl_ext_acc_y_type;
  _flatctrl_ext_acc_y_type flatctrl_ext_acc_y;

   typedef double _flatctrl_ext_acc_z_type;
  _flatctrl_ext_acc_z_type flatctrl_ext_acc_z;

   typedef double _ge_limit_k_type;
  _ge_limit_k_type ge_limit_k;

   typedef double _fb_vel_x_type;
  _fb_vel_x_type fb_vel_x;

   typedef double _fb_vel_y_type;
  _fb_vel_y_type fb_vel_y;

   typedef double _fb_vel_z_type;
  _fb_vel_z_type fb_vel_z;

   typedef double _cmd_vel_x_type;
  _cmd_vel_x_type cmd_vel_x;

   typedef double _cmd_vel_y_type;
  _cmd_vel_y_type cmd_vel_y;

   typedef double _cmd_vel_z_type;
  _cmd_vel_z_type cmd_vel_z;

   typedef double _compensate_acc_x_type;
  _compensate_acc_x_type compensate_acc_x;

   typedef double _compensate_acc_y_type;
  _compensate_acc_y_type compensate_acc_y;

   typedef double _compensate_acc_z_type;
  _compensate_acc_z_type compensate_acc_z;

   typedef double _fb_acc_x_type;
  _fb_acc_x_type fb_acc_x;

   typedef double _fb_acc_y_type;
  _fb_acc_y_type fb_acc_y;

   typedef double _fb_acc_z_type;
  _fb_acc_z_type fb_acc_z;

   typedef double _cmd_acc_x_type;
  _cmd_acc_x_type cmd_acc_x;

   typedef double _cmd_acc_y_type;
  _cmd_acc_y_type cmd_acc_y;

   typedef double _cmd_acc_z_type;
  _cmd_acc_z_type cmd_acc_z;

   typedef double _cmd_acc_norm_type;
  _cmd_acc_norm_type cmd_acc_norm;

   typedef double _cmd_acc_norm_by_body_type;
  _cmd_acc_norm_by_body_type cmd_acc_norm_by_body;

   typedef double _cmd_q_w_type;
  _cmd_q_w_type cmd_q_w;

   typedef double _cmd_q_x_type;
  _cmd_q_x_type cmd_q_x;

   typedef double _cmd_q_y_type;
  _cmd_q_y_type cmd_q_y;

   typedef double _cmd_q_z_type;
  _cmd_q_z_type cmd_q_z;

   typedef double _cmd_roll_type;
  _cmd_roll_type cmd_roll;

   typedef double _cmd_pitch_type;
  _cmd_pitch_type cmd_pitch;

   typedef double _cmd_yaw_type;
  _cmd_yaw_type cmd_yaw;

   typedef double _fb_bodyrate_x_type;
  _fb_bodyrate_x_type fb_bodyrate_x;

   typedef double _fb_bodyrate_y_type;
  _fb_bodyrate_y_type fb_bodyrate_y;

   typedef double _fb_bodyrate_z_type;
  _fb_bodyrate_z_type fb_bodyrate_z;

   typedef double _cmd_bodyrate_x_type;
  _cmd_bodyrate_x_type cmd_bodyrate_x;

   typedef double _cmd_bodyrate_y_type;
  _cmd_bodyrate_y_type cmd_bodyrate_y;

   typedef double _cmd_bodyrate_z_type;
  _cmd_bodyrate_z_type cmd_bodyrate_z;

   typedef double _fb_beta_x_type;
  _fb_beta_x_type fb_beta_x;

   typedef double _fb_beta_y_type;
  _fb_beta_y_type fb_beta_y;

   typedef double _fb_beta_z_type;
  _fb_beta_z_type fb_beta_z;

   typedef double _cmd_beta_x_type;
  _cmd_beta_x_type cmd_beta_x;

   typedef double _cmd_beta_y_type;
  _cmd_beta_y_type cmd_beta_y;

   typedef double _cmd_beta_z_type;
  _cmd_beta_z_type cmd_beta_z;

   typedef double _compensate_torque_x_type;
  _compensate_torque_x_type compensate_torque_x;

   typedef double _compensate_torque_y_type;
  _compensate_torque_y_type compensate_torque_y;

   typedef double _compensate_torque_z_type;
  _compensate_torque_z_type compensate_torque_z;

   typedef double _bodytorque_x_type;
  _bodytorque_x_type bodytorque_x;

   typedef double _bodytorque_y_type;
  _bodytorque_y_type bodytorque_y;

   typedef double _bodytorque_z_type;
  _bodytorque_z_type bodytorque_z;

   typedef double _cmd_torque_body_x_type;
  _cmd_torque_body_x_type cmd_torque_body_x;

   typedef double _cmd_torque_body_y_type;
  _cmd_torque_body_y_type cmd_torque_body_y;

   typedef double _cmd_torque_body_z_type;
  _cmd_torque_body_z_type cmd_torque_body_z;

   typedef double _diff_indi_torque_x_type;
  _diff_indi_torque_x_type diff_indi_torque_x;

   typedef double _diff_indi_torque_y_type;
  _diff_indi_torque_y_type diff_indi_torque_y;

   typedef double _diff_indi_torque_z_type;
  _diff_indi_torque_z_type diff_indi_torque_z;

   typedef double _diff_torque_x_type;
  _diff_torque_x_type diff_torque_x;

   typedef double _diff_torque_y_type;
  _diff_torque_y_type diff_torque_y;

   typedef double _diff_torque_z_type;
  _diff_torque_z_type diff_torque_z;

   typedef double _cmd_rpm1_type;
  _cmd_rpm1_type cmd_rpm1;

   typedef double _cmd_rpm2_type;
  _cmd_rpm2_type cmd_rpm2;

   typedef double _cmd_rpm3_type;
  _cmd_rpm3_type cmd_rpm3;

   typedef double _cmd_rpm4_type;
  _cmd_rpm4_type cmd_rpm4;

   typedef double _cmd_sumrpm2_type;
  _cmd_sumrpm2_type cmd_sumrpm2;

   typedef double _cmd_sumrpm2_to_acc_type;
  _cmd_sumrpm2_to_acc_type cmd_sumrpm2_to_acc;

   typedef double _fb_thrust1_type;
  _fb_thrust1_type fb_thrust1;

   typedef double _fb_thrust2_type;
  _fb_thrust2_type fb_thrust2;

   typedef double _fb_thrust3_type;
  _fb_thrust3_type fb_thrust3;

   typedef double _fb_thrust4_type;
  _fb_thrust4_type fb_thrust4;

   typedef double _ref_thrust1_type;
  _ref_thrust1_type ref_thrust1;

   typedef double _ref_thrust2_type;
  _ref_thrust2_type ref_thrust2;

   typedef double _ref_thrust3_type;
  _ref_thrust3_type ref_thrust3;

   typedef double _ref_thrust4_type;
  _ref_thrust4_type ref_thrust4;

   typedef double _cmd_thrust1_type;
  _cmd_thrust1_type cmd_thrust1;

   typedef double _cmd_thrust2_type;
  _cmd_thrust2_type cmd_thrust2;

   typedef double _cmd_thrust3_type;
  _cmd_thrust3_type cmd_thrust3;

   typedef double _cmd_thrust4_type;
  _cmd_thrust4_type cmd_thrust4;

   typedef double _Fgh_type;
  _Fgh_type Fgh;

   typedef double _ref_thrust_acc_type;
  _ref_thrust_acc_type ref_thrust_acc;

   typedef double _thrust_acc_fil_x_type;
  _thrust_acc_fil_x_type thrust_acc_fil_x;

   typedef double _thrust_acc_fil_y_type;
  _thrust_acc_fil_y_type thrust_acc_fil_y;

   typedef double _thrust_acc_fil_z_type;
  _thrust_acc_fil_z_type thrust_acc_fil_z;

   typedef double _imu_acc_fil_x_type;
  _imu_acc_fil_x_type imu_acc_fil_x;

   typedef double _imu_acc_fil_y_type;
  _imu_acc_fil_y_type imu_acc_fil_y;

   typedef double _imu_acc_fil_z_type;
  _imu_acc_fil_z_type imu_acc_fil_z;

   typedef double _extforce_acc_x_type;
  _extforce_acc_x_type extforce_acc_x;

   typedef double _extforce_acc_y_type;
  _extforce_acc_y_type extforce_acc_y;

   typedef double _extforce_acc_z_type;
  _extforce_acc_z_type extforce_acc_z;

   typedef double _extforce_acc_fil_x_type;
  _extforce_acc_fil_x_type extforce_acc_fil_x;

   typedef double _extforce_acc_fil_y_type;
  _extforce_acc_fil_y_type extforce_acc_fil_y;

   typedef double _extforce_acc_fil_z_type;
  _extforce_acc_fil_z_type extforce_acc_fil_z;

   typedef double _poly_thrust_type;
  _poly_thrust_type poly_thrust;

   typedef double _fb_thrust_type;
  _fb_thrust_type fb_thrust;

   typedef double _sum_thrust_type;
  _sum_thrust_type sum_thrust;





  typedef boost::shared_ptr< ::quadrotor_msgs::geDebug_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotor_msgs::geDebug_<ContainerAllocator> const> ConstPtr;

}; // struct geDebug_

typedef ::quadrotor_msgs::geDebug_<std::allocator<void> > geDebug;

typedef boost::shared_ptr< ::quadrotor_msgs::geDebug > geDebugPtr;
typedef boost::shared_ptr< ::quadrotor_msgs::geDebug const> geDebugConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quadrotor_msgs::geDebug_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quadrotor_msgs::geDebug_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quadrotor_msgs::geDebug_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::geDebug_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.odom_roll == rhs.odom_roll &&
    lhs.odom_pitch == rhs.odom_pitch &&
    lhs.odom_yaw == rhs.odom_yaw &&
    lhs.odomC_roll == rhs.odomC_roll &&
    lhs.odomC_pitch == rhs.odomC_pitch &&
    lhs.odomC_yaw == rhs.odomC_yaw &&
    lhs.ge_angle_roll == rhs.ge_angle_roll &&
    lhs.ge_angle_pitch == rhs.ge_angle_pitch &&
    lhs.ge_angle_yaw == rhs.ge_angle_yaw &&
    lhs.imu_a_x == rhs.imu_a_x &&
    lhs.imu_a_y == rhs.imu_a_y &&
    lhs.imu_a_z == rhs.imu_a_z &&
    lhs.imu_a_fil_x == rhs.imu_a_fil_x &&
    lhs.imu_a_fil_y == rhs.imu_a_fil_y &&
    lhs.imu_a_fil_z == rhs.imu_a_fil_z &&
    lhs.imu_w_x == rhs.imu_w_x &&
    lhs.imu_w_y == rhs.imu_w_y &&
    lhs.imu_w_z == rhs.imu_w_z &&
    lhs.imu_w_fil_x == rhs.imu_w_fil_x &&
    lhs.imu_w_fil_y == rhs.imu_w_fil_y &&
    lhs.imu_w_fil_z == rhs.imu_w_fil_z &&
    lhs.imu_w_c_x == rhs.imu_w_c_x &&
    lhs.imu_w_c_y == rhs.imu_w_c_y &&
    lhs.imu_w_c_z == rhs.imu_w_c_z &&
    lhs.imu_beta_fil_x == rhs.imu_beta_fil_x &&
    lhs.imu_beta_fil_y == rhs.imu_beta_fil_y &&
    lhs.imu_beta_fil_z == rhs.imu_beta_fil_z &&
    lhs.rpm1 == rhs.rpm1 &&
    lhs.rpm2 == rhs.rpm2 &&
    lhs.rpm3 == rhs.rpm3 &&
    lhs.rpm4 == rhs.rpm4 &&
    lhs.rpm1_fil == rhs.rpm1_fil &&
    lhs.rpm2_fil == rhs.rpm2_fil &&
    lhs.rpm3_fil == rhs.rpm3_fil &&
    lhs.rpm4_fil == rhs.rpm4_fil &&
    lhs.sumrpm2 == rhs.sumrpm2 &&
    lhs.thrust_force == rhs.thrust_force &&
    lhs.thrust_acc == rhs.thrust_acc &&
    lhs.sumrpm2_fil == rhs.sumrpm2_fil &&
    lhs.thrust_force_fil == rhs.thrust_force_fil &&
    lhs.thrust_acc_fil == rhs.thrust_acc_fil &&
    lhs.acc_world_x == rhs.acc_world_x &&
    lhs.acc_world_y == rhs.acc_world_y &&
    lhs.acc_world_z == rhs.acc_world_z &&
    lhs.ge_acc_x == rhs.ge_acc_x &&
    lhs.ge_acc_y == rhs.ge_acc_y &&
    lhs.ge_acc_z == rhs.ge_acc_z &&
    lhs.ge_bodytorque_x == rhs.ge_bodytorque_x &&
    lhs.ge_bodytorque_y == rhs.ge_bodytorque_y &&
    lhs.ge_bodytorque_z == rhs.ge_bodytorque_z &&
    lhs.des_ge_bodytorque_x == rhs.des_ge_bodytorque_x &&
    lhs.des_ge_bodytorque_y == rhs.des_ge_bodytorque_y &&
    lhs.des_ge_bodytorque_z == rhs.des_ge_bodytorque_z &&
    lhs.d_ge_torque_x == rhs.d_ge_torque_x &&
    lhs.d_ge_torque_y == rhs.d_ge_torque_y &&
    lhs.d_ge_torque_z == rhs.d_ge_torque_z &&
    lhs.diff_ge_torque_x == rhs.diff_ge_torque_x &&
    lhs.diff_ge_torque_y == rhs.diff_ge_torque_y &&
    lhs.diff_ge_torque_z == rhs.diff_ge_torque_z &&
    lhs.ext_torque_x == rhs.ext_torque_x &&
    lhs.ext_torque_y == rhs.ext_torque_y &&
    lhs.ext_torque_z == rhs.ext_torque_z &&
    lhs.predict_ext_torque_x == rhs.predict_ext_torque_x &&
    lhs.predict_ext_torque_y == rhs.predict_ext_torque_y &&
    lhs.predict_ext_torque_z == rhs.predict_ext_torque_z &&
    lhs.des_p_x == rhs.des_p_x &&
    lhs.des_p_y == rhs.des_p_y &&
    lhs.des_p_z == rhs.des_p_z &&
    lhs.des_v_x == rhs.des_v_x &&
    lhs.des_v_y == rhs.des_v_y &&
    lhs.des_v_z == rhs.des_v_z &&
    lhs.des_a_x == rhs.des_a_x &&
    lhs.des_a_y == rhs.des_a_y &&
    lhs.des_a_z == rhs.des_a_z &&
    lhs.des_j_x == rhs.des_j_x &&
    lhs.des_j_y == rhs.des_j_y &&
    lhs.des_j_z == rhs.des_j_z &&
    lhs.des_s_x == rhs.des_s_x &&
    lhs.des_s_y == rhs.des_s_y &&
    lhs.des_s_z == rhs.des_s_z &&
    lhs.des_yaw == rhs.des_yaw &&
    lhs.des_yaw_rate == rhs.des_yaw_rate &&
    lhs.des_yaw_acc == rhs.des_yaw_acc &&
    lhs.flatctrl_q_w == rhs.flatctrl_q_w &&
    lhs.flatctrl_q_x == rhs.flatctrl_q_x &&
    lhs.flatctrl_q_y == rhs.flatctrl_q_y &&
    lhs.flatctrl_q_z == rhs.flatctrl_q_z &&
    lhs.flatctrl_roll == rhs.flatctrl_roll &&
    lhs.flatctrl_pitch == rhs.flatctrl_pitch &&
    lhs.flatctrl_yaw == rhs.flatctrl_yaw &&
    lhs.flatctrl_bodyrate_x == rhs.flatctrl_bodyrate_x &&
    lhs.flatctrl_bodyrate_y == rhs.flatctrl_bodyrate_y &&
    lhs.flatctrl_bodyrate_z == rhs.flatctrl_bodyrate_z &&
    lhs.flatctrl_beta_x == rhs.flatctrl_beta_x &&
    lhs.flatctrl_beta_y == rhs.flatctrl_beta_y &&
    lhs.flatctrl_beta_z == rhs.flatctrl_beta_z &&
    lhs.flatctrl_thrust == rhs.flatctrl_thrust &&
    lhs.flatctrl_torque_x == rhs.flatctrl_torque_x &&
    lhs.flatctrl_torque_y == rhs.flatctrl_torque_y &&
    lhs.flatctrl_torque_z == rhs.flatctrl_torque_z &&
    lhs.flatctrl_ge_acc_x == rhs.flatctrl_ge_acc_x &&
    lhs.flatctrl_ge_acc_y == rhs.flatctrl_ge_acc_y &&
    lhs.flatctrl_ge_acc_z == rhs.flatctrl_ge_acc_z &&
    lhs.flatctrl_drag_acc_x == rhs.flatctrl_drag_acc_x &&
    lhs.flatctrl_drag_acc_y == rhs.flatctrl_drag_acc_y &&
    lhs.flatctrl_drag_acc_z == rhs.flatctrl_drag_acc_z &&
    lhs.flatctrl_ext_acc_x == rhs.flatctrl_ext_acc_x &&
    lhs.flatctrl_ext_acc_y == rhs.flatctrl_ext_acc_y &&
    lhs.flatctrl_ext_acc_z == rhs.flatctrl_ext_acc_z &&
    lhs.ge_limit_k == rhs.ge_limit_k &&
    lhs.fb_vel_x == rhs.fb_vel_x &&
    lhs.fb_vel_y == rhs.fb_vel_y &&
    lhs.fb_vel_z == rhs.fb_vel_z &&
    lhs.cmd_vel_x == rhs.cmd_vel_x &&
    lhs.cmd_vel_y == rhs.cmd_vel_y &&
    lhs.cmd_vel_z == rhs.cmd_vel_z &&
    lhs.compensate_acc_x == rhs.compensate_acc_x &&
    lhs.compensate_acc_y == rhs.compensate_acc_y &&
    lhs.compensate_acc_z == rhs.compensate_acc_z &&
    lhs.fb_acc_x == rhs.fb_acc_x &&
    lhs.fb_acc_y == rhs.fb_acc_y &&
    lhs.fb_acc_z == rhs.fb_acc_z &&
    lhs.cmd_acc_x == rhs.cmd_acc_x &&
    lhs.cmd_acc_y == rhs.cmd_acc_y &&
    lhs.cmd_acc_z == rhs.cmd_acc_z &&
    lhs.cmd_acc_norm == rhs.cmd_acc_norm &&
    lhs.cmd_acc_norm_by_body == rhs.cmd_acc_norm_by_body &&
    lhs.cmd_q_w == rhs.cmd_q_w &&
    lhs.cmd_q_x == rhs.cmd_q_x &&
    lhs.cmd_q_y == rhs.cmd_q_y &&
    lhs.cmd_q_z == rhs.cmd_q_z &&
    lhs.cmd_roll == rhs.cmd_roll &&
    lhs.cmd_pitch == rhs.cmd_pitch &&
    lhs.cmd_yaw == rhs.cmd_yaw &&
    lhs.fb_bodyrate_x == rhs.fb_bodyrate_x &&
    lhs.fb_bodyrate_y == rhs.fb_bodyrate_y &&
    lhs.fb_bodyrate_z == rhs.fb_bodyrate_z &&
    lhs.cmd_bodyrate_x == rhs.cmd_bodyrate_x &&
    lhs.cmd_bodyrate_y == rhs.cmd_bodyrate_y &&
    lhs.cmd_bodyrate_z == rhs.cmd_bodyrate_z &&
    lhs.fb_beta_x == rhs.fb_beta_x &&
    lhs.fb_beta_y == rhs.fb_beta_y &&
    lhs.fb_beta_z == rhs.fb_beta_z &&
    lhs.cmd_beta_x == rhs.cmd_beta_x &&
    lhs.cmd_beta_y == rhs.cmd_beta_y &&
    lhs.cmd_beta_z == rhs.cmd_beta_z &&
    lhs.compensate_torque_x == rhs.compensate_torque_x &&
    lhs.compensate_torque_y == rhs.compensate_torque_y &&
    lhs.compensate_torque_z == rhs.compensate_torque_z &&
    lhs.bodytorque_x == rhs.bodytorque_x &&
    lhs.bodytorque_y == rhs.bodytorque_y &&
    lhs.bodytorque_z == rhs.bodytorque_z &&
    lhs.cmd_torque_body_x == rhs.cmd_torque_body_x &&
    lhs.cmd_torque_body_y == rhs.cmd_torque_body_y &&
    lhs.cmd_torque_body_z == rhs.cmd_torque_body_z &&
    lhs.diff_indi_torque_x == rhs.diff_indi_torque_x &&
    lhs.diff_indi_torque_y == rhs.diff_indi_torque_y &&
    lhs.diff_indi_torque_z == rhs.diff_indi_torque_z &&
    lhs.diff_torque_x == rhs.diff_torque_x &&
    lhs.diff_torque_y == rhs.diff_torque_y &&
    lhs.diff_torque_z == rhs.diff_torque_z &&
    lhs.cmd_rpm1 == rhs.cmd_rpm1 &&
    lhs.cmd_rpm2 == rhs.cmd_rpm2 &&
    lhs.cmd_rpm3 == rhs.cmd_rpm3 &&
    lhs.cmd_rpm4 == rhs.cmd_rpm4 &&
    lhs.cmd_sumrpm2 == rhs.cmd_sumrpm2 &&
    lhs.cmd_sumrpm2_to_acc == rhs.cmd_sumrpm2_to_acc &&
    lhs.fb_thrust1 == rhs.fb_thrust1 &&
    lhs.fb_thrust2 == rhs.fb_thrust2 &&
    lhs.fb_thrust3 == rhs.fb_thrust3 &&
    lhs.fb_thrust4 == rhs.fb_thrust4 &&
    lhs.ref_thrust1 == rhs.ref_thrust1 &&
    lhs.ref_thrust2 == rhs.ref_thrust2 &&
    lhs.ref_thrust3 == rhs.ref_thrust3 &&
    lhs.ref_thrust4 == rhs.ref_thrust4 &&
    lhs.cmd_thrust1 == rhs.cmd_thrust1 &&
    lhs.cmd_thrust2 == rhs.cmd_thrust2 &&
    lhs.cmd_thrust3 == rhs.cmd_thrust3 &&
    lhs.cmd_thrust4 == rhs.cmd_thrust4 &&
    lhs.Fgh == rhs.Fgh &&
    lhs.ref_thrust_acc == rhs.ref_thrust_acc &&
    lhs.thrust_acc_fil_x == rhs.thrust_acc_fil_x &&
    lhs.thrust_acc_fil_y == rhs.thrust_acc_fil_y &&
    lhs.thrust_acc_fil_z == rhs.thrust_acc_fil_z &&
    lhs.imu_acc_fil_x == rhs.imu_acc_fil_x &&
    lhs.imu_acc_fil_y == rhs.imu_acc_fil_y &&
    lhs.imu_acc_fil_z == rhs.imu_acc_fil_z &&
    lhs.extforce_acc_x == rhs.extforce_acc_x &&
    lhs.extforce_acc_y == rhs.extforce_acc_y &&
    lhs.extforce_acc_z == rhs.extforce_acc_z &&
    lhs.extforce_acc_fil_x == rhs.extforce_acc_fil_x &&
    lhs.extforce_acc_fil_y == rhs.extforce_acc_fil_y &&
    lhs.extforce_acc_fil_z == rhs.extforce_acc_fil_z &&
    lhs.poly_thrust == rhs.poly_thrust &&
    lhs.fb_thrust == rhs.fb_thrust &&
    lhs.sum_thrust == rhs.sum_thrust;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quadrotor_msgs::geDebug_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::geDebug_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quadrotor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::geDebug_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::geDebug_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::geDebug_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::geDebug_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::geDebug_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::geDebug_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quadrotor_msgs::geDebug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "488d08f267b0b36a062742ffec509736";
  }

  static const char* value(const ::quadrotor_msgs::geDebug_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x488d08f267b0b36aULL;
  static const uint64_t static_value2 = 0x062742ffec509736ULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotor_msgs::geDebug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quadrotor_msgs/geDebug";
  }

  static const char* value(const ::quadrotor_msgs::geDebug_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quadrotor_msgs::geDebug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"# sensors-------------------------------------------------\n"
"\n"
"float64 odom_roll\n"
"float64 odom_pitch\n"
"float64 odom_yaw\n"
"\n"
"float64 odomC_roll\n"
"float64 odomC_pitch\n"
"float64 odomC_yaw\n"
"\n"
"float64 ge_angle_roll\n"
"float64 ge_angle_pitch\n"
"float64 ge_angle_yaw\n"
"\n"
"float64 imu_a_x\n"
"float64 imu_a_y\n"
"float64 imu_a_z\n"
"\n"
"float64 imu_a_fil_x\n"
"float64 imu_a_fil_y\n"
"float64 imu_a_fil_z\n"
"\n"
"float64 imu_w_x\n"
"float64 imu_w_y\n"
"float64 imu_w_z\n"
"\n"
"float64 imu_w_fil_x\n"
"float64 imu_w_fil_y\n"
"float64 imu_w_fil_z\n"
"\n"
"float64 imu_w_c_x\n"
"float64 imu_w_c_y\n"
"float64 imu_w_c_z\n"
"\n"
"float64 imu_beta_fil_x\n"
"float64 imu_beta_fil_y\n"
"float64 imu_beta_fil_z\n"
"\n"
"float64 rpm1\n"
"float64 rpm2\n"
"float64 rpm3\n"
"float64 rpm4\n"
"\n"
"float64 rpm1_fil\n"
"float64 rpm2_fil\n"
"float64 rpm3_fil\n"
"float64 rpm4_fil\n"
"\n"
"float64 sumrpm2 #实际转速平方和\n"
"float64 thrust_force #实际推力\n"
"float64 thrust_acc #实际推力加速度\n"
"\n"
"float64 sumrpm2_fil #实际转速平方和，滤波后\n"
"float64 thrust_force_fil #实际推力，滤波后\n"
"float64 thrust_acc_fil #实际推力加速度，滤波后\n"
"\n"
"float64 acc_world_x\n"
"float64 acc_world_y\n"
"float64 acc_world_z\n"
"\n"
"float64 ge_acc_x #按照地效模型，实际的地效额外推力加速度\n"
"float64 ge_acc_y\n"
"float64 ge_acc_z\n"
"\n"
"float64 ge_bodytorque_x #按照地效模型的反扭矩\n"
"float64 ge_bodytorque_y\n"
"float64 ge_bodytorque_z\n"
"\n"
"float64 des_ge_bodytorque_x #按照地效模型的反扭矩\n"
"float64 des_ge_bodytorque_y\n"
"float64 des_ge_bodytorque_z\n"
"\n"
"float64 d_ge_torque_x #按照地效模型的反扭矩的导数\n"
"float64 d_ge_torque_y\n"
"float64 d_ge_torque_z\n"
"\n"
"float64 diff_ge_torque_x #扭矩变化量\n"
"float64 diff_ge_torque_y\n"
"float64 diff_ge_torque_z\n"
"\n"
"float64 ext_torque_x\n"
"float64 ext_torque_y\n"
"float64 ext_torque_z\n"
"\n"
"float64 predict_ext_torque_x\n"
"float64 predict_ext_torque_y\n"
"float64 predict_ext_torque_z\n"
"\n"
"# 控制器接收的指令，来自traj server-------------------------------------------------\n"
"float64 des_p_x\n"
"float64 des_p_y\n"
"float64 des_p_z\n"
"\n"
"float64 des_v_x\n"
"float64 des_v_y\n"
"float64 des_v_z\n"
"\n"
"float64 des_a_x\n"
"float64 des_a_y\n"
"float64 des_a_z\n"
"\n"
"float64 des_j_x\n"
"float64 des_j_y\n"
"float64 des_j_z\n"
"\n"
"float64 des_s_x\n"
"float64 des_s_y\n"
"float64 des_s_z\n"
"\n"
"float64 des_yaw\n"
"float64 des_yaw_rate\n"
"float64 des_yaw_acc\n"
"\n"
"\n"
"# flatness-------------------------------------------------------------------------------\n"
"float64 flatctrl_q_w\n"
"float64 flatctrl_q_x\n"
"float64 flatctrl_q_y\n"
"float64 flatctrl_q_z\n"
"\n"
"float64 flatctrl_roll\n"
"float64 flatctrl_pitch\n"
"float64 flatctrl_yaw\n"
"\n"
"float64 flatctrl_bodyrate_x\n"
"float64 flatctrl_bodyrate_y\n"
"float64 flatctrl_bodyrate_z\n"
"\n"
"float64 flatctrl_beta_x\n"
"float64 flatctrl_beta_y\n"
"float64 flatctrl_beta_z\n"
"\n"
"float64 flatctrl_thrust\n"
"float64 flatctrl_torque_x\n"
"float64 flatctrl_torque_y\n"
"float64 flatctrl_torque_z\n"
"\n"
"# 根据平坦模型：地面效应带来的额外推力加速度\n"
"float64 flatctrl_ge_acc_x\n"
"float64 flatctrl_ge_acc_y\n"
"float64 flatctrl_ge_acc_z\n"
"\n"
"# 根据平坦模型：阻力加速度\n"
"float64 flatctrl_drag_acc_x\n"
"float64 flatctrl_drag_acc_y\n"
"float64 flatctrl_drag_acc_z\n"
"\n"
"# 根据平坦模型：合外力加速度\n"
"float64 flatctrl_ext_acc_x\n"
"float64 flatctrl_ext_acc_y\n"
"float64 flatctrl_ext_acc_z\n"
"\n"
"float64 ge_limit_k\n"
"\n"
"# 加速度环，由误差、外力等输出期望加速度 --------------------------------------------------------------------\n"
"\n"
"float64 fb_vel_x\n"
"float64 fb_vel_y\n"
"float64 fb_vel_z\n"
"float64 cmd_vel_x\n"
"float64 cmd_vel_y\n"
"float64 cmd_vel_z\n"
"\n"
"\n"
"float64 compensate_acc_x #补偿给控制器的加速度\n"
"float64 compensate_acc_y\n"
"float64 compensate_acc_z\n"
"float64 fb_acc_x # 由位置和速度误差得到的反馈加速度\n"
"float64 fb_acc_y\n"
"float64 fb_acc_z\n"
"float64 cmd_acc_x # 需要推力提供的加速度\n"
"float64 cmd_acc_y\n"
"float64 cmd_acc_z\n"
"float64 cmd_acc_norm # 需要推力提供的加速度的模\n"
"float64 cmd_acc_norm_by_body # 需要推力提供的加速度的模，考虑当前姿态\n"
"\n"
"\n"
"# 加速度控制 输出 姿态+推力、角速度+推力，扭矩+推力、转速 ------------------------------------------------\n"
"\n"
"# cmd-----------------------------\n"
"\n"
"float64 cmd_q_w\n"
"float64 cmd_q_x\n"
"float64 cmd_q_y\n"
"float64 cmd_q_z\n"
"\n"
"float64 cmd_roll\n"
"float64 cmd_pitch\n"
"float64 cmd_yaw\n"
"\n"
"\n"
"float64 fb_bodyrate_x\n"
"float64 fb_bodyrate_y\n"
"float64 fb_bodyrate_z\n"
"float64 cmd_bodyrate_x\n"
"float64 cmd_bodyrate_y\n"
"float64 cmd_bodyrate_z\n"
"\n"
"float64 fb_beta_x\n"
"float64 fb_beta_y\n"
"float64 fb_beta_z\n"
"float64 cmd_beta_x\n"
"float64 cmd_beta_y\n"
"float64 cmd_beta_z\n"
"\n"
"#补偿给控制器的扭矩\n"
"float64 compensate_torque_x\n"
"float64 compensate_torque_y\n"
"float64 compensate_torque_z\n"
"\n"
"float64 bodytorque_x\n"
"float64 bodytorque_y\n"
"float64 bodytorque_z\n"
"float64 cmd_torque_body_x\n"
"float64 cmd_torque_body_y\n"
"float64 cmd_torque_body_z\n"
"\n"
"float64 diff_indi_torque_x #INDI方法的力矩增量\n"
"float64 diff_indi_torque_y\n"
"float64 diff_indi_torque_z\n"
"\n"
"float64 diff_torque_x #INDI和模型力矩增量\n"
"float64 diff_torque_y\n"
"float64 diff_torque_z\n"
"\n"
"float64 cmd_rpm1\n"
"float64 cmd_rpm2\n"
"float64 cmd_rpm3\n"
"float64 cmd_rpm4\n"
"float64 cmd_sumrpm2\n"
"float64 cmd_sumrpm2_to_acc\n"
"\n"
"\n"
"# 转速误差引入的推力\n"
"float64 fb_thrust1\n"
"float64 fb_thrust2\n"
"float64 fb_thrust3\n"
"float64 fb_thrust4\n"
"\n"
"# 油门曲线前馈推力\n"
"float64 ref_thrust1\n"
"float64 ref_thrust2\n"
"float64 ref_thrust3\n"
"float64 ref_thrust4\n"
"\n"
"# 实际推力\n"
"float64 cmd_thrust1\n"
"float64 cmd_thrust2\n"
"float64 cmd_thrust3\n"
"float64 cmd_thrust4\n"
"\n"
"# OLD MSGS ----------------------------------------------------------------------------------------------------------\n"
"# ref forces\n"
"float64 Fgh\n"
"\n"
"\n"
"\n"
"# 根据平坦模型：推力加速度\n"
"float64 ref_thrust_acc\n"
"\n"
"\n"
"\n"
"#实际作用在world系上的推力加速度，滤波后\n"
"float64 thrust_acc_fil_x \n"
"float64 thrust_acc_fil_y\n"
"float64 thrust_acc_fil_z\n"
"\n"
"# force estimate\n"
"\n"
"# 滤波后的IMU加速度数据\n"
"float64 imu_acc_fil_x\n"
"float64 imu_acc_fil_y\n"
"float64 imu_acc_fil_z\n"
"\n"
"#外力估计器估计的实际加速度\n"
"float64 extforce_acc_x\n"
"float64 extforce_acc_y\n"
"float64 extforce_acc_z\n"
"\n"
"#外力估计器估计的实际加速度, 滤波后\n"
"float64 extforce_acc_fil_x\n"
"float64 extforce_acc_fil_y\n"
"float64 extforce_acc_fil_z\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"float64 poly_thrust # 根据 油门~转速 模型得到的0~1的前馈油门\n"
"float64 fb_thrust # 根据转速差PID反馈得到的补偿油门差\n"
"float64 sum_thrust # 前馈油门+反馈油门\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::quadrotor_msgs::geDebug_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quadrotor_msgs::geDebug_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.odom_roll);
      stream.next(m.odom_pitch);
      stream.next(m.odom_yaw);
      stream.next(m.odomC_roll);
      stream.next(m.odomC_pitch);
      stream.next(m.odomC_yaw);
      stream.next(m.ge_angle_roll);
      stream.next(m.ge_angle_pitch);
      stream.next(m.ge_angle_yaw);
      stream.next(m.imu_a_x);
      stream.next(m.imu_a_y);
      stream.next(m.imu_a_z);
      stream.next(m.imu_a_fil_x);
      stream.next(m.imu_a_fil_y);
      stream.next(m.imu_a_fil_z);
      stream.next(m.imu_w_x);
      stream.next(m.imu_w_y);
      stream.next(m.imu_w_z);
      stream.next(m.imu_w_fil_x);
      stream.next(m.imu_w_fil_y);
      stream.next(m.imu_w_fil_z);
      stream.next(m.imu_w_c_x);
      stream.next(m.imu_w_c_y);
      stream.next(m.imu_w_c_z);
      stream.next(m.imu_beta_fil_x);
      stream.next(m.imu_beta_fil_y);
      stream.next(m.imu_beta_fil_z);
      stream.next(m.rpm1);
      stream.next(m.rpm2);
      stream.next(m.rpm3);
      stream.next(m.rpm4);
      stream.next(m.rpm1_fil);
      stream.next(m.rpm2_fil);
      stream.next(m.rpm3_fil);
      stream.next(m.rpm4_fil);
      stream.next(m.sumrpm2);
      stream.next(m.thrust_force);
      stream.next(m.thrust_acc);
      stream.next(m.sumrpm2_fil);
      stream.next(m.thrust_force_fil);
      stream.next(m.thrust_acc_fil);
      stream.next(m.acc_world_x);
      stream.next(m.acc_world_y);
      stream.next(m.acc_world_z);
      stream.next(m.ge_acc_x);
      stream.next(m.ge_acc_y);
      stream.next(m.ge_acc_z);
      stream.next(m.ge_bodytorque_x);
      stream.next(m.ge_bodytorque_y);
      stream.next(m.ge_bodytorque_z);
      stream.next(m.des_ge_bodytorque_x);
      stream.next(m.des_ge_bodytorque_y);
      stream.next(m.des_ge_bodytorque_z);
      stream.next(m.d_ge_torque_x);
      stream.next(m.d_ge_torque_y);
      stream.next(m.d_ge_torque_z);
      stream.next(m.diff_ge_torque_x);
      stream.next(m.diff_ge_torque_y);
      stream.next(m.diff_ge_torque_z);
      stream.next(m.ext_torque_x);
      stream.next(m.ext_torque_y);
      stream.next(m.ext_torque_z);
      stream.next(m.predict_ext_torque_x);
      stream.next(m.predict_ext_torque_y);
      stream.next(m.predict_ext_torque_z);
      stream.next(m.des_p_x);
      stream.next(m.des_p_y);
      stream.next(m.des_p_z);
      stream.next(m.des_v_x);
      stream.next(m.des_v_y);
      stream.next(m.des_v_z);
      stream.next(m.des_a_x);
      stream.next(m.des_a_y);
      stream.next(m.des_a_z);
      stream.next(m.des_j_x);
      stream.next(m.des_j_y);
      stream.next(m.des_j_z);
      stream.next(m.des_s_x);
      stream.next(m.des_s_y);
      stream.next(m.des_s_z);
      stream.next(m.des_yaw);
      stream.next(m.des_yaw_rate);
      stream.next(m.des_yaw_acc);
      stream.next(m.flatctrl_q_w);
      stream.next(m.flatctrl_q_x);
      stream.next(m.flatctrl_q_y);
      stream.next(m.flatctrl_q_z);
      stream.next(m.flatctrl_roll);
      stream.next(m.flatctrl_pitch);
      stream.next(m.flatctrl_yaw);
      stream.next(m.flatctrl_bodyrate_x);
      stream.next(m.flatctrl_bodyrate_y);
      stream.next(m.flatctrl_bodyrate_z);
      stream.next(m.flatctrl_beta_x);
      stream.next(m.flatctrl_beta_y);
      stream.next(m.flatctrl_beta_z);
      stream.next(m.flatctrl_thrust);
      stream.next(m.flatctrl_torque_x);
      stream.next(m.flatctrl_torque_y);
      stream.next(m.flatctrl_torque_z);
      stream.next(m.flatctrl_ge_acc_x);
      stream.next(m.flatctrl_ge_acc_y);
      stream.next(m.flatctrl_ge_acc_z);
      stream.next(m.flatctrl_drag_acc_x);
      stream.next(m.flatctrl_drag_acc_y);
      stream.next(m.flatctrl_drag_acc_z);
      stream.next(m.flatctrl_ext_acc_x);
      stream.next(m.flatctrl_ext_acc_y);
      stream.next(m.flatctrl_ext_acc_z);
      stream.next(m.ge_limit_k);
      stream.next(m.fb_vel_x);
      stream.next(m.fb_vel_y);
      stream.next(m.fb_vel_z);
      stream.next(m.cmd_vel_x);
      stream.next(m.cmd_vel_y);
      stream.next(m.cmd_vel_z);
      stream.next(m.compensate_acc_x);
      stream.next(m.compensate_acc_y);
      stream.next(m.compensate_acc_z);
      stream.next(m.fb_acc_x);
      stream.next(m.fb_acc_y);
      stream.next(m.fb_acc_z);
      stream.next(m.cmd_acc_x);
      stream.next(m.cmd_acc_y);
      stream.next(m.cmd_acc_z);
      stream.next(m.cmd_acc_norm);
      stream.next(m.cmd_acc_norm_by_body);
      stream.next(m.cmd_q_w);
      stream.next(m.cmd_q_x);
      stream.next(m.cmd_q_y);
      stream.next(m.cmd_q_z);
      stream.next(m.cmd_roll);
      stream.next(m.cmd_pitch);
      stream.next(m.cmd_yaw);
      stream.next(m.fb_bodyrate_x);
      stream.next(m.fb_bodyrate_y);
      stream.next(m.fb_bodyrate_z);
      stream.next(m.cmd_bodyrate_x);
      stream.next(m.cmd_bodyrate_y);
      stream.next(m.cmd_bodyrate_z);
      stream.next(m.fb_beta_x);
      stream.next(m.fb_beta_y);
      stream.next(m.fb_beta_z);
      stream.next(m.cmd_beta_x);
      stream.next(m.cmd_beta_y);
      stream.next(m.cmd_beta_z);
      stream.next(m.compensate_torque_x);
      stream.next(m.compensate_torque_y);
      stream.next(m.compensate_torque_z);
      stream.next(m.bodytorque_x);
      stream.next(m.bodytorque_y);
      stream.next(m.bodytorque_z);
      stream.next(m.cmd_torque_body_x);
      stream.next(m.cmd_torque_body_y);
      stream.next(m.cmd_torque_body_z);
      stream.next(m.diff_indi_torque_x);
      stream.next(m.diff_indi_torque_y);
      stream.next(m.diff_indi_torque_z);
      stream.next(m.diff_torque_x);
      stream.next(m.diff_torque_y);
      stream.next(m.diff_torque_z);
      stream.next(m.cmd_rpm1);
      stream.next(m.cmd_rpm2);
      stream.next(m.cmd_rpm3);
      stream.next(m.cmd_rpm4);
      stream.next(m.cmd_sumrpm2);
      stream.next(m.cmd_sumrpm2_to_acc);
      stream.next(m.fb_thrust1);
      stream.next(m.fb_thrust2);
      stream.next(m.fb_thrust3);
      stream.next(m.fb_thrust4);
      stream.next(m.ref_thrust1);
      stream.next(m.ref_thrust2);
      stream.next(m.ref_thrust3);
      stream.next(m.ref_thrust4);
      stream.next(m.cmd_thrust1);
      stream.next(m.cmd_thrust2);
      stream.next(m.cmd_thrust3);
      stream.next(m.cmd_thrust4);
      stream.next(m.Fgh);
      stream.next(m.ref_thrust_acc);
      stream.next(m.thrust_acc_fil_x);
      stream.next(m.thrust_acc_fil_y);
      stream.next(m.thrust_acc_fil_z);
      stream.next(m.imu_acc_fil_x);
      stream.next(m.imu_acc_fil_y);
      stream.next(m.imu_acc_fil_z);
      stream.next(m.extforce_acc_x);
      stream.next(m.extforce_acc_y);
      stream.next(m.extforce_acc_z);
      stream.next(m.extforce_acc_fil_x);
      stream.next(m.extforce_acc_fil_y);
      stream.next(m.extforce_acc_fil_z);
      stream.next(m.poly_thrust);
      stream.next(m.fb_thrust);
      stream.next(m.sum_thrust);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct geDebug_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadrotor_msgs::geDebug_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quadrotor_msgs::geDebug_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "odom_roll: ";
    Printer<double>::stream(s, indent + "  ", v.odom_roll);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "odom_pitch: ";
    Printer<double>::stream(s, indent + "  ", v.odom_pitch);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "odom_yaw: ";
    Printer<double>::stream(s, indent + "  ", v.odom_yaw);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "odomC_roll: ";
    Printer<double>::stream(s, indent + "  ", v.odomC_roll);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "odomC_pitch: ";
    Printer<double>::stream(s, indent + "  ", v.odomC_pitch);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "odomC_yaw: ";
    Printer<double>::stream(s, indent + "  ", v.odomC_yaw);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ge_angle_roll: ";
    Printer<double>::stream(s, indent + "  ", v.ge_angle_roll);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ge_angle_pitch: ";
    Printer<double>::stream(s, indent + "  ", v.ge_angle_pitch);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ge_angle_yaw: ";
    Printer<double>::stream(s, indent + "  ", v.ge_angle_yaw);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "imu_a_x: ";
    Printer<double>::stream(s, indent + "  ", v.imu_a_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "imu_a_y: ";
    Printer<double>::stream(s, indent + "  ", v.imu_a_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "imu_a_z: ";
    Printer<double>::stream(s, indent + "  ", v.imu_a_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "imu_a_fil_x: ";
    Printer<double>::stream(s, indent + "  ", v.imu_a_fil_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "imu_a_fil_y: ";
    Printer<double>::stream(s, indent + "  ", v.imu_a_fil_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "imu_a_fil_z: ";
    Printer<double>::stream(s, indent + "  ", v.imu_a_fil_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "imu_w_x: ";
    Printer<double>::stream(s, indent + "  ", v.imu_w_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "imu_w_y: ";
    Printer<double>::stream(s, indent + "  ", v.imu_w_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "imu_w_z: ";
    Printer<double>::stream(s, indent + "  ", v.imu_w_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "imu_w_fil_x: ";
    Printer<double>::stream(s, indent + "  ", v.imu_w_fil_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "imu_w_fil_y: ";
    Printer<double>::stream(s, indent + "  ", v.imu_w_fil_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "imu_w_fil_z: ";
    Printer<double>::stream(s, indent + "  ", v.imu_w_fil_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "imu_w_c_x: ";
    Printer<double>::stream(s, indent + "  ", v.imu_w_c_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "imu_w_c_y: ";
    Printer<double>::stream(s, indent + "  ", v.imu_w_c_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "imu_w_c_z: ";
    Printer<double>::stream(s, indent + "  ", v.imu_w_c_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "imu_beta_fil_x: ";
    Printer<double>::stream(s, indent + "  ", v.imu_beta_fil_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "imu_beta_fil_y: ";
    Printer<double>::stream(s, indent + "  ", v.imu_beta_fil_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "imu_beta_fil_z: ";
    Printer<double>::stream(s, indent + "  ", v.imu_beta_fil_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rpm1: ";
    Printer<double>::stream(s, indent + "  ", v.rpm1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rpm2: ";
    Printer<double>::stream(s, indent + "  ", v.rpm2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rpm3: ";
    Printer<double>::stream(s, indent + "  ", v.rpm3);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rpm4: ";
    Printer<double>::stream(s, indent + "  ", v.rpm4);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rpm1_fil: ";
    Printer<double>::stream(s, indent + "  ", v.rpm1_fil);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rpm2_fil: ";
    Printer<double>::stream(s, indent + "  ", v.rpm2_fil);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rpm3_fil: ";
    Printer<double>::stream(s, indent + "  ", v.rpm3_fil);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rpm4_fil: ";
    Printer<double>::stream(s, indent + "  ", v.rpm4_fil);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "sumrpm2: ";
    Printer<double>::stream(s, indent + "  ", v.sumrpm2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "thrust_force: ";
    Printer<double>::stream(s, indent + "  ", v.thrust_force);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "thrust_acc: ";
    Printer<double>::stream(s, indent + "  ", v.thrust_acc);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "sumrpm2_fil: ";
    Printer<double>::stream(s, indent + "  ", v.sumrpm2_fil);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "thrust_force_fil: ";
    Printer<double>::stream(s, indent + "  ", v.thrust_force_fil);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "thrust_acc_fil: ";
    Printer<double>::stream(s, indent + "  ", v.thrust_acc_fil);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "acc_world_x: ";
    Printer<double>::stream(s, indent + "  ", v.acc_world_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "acc_world_y: ";
    Printer<double>::stream(s, indent + "  ", v.acc_world_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "acc_world_z: ";
    Printer<double>::stream(s, indent + "  ", v.acc_world_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ge_acc_x: ";
    Printer<double>::stream(s, indent + "  ", v.ge_acc_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ge_acc_y: ";
    Printer<double>::stream(s, indent + "  ", v.ge_acc_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ge_acc_z: ";
    Printer<double>::stream(s, indent + "  ", v.ge_acc_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ge_bodytorque_x: ";
    Printer<double>::stream(s, indent + "  ", v.ge_bodytorque_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ge_bodytorque_y: ";
    Printer<double>::stream(s, indent + "  ", v.ge_bodytorque_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ge_bodytorque_z: ";
    Printer<double>::stream(s, indent + "  ", v.ge_bodytorque_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_ge_bodytorque_x: ";
    Printer<double>::stream(s, indent + "  ", v.des_ge_bodytorque_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_ge_bodytorque_y: ";
    Printer<double>::stream(s, indent + "  ", v.des_ge_bodytorque_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_ge_bodytorque_z: ";
    Printer<double>::stream(s, indent + "  ", v.des_ge_bodytorque_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "d_ge_torque_x: ";
    Printer<double>::stream(s, indent + "  ", v.d_ge_torque_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "d_ge_torque_y: ";
    Printer<double>::stream(s, indent + "  ", v.d_ge_torque_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "d_ge_torque_z: ";
    Printer<double>::stream(s, indent + "  ", v.d_ge_torque_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "diff_ge_torque_x: ";
    Printer<double>::stream(s, indent + "  ", v.diff_ge_torque_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "diff_ge_torque_y: ";
    Printer<double>::stream(s, indent + "  ", v.diff_ge_torque_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "diff_ge_torque_z: ";
    Printer<double>::stream(s, indent + "  ", v.diff_ge_torque_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ext_torque_x: ";
    Printer<double>::stream(s, indent + "  ", v.ext_torque_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ext_torque_y: ";
    Printer<double>::stream(s, indent + "  ", v.ext_torque_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ext_torque_z: ";
    Printer<double>::stream(s, indent + "  ", v.ext_torque_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "predict_ext_torque_x: ";
    Printer<double>::stream(s, indent + "  ", v.predict_ext_torque_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "predict_ext_torque_y: ";
    Printer<double>::stream(s, indent + "  ", v.predict_ext_torque_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "predict_ext_torque_z: ";
    Printer<double>::stream(s, indent + "  ", v.predict_ext_torque_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_p_x: ";
    Printer<double>::stream(s, indent + "  ", v.des_p_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_p_y: ";
    Printer<double>::stream(s, indent + "  ", v.des_p_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_p_z: ";
    Printer<double>::stream(s, indent + "  ", v.des_p_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_v_x: ";
    Printer<double>::stream(s, indent + "  ", v.des_v_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_v_y: ";
    Printer<double>::stream(s, indent + "  ", v.des_v_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_v_z: ";
    Printer<double>::stream(s, indent + "  ", v.des_v_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_a_x: ";
    Printer<double>::stream(s, indent + "  ", v.des_a_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_a_y: ";
    Printer<double>::stream(s, indent + "  ", v.des_a_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_a_z: ";
    Printer<double>::stream(s, indent + "  ", v.des_a_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_j_x: ";
    Printer<double>::stream(s, indent + "  ", v.des_j_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_j_y: ";
    Printer<double>::stream(s, indent + "  ", v.des_j_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_j_z: ";
    Printer<double>::stream(s, indent + "  ", v.des_j_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_s_x: ";
    Printer<double>::stream(s, indent + "  ", v.des_s_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_s_y: ";
    Printer<double>::stream(s, indent + "  ", v.des_s_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_s_z: ";
    Printer<double>::stream(s, indent + "  ", v.des_s_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_yaw: ";
    Printer<double>::stream(s, indent + "  ", v.des_yaw);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_yaw_rate: ";
    Printer<double>::stream(s, indent + "  ", v.des_yaw_rate);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_yaw_acc: ";
    Printer<double>::stream(s, indent + "  ", v.des_yaw_acc);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flatctrl_q_w: ";
    Printer<double>::stream(s, indent + "  ", v.flatctrl_q_w);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flatctrl_q_x: ";
    Printer<double>::stream(s, indent + "  ", v.flatctrl_q_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flatctrl_q_y: ";
    Printer<double>::stream(s, indent + "  ", v.flatctrl_q_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flatctrl_q_z: ";
    Printer<double>::stream(s, indent + "  ", v.flatctrl_q_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flatctrl_roll: ";
    Printer<double>::stream(s, indent + "  ", v.flatctrl_roll);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flatctrl_pitch: ";
    Printer<double>::stream(s, indent + "  ", v.flatctrl_pitch);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flatctrl_yaw: ";
    Printer<double>::stream(s, indent + "  ", v.flatctrl_yaw);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flatctrl_bodyrate_x: ";
    Printer<double>::stream(s, indent + "  ", v.flatctrl_bodyrate_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flatctrl_bodyrate_y: ";
    Printer<double>::stream(s, indent + "  ", v.flatctrl_bodyrate_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flatctrl_bodyrate_z: ";
    Printer<double>::stream(s, indent + "  ", v.flatctrl_bodyrate_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flatctrl_beta_x: ";
    Printer<double>::stream(s, indent + "  ", v.flatctrl_beta_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flatctrl_beta_y: ";
    Printer<double>::stream(s, indent + "  ", v.flatctrl_beta_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flatctrl_beta_z: ";
    Printer<double>::stream(s, indent + "  ", v.flatctrl_beta_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flatctrl_thrust: ";
    Printer<double>::stream(s, indent + "  ", v.flatctrl_thrust);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flatctrl_torque_x: ";
    Printer<double>::stream(s, indent + "  ", v.flatctrl_torque_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flatctrl_torque_y: ";
    Printer<double>::stream(s, indent + "  ", v.flatctrl_torque_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flatctrl_torque_z: ";
    Printer<double>::stream(s, indent + "  ", v.flatctrl_torque_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flatctrl_ge_acc_x: ";
    Printer<double>::stream(s, indent + "  ", v.flatctrl_ge_acc_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flatctrl_ge_acc_y: ";
    Printer<double>::stream(s, indent + "  ", v.flatctrl_ge_acc_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flatctrl_ge_acc_z: ";
    Printer<double>::stream(s, indent + "  ", v.flatctrl_ge_acc_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flatctrl_drag_acc_x: ";
    Printer<double>::stream(s, indent + "  ", v.flatctrl_drag_acc_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flatctrl_drag_acc_y: ";
    Printer<double>::stream(s, indent + "  ", v.flatctrl_drag_acc_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flatctrl_drag_acc_z: ";
    Printer<double>::stream(s, indent + "  ", v.flatctrl_drag_acc_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flatctrl_ext_acc_x: ";
    Printer<double>::stream(s, indent + "  ", v.flatctrl_ext_acc_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flatctrl_ext_acc_y: ";
    Printer<double>::stream(s, indent + "  ", v.flatctrl_ext_acc_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flatctrl_ext_acc_z: ";
    Printer<double>::stream(s, indent + "  ", v.flatctrl_ext_acc_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ge_limit_k: ";
    Printer<double>::stream(s, indent + "  ", v.ge_limit_k);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_vel_x: ";
    Printer<double>::stream(s, indent + "  ", v.fb_vel_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_vel_y: ";
    Printer<double>::stream(s, indent + "  ", v.fb_vel_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_vel_z: ";
    Printer<double>::stream(s, indent + "  ", v.fb_vel_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_vel_x: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_vel_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_vel_y: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_vel_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_vel_z: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_vel_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "compensate_acc_x: ";
    Printer<double>::stream(s, indent + "  ", v.compensate_acc_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "compensate_acc_y: ";
    Printer<double>::stream(s, indent + "  ", v.compensate_acc_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "compensate_acc_z: ";
    Printer<double>::stream(s, indent + "  ", v.compensate_acc_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_acc_x: ";
    Printer<double>::stream(s, indent + "  ", v.fb_acc_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_acc_y: ";
    Printer<double>::stream(s, indent + "  ", v.fb_acc_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_acc_z: ";
    Printer<double>::stream(s, indent + "  ", v.fb_acc_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_acc_x: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_acc_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_acc_y: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_acc_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_acc_z: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_acc_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_acc_norm: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_acc_norm);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_acc_norm_by_body: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_acc_norm_by_body);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_q_w: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_q_w);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_q_x: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_q_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_q_y: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_q_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_q_z: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_q_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_roll: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_roll);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_pitch: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_pitch);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_yaw: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_yaw);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_bodyrate_x: ";
    Printer<double>::stream(s, indent + "  ", v.fb_bodyrate_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_bodyrate_y: ";
    Printer<double>::stream(s, indent + "  ", v.fb_bodyrate_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_bodyrate_z: ";
    Printer<double>::stream(s, indent + "  ", v.fb_bodyrate_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_bodyrate_x: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_bodyrate_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_bodyrate_y: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_bodyrate_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_bodyrate_z: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_bodyrate_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_beta_x: ";
    Printer<double>::stream(s, indent + "  ", v.fb_beta_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_beta_y: ";
    Printer<double>::stream(s, indent + "  ", v.fb_beta_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_beta_z: ";
    Printer<double>::stream(s, indent + "  ", v.fb_beta_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_beta_x: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_beta_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_beta_y: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_beta_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_beta_z: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_beta_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "compensate_torque_x: ";
    Printer<double>::stream(s, indent + "  ", v.compensate_torque_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "compensate_torque_y: ";
    Printer<double>::stream(s, indent + "  ", v.compensate_torque_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "compensate_torque_z: ";
    Printer<double>::stream(s, indent + "  ", v.compensate_torque_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bodytorque_x: ";
    Printer<double>::stream(s, indent + "  ", v.bodytorque_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bodytorque_y: ";
    Printer<double>::stream(s, indent + "  ", v.bodytorque_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bodytorque_z: ";
    Printer<double>::stream(s, indent + "  ", v.bodytorque_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_torque_body_x: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_torque_body_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_torque_body_y: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_torque_body_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_torque_body_z: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_torque_body_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "diff_indi_torque_x: ";
    Printer<double>::stream(s, indent + "  ", v.diff_indi_torque_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "diff_indi_torque_y: ";
    Printer<double>::stream(s, indent + "  ", v.diff_indi_torque_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "diff_indi_torque_z: ";
    Printer<double>::stream(s, indent + "  ", v.diff_indi_torque_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "diff_torque_x: ";
    Printer<double>::stream(s, indent + "  ", v.diff_torque_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "diff_torque_y: ";
    Printer<double>::stream(s, indent + "  ", v.diff_torque_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "diff_torque_z: ";
    Printer<double>::stream(s, indent + "  ", v.diff_torque_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_rpm1: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_rpm1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_rpm2: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_rpm2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_rpm3: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_rpm3);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_rpm4: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_rpm4);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_sumrpm2: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_sumrpm2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_sumrpm2_to_acc: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_sumrpm2_to_acc);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_thrust1: ";
    Printer<double>::stream(s, indent + "  ", v.fb_thrust1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_thrust2: ";
    Printer<double>::stream(s, indent + "  ", v.fb_thrust2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_thrust3: ";
    Printer<double>::stream(s, indent + "  ", v.fb_thrust3);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_thrust4: ";
    Printer<double>::stream(s, indent + "  ", v.fb_thrust4);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_thrust1: ";
    Printer<double>::stream(s, indent + "  ", v.ref_thrust1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_thrust2: ";
    Printer<double>::stream(s, indent + "  ", v.ref_thrust2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_thrust3: ";
    Printer<double>::stream(s, indent + "  ", v.ref_thrust3);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_thrust4: ";
    Printer<double>::stream(s, indent + "  ", v.ref_thrust4);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_thrust1: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_thrust1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_thrust2: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_thrust2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_thrust3: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_thrust3);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_thrust4: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_thrust4);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Fgh: ";
    Printer<double>::stream(s, indent + "  ", v.Fgh);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_thrust_acc: ";
    Printer<double>::stream(s, indent + "  ", v.ref_thrust_acc);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "thrust_acc_fil_x: ";
    Printer<double>::stream(s, indent + "  ", v.thrust_acc_fil_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "thrust_acc_fil_y: ";
    Printer<double>::stream(s, indent + "  ", v.thrust_acc_fil_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "thrust_acc_fil_z: ";
    Printer<double>::stream(s, indent + "  ", v.thrust_acc_fil_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "imu_acc_fil_x: ";
    Printer<double>::stream(s, indent + "  ", v.imu_acc_fil_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "imu_acc_fil_y: ";
    Printer<double>::stream(s, indent + "  ", v.imu_acc_fil_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "imu_acc_fil_z: ";
    Printer<double>::stream(s, indent + "  ", v.imu_acc_fil_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "extforce_acc_x: ";
    Printer<double>::stream(s, indent + "  ", v.extforce_acc_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "extforce_acc_y: ";
    Printer<double>::stream(s, indent + "  ", v.extforce_acc_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "extforce_acc_z: ";
    Printer<double>::stream(s, indent + "  ", v.extforce_acc_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "extforce_acc_fil_x: ";
    Printer<double>::stream(s, indent + "  ", v.extforce_acc_fil_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "extforce_acc_fil_y: ";
    Printer<double>::stream(s, indent + "  ", v.extforce_acc_fil_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "extforce_acc_fil_z: ";
    Printer<double>::stream(s, indent + "  ", v.extforce_acc_fil_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "poly_thrust: ";
    Printer<double>::stream(s, indent + "  ", v.poly_thrust);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_thrust: ";
    Printer<double>::stream(s, indent + "  ", v.fb_thrust);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "sum_thrust: ";
    Printer<double>::stream(s, indent + "  ", v.sum_thrust);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUADROTOR_MSGS_MESSAGE_GEDEBUG_H
