// Generated by gencpp from file quadrotor_msgs/IndiState.msg
// DO NOT EDIT!


#ifndef QUADROTOR_MSGS_MESSAGE_INDISTATE_H
#define QUADROTOR_MSGS_MESSAGE_INDISTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace quadrotor_msgs
{
template <class ContainerAllocator>
struct IndiState_
{
  typedef IndiState_<ContainerAllocator> Type;

  IndiState_()
    : header()
    , indiF(0.0)
    , indiqt(0.0)
    , indiqy(0.0)
    , indiq()
    , drpy()
    , cp()
    , cv()
    , ca()
    , cq()
    , cF()  {
    }
  IndiState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , indiF(0.0)
    , indiqt(0.0)
    , indiqy(0.0)
    , indiq(_alloc)
    , drpy(_alloc)
    , cp(_alloc)
    , cv(_alloc)
    , ca(_alloc)
    , cq(_alloc)
    , cF(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _indiF_type;
  _indiF_type indiF;

   typedef double _indiqt_type;
  _indiqt_type indiqt;

   typedef double _indiqy_type;
  _indiqy_type indiqy;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _indiq_type;
  _indiq_type indiq;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _drpy_type;
  _drpy_type drpy;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _cp_type;
  _cp_type cp;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _cv_type;
  _cv_type cv;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _ca_type;
  _ca_type ca;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _cq_type;
  _cq_type cq;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _cF_type;
  _cF_type cF;





  typedef boost::shared_ptr< ::quadrotor_msgs::IndiState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotor_msgs::IndiState_<ContainerAllocator> const> ConstPtr;

}; // struct IndiState_

typedef ::quadrotor_msgs::IndiState_<std::allocator<void> > IndiState;

typedef boost::shared_ptr< ::quadrotor_msgs::IndiState > IndiStatePtr;
typedef boost::shared_ptr< ::quadrotor_msgs::IndiState const> IndiStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quadrotor_msgs::IndiState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quadrotor_msgs::IndiState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quadrotor_msgs::IndiState_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::IndiState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.indiF == rhs.indiF &&
    lhs.indiqt == rhs.indiqt &&
    lhs.indiqy == rhs.indiqy &&
    lhs.indiq == rhs.indiq &&
    lhs.drpy == rhs.drpy &&
    lhs.cp == rhs.cp &&
    lhs.cv == rhs.cv &&
    lhs.ca == rhs.ca &&
    lhs.cq == rhs.cq &&
    lhs.cF == rhs.cF;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quadrotor_msgs::IndiState_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::IndiState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quadrotor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::IndiState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::IndiState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::IndiState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::IndiState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::IndiState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::IndiState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quadrotor_msgs::IndiState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3911a5b39960e03dbb9636a0eb9cd311";
  }

  static const char* value(const ::quadrotor_msgs::IndiState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3911a5b39960e03dULL;
  static const uint64_t static_value2 = 0xbb9636a0eb9cd311ULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotor_msgs::IndiState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quadrotor_msgs/IndiState";
  }

  static const char* value(const ::quadrotor_msgs::IndiState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quadrotor_msgs::IndiState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 indiF\n"
"float64 indiqt\n"
"float64 indiqy\n"
"geometry_msgs/Vector3 indiq\n"
"geometry_msgs/Vector3 drpy\n"
"geometry_msgs/Vector3 cp\n"
"geometry_msgs/Vector3 cv\n"
"geometry_msgs/Vector3 ca\n"
"geometry_msgs/Vector3 cq\n"
"geometry_msgs/Vector3 cF \n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::quadrotor_msgs::IndiState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quadrotor_msgs::IndiState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.indiF);
      stream.next(m.indiqt);
      stream.next(m.indiqy);
      stream.next(m.indiq);
      stream.next(m.drpy);
      stream.next(m.cp);
      stream.next(m.cv);
      stream.next(m.ca);
      stream.next(m.cq);
      stream.next(m.cF);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IndiState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadrotor_msgs::IndiState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quadrotor_msgs::IndiState_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "indiF: ";
    Printer<double>::stream(s, indent + "  ", v.indiF);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "indiqt: ";
    Printer<double>::stream(s, indent + "  ", v.indiqt);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "indiqy: ";
    Printer<double>::stream(s, indent + "  ", v.indiqy);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "indiq: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.indiq);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "drpy: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.drpy);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cp: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.cp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cv: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.cv);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ca: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.ca);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cq: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.cq);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cF: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.cF);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUADROTOR_MSGS_MESSAGE_INDISTATE_H
