// Generated by gencpp from file quadrotor_msgs/LoadCorridor.msg
// DO NOT EDIT!


#ifndef QUADROTOR_MSGS_MESSAGE_LOADCORRIDOR_H
#define QUADROTOR_MSGS_MESSAGE_LOADCORRIDOR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <quadrotor_msgs/CorridorPolytope.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>

namespace quadrotor_msgs
{
template <class ContainerAllocator>
struct LoadCorridor_
{
  typedef LoadCorridor_<ContainerAllocator> Type;

  LoadCorridor_()
    : header()
    , polytopes()
    , transition_centers()
    , transition_radii()
    , transition_tangents()
    , transition_longitudinal_radii()
    , transition_transverse_radii()  {
    }
  LoadCorridor_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , polytopes(_alloc)
    , transition_centers(_alloc)
    , transition_radii(_alloc)
    , transition_tangents(_alloc)
    , transition_longitudinal_radii(_alloc)
    , transition_transverse_radii(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::quadrotor_msgs::CorridorPolytope_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::quadrotor_msgs::CorridorPolytope_<ContainerAllocator> >> _polytopes_type;
  _polytopes_type polytopes;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _transition_centers_type;
  _transition_centers_type transition_centers;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _transition_radii_type;
  _transition_radii_type transition_radii;

   typedef std::vector< ::geometry_msgs::Vector3_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Vector3_<ContainerAllocator> >> _transition_tangents_type;
  _transition_tangents_type transition_tangents;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _transition_longitudinal_radii_type;
  _transition_longitudinal_radii_type transition_longitudinal_radii;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _transition_transverse_radii_type;
  _transition_transverse_radii_type transition_transverse_radii;





  typedef boost::shared_ptr< ::quadrotor_msgs::LoadCorridor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotor_msgs::LoadCorridor_<ContainerAllocator> const> ConstPtr;

}; // struct LoadCorridor_

typedef ::quadrotor_msgs::LoadCorridor_<std::allocator<void> > LoadCorridor;

typedef boost::shared_ptr< ::quadrotor_msgs::LoadCorridor > LoadCorridorPtr;
typedef boost::shared_ptr< ::quadrotor_msgs::LoadCorridor const> LoadCorridorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quadrotor_msgs::LoadCorridor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quadrotor_msgs::LoadCorridor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quadrotor_msgs::LoadCorridor_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::LoadCorridor_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.polytopes == rhs.polytopes &&
    lhs.transition_centers == rhs.transition_centers &&
    lhs.transition_radii == rhs.transition_radii &&
    lhs.transition_tangents == rhs.transition_tangents &&
    lhs.transition_longitudinal_radii == rhs.transition_longitudinal_radii &&
    lhs.transition_transverse_radii == rhs.transition_transverse_radii;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quadrotor_msgs::LoadCorridor_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::LoadCorridor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quadrotor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::LoadCorridor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::LoadCorridor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::LoadCorridor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::LoadCorridor_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::LoadCorridor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::LoadCorridor_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quadrotor_msgs::LoadCorridor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36351e1e34a11193f6c66fa2067de8d5";
  }

  static const char* value(const ::quadrotor_msgs::LoadCorridor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36351e1e34a11193ULL;
  static const uint64_t static_value2 = 0xf6c66fa2067de8d5ULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotor_msgs::LoadCorridor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quadrotor_msgs/LoadCorridor";
  }

  static const char* value(const ::quadrotor_msgs::LoadCorridor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quadrotor_msgs::LoadCorridor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"quadrotor_msgs/CorridorPolytope[] polytopes\n"
"geometry_msgs/Point[] transition_centers\n"
"float64[] transition_radii\n"
"geometry_msgs/Vector3[] transition_tangents\n"
"float64[] transition_longitudinal_radii\n"
"float64[] transition_transverse_radii\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: quadrotor_msgs/CorridorPolytope\n"
"uint32 path_begin\n"
"uint32 path_end\n"
"geometry_msgs/Vector3[] normals\n"
"float64[] offsets\n"
"geometry_msgs/Point[] vertices\n"
"bool clearance_bridge\n"
"float64 complexity\n"
"float64 local_extent\n"
"float64 minimum_system_margin\n"
"float64 maximum_system_margin\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::quadrotor_msgs::LoadCorridor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quadrotor_msgs::LoadCorridor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.polytopes);
      stream.next(m.transition_centers);
      stream.next(m.transition_radii);
      stream.next(m.transition_tangents);
      stream.next(m.transition_longitudinal_radii);
      stream.next(m.transition_transverse_radii);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LoadCorridor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadrotor_msgs::LoadCorridor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quadrotor_msgs::LoadCorridor_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "polytopes: ";
    if (v.polytopes.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.polytopes.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::quadrotor_msgs::CorridorPolytope_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.polytopes[i]);
    }
    if (v.polytopes.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "transition_centers: ";
    if (v.transition_centers.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.transition_centers.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.transition_centers[i]);
    }
    if (v.transition_centers.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "transition_radii: ";
    if (v.transition_radii.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.transition_radii.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.transition_radii[i]);
    }
    if (v.transition_radii.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "transition_tangents: ";
    if (v.transition_tangents.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.transition_tangents.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.transition_tangents[i]);
    }
    if (v.transition_tangents.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "transition_longitudinal_radii: ";
    if (v.transition_longitudinal_radii.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.transition_longitudinal_radii.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.transition_longitudinal_radii[i]);
    }
    if (v.transition_longitudinal_radii.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "transition_transverse_radii: ";
    if (v.transition_transverse_radii.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.transition_transverse_radii.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.transition_transverse_radii[i]);
    }
    if (v.transition_transverse_radii.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUADROTOR_MSGS_MESSAGE_LOADCORRIDOR_H
