// Generated by gencpp from file quadrotor_msgs/Px4ctrlDebug.msg
// DO NOT EDIT!


#ifndef QUADROTOR_MSGS_MESSAGE_PX4CTRLDEBUG_H
#define QUADROTOR_MSGS_MESSAGE_PX4CTRLDEBUG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace quadrotor_msgs
{
template <class ContainerAllocator>
struct Px4ctrlDebug_
{
  typedef Px4ctrlDebug_<ContainerAllocator> Type;

  Px4ctrlDebug_()
    : header()
    , fb_a_x(0.0)
    , fb_a_y(0.0)
    , fb_a_z(0.0)
    , des_p_x(0.0)
    , des_p_y(0.0)
    , des_p_z(0.0)
    , des_v_x(0.0)
    , des_v_y(0.0)
    , des_v_z(0.0)
    , des_a_x(0.0)
    , des_a_y(0.0)
    , des_a_z(0.0)
    , des_q_x(0.0)
    , des_q_y(0.0)
    , des_q_z(0.0)
    , des_q_w(0.0)
    , est_r(0.0)
    , est_p(0.0)
    , est_y(0.0)
    , ref_r(0.0)
    , ref_p(0.0)
    , ref_y(0.0)
    , des_r(0.0)
    , des_p(0.0)
    , des_y(0.0)
    , exec_err_axisang_x(0.0)
    , exec_err_axisang_y(0.0)
    , exec_err_axisang_z(0.0)
    , exec_err_axisang_ang(0.0)
    , fb_axisang_x(0.0)
    , fb_axisang_y(0.0)
    , fb_axisang_z(0.0)
    , fb_axisang_ang(0.0)
    , fb_rate_x(0.0)
    , fb_rate_y(0.0)
    , fb_rate_z(0.0)
    , des_bodyrates_x(0.0)
    , des_bodyrates_y(0.0)
    , des_bodyrates_z(0.0)
    , des_bodyaccs_x(0.0)
    , des_bodyaccs_y(0.0)
    , des_bodyaccs_z(0.0)
    , imu_af_x(0.0)
    , imu_af_y(0.0)
    , imu_af_z(0.0)
    , imu_wf_x(0.0)
    , imu_wf_y(0.0)
    , imu_wf_z(0.0)
    , imu_dw_x(0.0)
    , imu_dw_y(0.0)
    , imu_dw_z(0.0)
    , rpm_f1(0.0)
    , rpm_f2(0.0)
    , rpm_f3(0.0)
    , rpm_f4(0.0)
    , cmd_rpm1(0.0)
    , cmd_rpm2(0.0)
    , cmd_rpm3(0.0)
    , cmd_rpm4(0.0)
    , ref_thrust1(0.0)
    , ref_thrust2(0.0)
    , ref_thrust3(0.0)
    , ref_thrust4(0.0)
    , des_rpm_ave(0.0)
    , rpm_ave(0.0)
    , des_yaw(0.0)
    , des_yaw_rate(0.0)
    , des_yaw_acc(0.0)
    , thro1(0.0)
    , thro2(0.0)
    , thro3(0.0)
    , thro4(0.0)
    , delta_q_ang(0.0)
    , des_q_ang(0.0)
    , des_F(0.0)
    , indi_F(0.0)
    , hover_percentage(0.0)
    , thr_scale_compensate(0.0)
    , voltage(0.0)
    , ref_v_x(0.0)
    , ref_v_y(0.0)
    , ref_v_z(0.0)
    , ref_a_x(0.0)
    , ref_a_y(0.0)
    , ref_a_z(0.0)
    , ref_j_x(0.0)
    , ref_j_y(0.0)
    , ref_j_z(0.0)
    , ref_s_x(0.0)
    , ref_s_y(0.0)
    , ref_s_z(0.0)
    , x_pos_error(0.0)
    , y_pos_error(0.0)
    , z_pos_error(0.0)
    , x_vel_error(0.0)
    , y_vel_error(0.0)
    , z_vel_error(0.0)
    , ref_thr(0.0)
    , des_thr(0.0)
    , est_thr(0.0)
    , des_torque_x(0.0)
    , des_torque_y(0.0)
    , des_torque_z(0.0)
    , cont_torque_x(0.0)
    , cont_torque_y(0.0)
    , cont_torque_z(0.0)
    , z_jwj(0.0)
    , fbp_thrust1(0.0)
    , fbi_thrust1(0.0)
    , fbp_thrust2(0.0)
    , fbi_thrust2(0.0)
    , fbp_thrust3(0.0)
    , fbi_thrust3(0.0)
    , fbp_thrust4(0.0)
    , fbi_thrust4(0.0)
    , fbp_thrust(0.0)
    , fbi_thrust(0.0)
    , fb_thrust(0.0)
    , rpm_error1(0.0)
    , rpm_error_sum1(0.0)
    , rpm_error2(0.0)
    , rpm_error_sum2(0.0)
    , rpm_error3(0.0)
    , rpm_error_sum3(0.0)
    , rpm_error4(0.0)
    , rpm_error_sum4(0.0)
    , rate_error_z(0.0)
    , rate_error_sum_z(0.0)
    , fbp_bodyacc_z(0.0)
    , fbi_bodyacc_z(0.0)
    , des_est_bodyrates_x(0.0)
    , des_est_bodyrates_y(0.0)
    , des_est_bodyrates_z(0.0)
    , acc_error1(0.0)
    , acc_error2(0.0)
    , acc_error3(0.0)
    , acc_error4(0.0)
    , acc_errorsum1(0.0)
    , acc_errorsum2(0.0)
    , acc_errorsum3(0.0)
    , acc_errorsum4(0.0)
    , window_ave1(0.0)
    , window_ave2(0.0)
    , window_ave3(0.0)
    , window_ave4(0.0)
    , pos_error_all(0.0)
    , pos_error_xy(0.0)
    , pos_error_rmse(0.0)
    , vel_error_all(0.0)
    , des_v_all(0.0)
    , ref_bodyrates_x(0.0)
    , ref_bodyrates_y(0.0)
    , ref_bodyrates_z(0.0)
    , extTotalAccIndi_x(0.0)
    , extTotalAccIndi_y(0.0)
    , extTotalAccIndi_z(0.0)
    , aw_x(0.0)
    , aw_y(0.0)
    , aw_z(0.0)
    , fb_a_x_fil(0.0)
    , fb_a_y_fil(0.0)
    , fb_a_z_fil(0.0)
    , extF_psi(0.0)
    , extF_theta(0.0)
    , des_Fq_psi(0.0)
    , des_Fq_theta(0.0)
    , indi_q_err_ang(0.0)
    , fb_F_x(0.0)
    , fb_F_y(0.0)
    , fb_F_z(0.0)
    , flag(0)
    , indi_acc_q_error_x(0.0)
    , indi_acc_q_error_y(0.0)
    , indi_acc_q_error_z(0.0)
    , F_error(0.0)
    , indi_acc_F_error_x(0.0)
    , indi_acc_F_error_y(0.0)
    , indi_acc_F_error_z(0.0)
    , indiF_x(0.0)
    , indiF_y(0.0)
    , indiF_z(0.0)
    , desFq_x(0.0)
    , desFq_y(0.0)
    , desFq_z(0.0)
    , fb_pv_x(0.0)
    , fb_pv_y(0.0)
    , fb_pv_z(0.0)
    , fb_q_x(0.0)
    , fb_q_y(0.0)
    , fb_q_z(0.0)
    , fb_Fq_x(0.0)
    , fb_Fq_y(0.0)
    , fb_Fq_z(0.0)
    , v_modi_x(0.0)
    , v_modi_y(0.0)
    , v_modi_z(0.0)
    , fb_Fq_error_fil_x(0.0)
    , fb_Fq_error_fil_y(0.0)
    , fb_Fq_error_fil_z(0.0)
    , FUpper(0.0)
    , FLower(0.0)
    , ref_rpm1(0.0)
    , ref_rpm2(0.0)
    , ref_rpm3(0.0)
    , ref_rpm4(0.0)
    , ref_torque_x(0.0)
    , ref_torque_y(0.0)
    , ref_torque_z(0.0)
    , indi_F_Limit(0.0)  {
    }
  Px4ctrlDebug_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , fb_a_x(0.0)
    , fb_a_y(0.0)
    , fb_a_z(0.0)
    , des_p_x(0.0)
    , des_p_y(0.0)
    , des_p_z(0.0)
    , des_v_x(0.0)
    , des_v_y(0.0)
    , des_v_z(0.0)
    , des_a_x(0.0)
    , des_a_y(0.0)
    , des_a_z(0.0)
    , des_q_x(0.0)
    , des_q_y(0.0)
    , des_q_z(0.0)
    , des_q_w(0.0)
    , est_r(0.0)
    , est_p(0.0)
    , est_y(0.0)
    , ref_r(0.0)
    , ref_p(0.0)
    , ref_y(0.0)
    , des_r(0.0)
    , des_p(0.0)
    , des_y(0.0)
    , exec_err_axisang_x(0.0)
    , exec_err_axisang_y(0.0)
    , exec_err_axisang_z(0.0)
    , exec_err_axisang_ang(0.0)
    , fb_axisang_x(0.0)
    , fb_axisang_y(0.0)
    , fb_axisang_z(0.0)
    , fb_axisang_ang(0.0)
    , fb_rate_x(0.0)
    , fb_rate_y(0.0)
    , fb_rate_z(0.0)
    , des_bodyrates_x(0.0)
    , des_bodyrates_y(0.0)
    , des_bodyrates_z(0.0)
    , des_bodyaccs_x(0.0)
    , des_bodyaccs_y(0.0)
    , des_bodyaccs_z(0.0)
    , imu_af_x(0.0)
    , imu_af_y(0.0)
    , imu_af_z(0.0)
    , imu_wf_x(0.0)
    , imu_wf_y(0.0)
    , imu_wf_z(0.0)
    , imu_dw_x(0.0)
    , imu_dw_y(0.0)
    , imu_dw_z(0.0)
    , rpm_f1(0.0)
    , rpm_f2(0.0)
    , rpm_f3(0.0)
    , rpm_f4(0.0)
    , cmd_rpm1(0.0)
    , cmd_rpm2(0.0)
    , cmd_rpm3(0.0)
    , cmd_rpm4(0.0)
    , ref_thrust1(0.0)
    , ref_thrust2(0.0)
    , ref_thrust3(0.0)
    , ref_thrust4(0.0)
    , des_rpm_ave(0.0)
    , rpm_ave(0.0)
    , des_yaw(0.0)
    , des_yaw_rate(0.0)
    , des_yaw_acc(0.0)
    , thro1(0.0)
    , thro2(0.0)
    , thro3(0.0)
    , thro4(0.0)
    , delta_q_ang(0.0)
    , des_q_ang(0.0)
    , des_F(0.0)
    , indi_F(0.0)
    , hover_percentage(0.0)
    , thr_scale_compensate(0.0)
    , voltage(0.0)
    , ref_v_x(0.0)
    , ref_v_y(0.0)
    , ref_v_z(0.0)
    , ref_a_x(0.0)
    , ref_a_y(0.0)
    , ref_a_z(0.0)
    , ref_j_x(0.0)
    , ref_j_y(0.0)
    , ref_j_z(0.0)
    , ref_s_x(0.0)
    , ref_s_y(0.0)
    , ref_s_z(0.0)
    , x_pos_error(0.0)
    , y_pos_error(0.0)
    , z_pos_error(0.0)
    , x_vel_error(0.0)
    , y_vel_error(0.0)
    , z_vel_error(0.0)
    , ref_thr(0.0)
    , des_thr(0.0)
    , est_thr(0.0)
    , des_torque_x(0.0)
    , des_torque_y(0.0)
    , des_torque_z(0.0)
    , cont_torque_x(0.0)
    , cont_torque_y(0.0)
    , cont_torque_z(0.0)
    , z_jwj(0.0)
    , fbp_thrust1(0.0)
    , fbi_thrust1(0.0)
    , fbp_thrust2(0.0)
    , fbi_thrust2(0.0)
    , fbp_thrust3(0.0)
    , fbi_thrust3(0.0)
    , fbp_thrust4(0.0)
    , fbi_thrust4(0.0)
    , fbp_thrust(0.0)
    , fbi_thrust(0.0)
    , fb_thrust(0.0)
    , rpm_error1(0.0)
    , rpm_error_sum1(0.0)
    , rpm_error2(0.0)
    , rpm_error_sum2(0.0)
    , rpm_error3(0.0)
    , rpm_error_sum3(0.0)
    , rpm_error4(0.0)
    , rpm_error_sum4(0.0)
    , rate_error_z(0.0)
    , rate_error_sum_z(0.0)
    , fbp_bodyacc_z(0.0)
    , fbi_bodyacc_z(0.0)
    , des_est_bodyrates_x(0.0)
    , des_est_bodyrates_y(0.0)
    , des_est_bodyrates_z(0.0)
    , acc_error1(0.0)
    , acc_error2(0.0)
    , acc_error3(0.0)
    , acc_error4(0.0)
    , acc_errorsum1(0.0)
    , acc_errorsum2(0.0)
    , acc_errorsum3(0.0)
    , acc_errorsum4(0.0)
    , window_ave1(0.0)
    , window_ave2(0.0)
    , window_ave3(0.0)
    , window_ave4(0.0)
    , pos_error_all(0.0)
    , pos_error_xy(0.0)
    , pos_error_rmse(0.0)
    , vel_error_all(0.0)
    , des_v_all(0.0)
    , ref_bodyrates_x(0.0)
    , ref_bodyrates_y(0.0)
    , ref_bodyrates_z(0.0)
    , extTotalAccIndi_x(0.0)
    , extTotalAccIndi_y(0.0)
    , extTotalAccIndi_z(0.0)
    , aw_x(0.0)
    , aw_y(0.0)
    , aw_z(0.0)
    , fb_a_x_fil(0.0)
    , fb_a_y_fil(0.0)
    , fb_a_z_fil(0.0)
    , extF_psi(0.0)
    , extF_theta(0.0)
    , des_Fq_psi(0.0)
    , des_Fq_theta(0.0)
    , indi_q_err_ang(0.0)
    , fb_F_x(0.0)
    , fb_F_y(0.0)
    , fb_F_z(0.0)
    , flag(0)
    , indi_acc_q_error_x(0.0)
    , indi_acc_q_error_y(0.0)
    , indi_acc_q_error_z(0.0)
    , F_error(0.0)
    , indi_acc_F_error_x(0.0)
    , indi_acc_F_error_y(0.0)
    , indi_acc_F_error_z(0.0)
    , indiF_x(0.0)
    , indiF_y(0.0)
    , indiF_z(0.0)
    , desFq_x(0.0)
    , desFq_y(0.0)
    , desFq_z(0.0)
    , fb_pv_x(0.0)
    , fb_pv_y(0.0)
    , fb_pv_z(0.0)
    , fb_q_x(0.0)
    , fb_q_y(0.0)
    , fb_q_z(0.0)
    , fb_Fq_x(0.0)
    , fb_Fq_y(0.0)
    , fb_Fq_z(0.0)
    , v_modi_x(0.0)
    , v_modi_y(0.0)
    , v_modi_z(0.0)
    , fb_Fq_error_fil_x(0.0)
    , fb_Fq_error_fil_y(0.0)
    , fb_Fq_error_fil_z(0.0)
    , FUpper(0.0)
    , FLower(0.0)
    , ref_rpm1(0.0)
    , ref_rpm2(0.0)
    , ref_rpm3(0.0)
    , ref_rpm4(0.0)
    , ref_torque_x(0.0)
    , ref_torque_y(0.0)
    , ref_torque_z(0.0)
    , indi_F_Limit(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _fb_a_x_type;
  _fb_a_x_type fb_a_x;

   typedef double _fb_a_y_type;
  _fb_a_y_type fb_a_y;

   typedef double _fb_a_z_type;
  _fb_a_z_type fb_a_z;

   typedef double _des_p_x_type;
  _des_p_x_type des_p_x;

   typedef double _des_p_y_type;
  _des_p_y_type des_p_y;

   typedef double _des_p_z_type;
  _des_p_z_type des_p_z;

   typedef double _des_v_x_type;
  _des_v_x_type des_v_x;

   typedef double _des_v_y_type;
  _des_v_y_type des_v_y;

   typedef double _des_v_z_type;
  _des_v_z_type des_v_z;

   typedef double _des_a_x_type;
  _des_a_x_type des_a_x;

   typedef double _des_a_y_type;
  _des_a_y_type des_a_y;

   typedef double _des_a_z_type;
  _des_a_z_type des_a_z;

   typedef double _des_q_x_type;
  _des_q_x_type des_q_x;

   typedef double _des_q_y_type;
  _des_q_y_type des_q_y;

   typedef double _des_q_z_type;
  _des_q_z_type des_q_z;

   typedef double _des_q_w_type;
  _des_q_w_type des_q_w;

   typedef double _est_r_type;
  _est_r_type est_r;

   typedef double _est_p_type;
  _est_p_type est_p;

   typedef double _est_y_type;
  _est_y_type est_y;

   typedef double _ref_r_type;
  _ref_r_type ref_r;

   typedef double _ref_p_type;
  _ref_p_type ref_p;

   typedef double _ref_y_type;
  _ref_y_type ref_y;

   typedef double _des_r_type;
  _des_r_type des_r;

   typedef double _des_p_type;
  _des_p_type des_p;

   typedef double _des_y_type;
  _des_y_type des_y;

   typedef double _exec_err_axisang_x_type;
  _exec_err_axisang_x_type exec_err_axisang_x;

   typedef double _exec_err_axisang_y_type;
  _exec_err_axisang_y_type exec_err_axisang_y;

   typedef double _exec_err_axisang_z_type;
  _exec_err_axisang_z_type exec_err_axisang_z;

   typedef double _exec_err_axisang_ang_type;
  _exec_err_axisang_ang_type exec_err_axisang_ang;

   typedef double _fb_axisang_x_type;
  _fb_axisang_x_type fb_axisang_x;

   typedef double _fb_axisang_y_type;
  _fb_axisang_y_type fb_axisang_y;

   typedef double _fb_axisang_z_type;
  _fb_axisang_z_type fb_axisang_z;

   typedef double _fb_axisang_ang_type;
  _fb_axisang_ang_type fb_axisang_ang;

   typedef double _fb_rate_x_type;
  _fb_rate_x_type fb_rate_x;

   typedef double _fb_rate_y_type;
  _fb_rate_y_type fb_rate_y;

   typedef double _fb_rate_z_type;
  _fb_rate_z_type fb_rate_z;

   typedef double _des_bodyrates_x_type;
  _des_bodyrates_x_type des_bodyrates_x;

   typedef double _des_bodyrates_y_type;
  _des_bodyrates_y_type des_bodyrates_y;

   typedef double _des_bodyrates_z_type;
  _des_bodyrates_z_type des_bodyrates_z;

   typedef double _des_bodyaccs_x_type;
  _des_bodyaccs_x_type des_bodyaccs_x;

   typedef double _des_bodyaccs_y_type;
  _des_bodyaccs_y_type des_bodyaccs_y;

   typedef double _des_bodyaccs_z_type;
  _des_bodyaccs_z_type des_bodyaccs_z;

   typedef double _imu_af_x_type;
  _imu_af_x_type imu_af_x;

   typedef double _imu_af_y_type;
  _imu_af_y_type imu_af_y;

   typedef double _imu_af_z_type;
  _imu_af_z_type imu_af_z;

   typedef double _imu_wf_x_type;
  _imu_wf_x_type imu_wf_x;

   typedef double _imu_wf_y_type;
  _imu_wf_y_type imu_wf_y;

   typedef double _imu_wf_z_type;
  _imu_wf_z_type imu_wf_z;

   typedef double _imu_dw_x_type;
  _imu_dw_x_type imu_dw_x;

   typedef double _imu_dw_y_type;
  _imu_dw_y_type imu_dw_y;

   typedef double _imu_dw_z_type;
  _imu_dw_z_type imu_dw_z;

   typedef double _rpm_f1_type;
  _rpm_f1_type rpm_f1;

   typedef double _rpm_f2_type;
  _rpm_f2_type rpm_f2;

   typedef double _rpm_f3_type;
  _rpm_f3_type rpm_f3;

   typedef double _rpm_f4_type;
  _rpm_f4_type rpm_f4;

   typedef double _cmd_rpm1_type;
  _cmd_rpm1_type cmd_rpm1;

   typedef double _cmd_rpm2_type;
  _cmd_rpm2_type cmd_rpm2;

   typedef double _cmd_rpm3_type;
  _cmd_rpm3_type cmd_rpm3;

   typedef double _cmd_rpm4_type;
  _cmd_rpm4_type cmd_rpm4;

   typedef double _ref_thrust1_type;
  _ref_thrust1_type ref_thrust1;

   typedef double _ref_thrust2_type;
  _ref_thrust2_type ref_thrust2;

   typedef double _ref_thrust3_type;
  _ref_thrust3_type ref_thrust3;

   typedef double _ref_thrust4_type;
  _ref_thrust4_type ref_thrust4;

   typedef double _des_rpm_ave_type;
  _des_rpm_ave_type des_rpm_ave;

   typedef double _rpm_ave_type;
  _rpm_ave_type rpm_ave;

   typedef double _des_yaw_type;
  _des_yaw_type des_yaw;

   typedef double _des_yaw_rate_type;
  _des_yaw_rate_type des_yaw_rate;

   typedef double _des_yaw_acc_type;
  _des_yaw_acc_type des_yaw_acc;

   typedef double _thro1_type;
  _thro1_type thro1;

   typedef double _thro2_type;
  _thro2_type thro2;

   typedef double _thro3_type;
  _thro3_type thro3;

   typedef double _thro4_type;
  _thro4_type thro4;

   typedef double _delta_q_ang_type;
  _delta_q_ang_type delta_q_ang;

   typedef double _des_q_ang_type;
  _des_q_ang_type des_q_ang;

   typedef double _des_F_type;
  _des_F_type des_F;

   typedef double _indi_F_type;
  _indi_F_type indi_F;

   typedef double _hover_percentage_type;
  _hover_percentage_type hover_percentage;

   typedef double _thr_scale_compensate_type;
  _thr_scale_compensate_type thr_scale_compensate;

   typedef double _voltage_type;
  _voltage_type voltage;

   typedef double _ref_v_x_type;
  _ref_v_x_type ref_v_x;

   typedef double _ref_v_y_type;
  _ref_v_y_type ref_v_y;

   typedef double _ref_v_z_type;
  _ref_v_z_type ref_v_z;

   typedef double _ref_a_x_type;
  _ref_a_x_type ref_a_x;

   typedef double _ref_a_y_type;
  _ref_a_y_type ref_a_y;

   typedef double _ref_a_z_type;
  _ref_a_z_type ref_a_z;

   typedef double _ref_j_x_type;
  _ref_j_x_type ref_j_x;

   typedef double _ref_j_y_type;
  _ref_j_y_type ref_j_y;

   typedef double _ref_j_z_type;
  _ref_j_z_type ref_j_z;

   typedef double _ref_s_x_type;
  _ref_s_x_type ref_s_x;

   typedef double _ref_s_y_type;
  _ref_s_y_type ref_s_y;

   typedef double _ref_s_z_type;
  _ref_s_z_type ref_s_z;

   typedef double _x_pos_error_type;
  _x_pos_error_type x_pos_error;

   typedef double _y_pos_error_type;
  _y_pos_error_type y_pos_error;

   typedef double _z_pos_error_type;
  _z_pos_error_type z_pos_error;

   typedef double _x_vel_error_type;
  _x_vel_error_type x_vel_error;

   typedef double _y_vel_error_type;
  _y_vel_error_type y_vel_error;

   typedef double _z_vel_error_type;
  _z_vel_error_type z_vel_error;

   typedef double _ref_thr_type;
  _ref_thr_type ref_thr;

   typedef double _des_thr_type;
  _des_thr_type des_thr;

   typedef double _est_thr_type;
  _est_thr_type est_thr;

   typedef double _des_torque_x_type;
  _des_torque_x_type des_torque_x;

   typedef double _des_torque_y_type;
  _des_torque_y_type des_torque_y;

   typedef double _des_torque_z_type;
  _des_torque_z_type des_torque_z;

   typedef double _cont_torque_x_type;
  _cont_torque_x_type cont_torque_x;

   typedef double _cont_torque_y_type;
  _cont_torque_y_type cont_torque_y;

   typedef double _cont_torque_z_type;
  _cont_torque_z_type cont_torque_z;

   typedef double _z_jwj_type;
  _z_jwj_type z_jwj;

   typedef double _fbp_thrust1_type;
  _fbp_thrust1_type fbp_thrust1;

   typedef double _fbi_thrust1_type;
  _fbi_thrust1_type fbi_thrust1;

   typedef double _fbp_thrust2_type;
  _fbp_thrust2_type fbp_thrust2;

   typedef double _fbi_thrust2_type;
  _fbi_thrust2_type fbi_thrust2;

   typedef double _fbp_thrust3_type;
  _fbp_thrust3_type fbp_thrust3;

   typedef double _fbi_thrust3_type;
  _fbi_thrust3_type fbi_thrust3;

   typedef double _fbp_thrust4_type;
  _fbp_thrust4_type fbp_thrust4;

   typedef double _fbi_thrust4_type;
  _fbi_thrust4_type fbi_thrust4;

   typedef double _fbp_thrust_type;
  _fbp_thrust_type fbp_thrust;

   typedef double _fbi_thrust_type;
  _fbi_thrust_type fbi_thrust;

   typedef double _fb_thrust_type;
  _fb_thrust_type fb_thrust;

   typedef double _rpm_error1_type;
  _rpm_error1_type rpm_error1;

   typedef double _rpm_error_sum1_type;
  _rpm_error_sum1_type rpm_error_sum1;

   typedef double _rpm_error2_type;
  _rpm_error2_type rpm_error2;

   typedef double _rpm_error_sum2_type;
  _rpm_error_sum2_type rpm_error_sum2;

   typedef double _rpm_error3_type;
  _rpm_error3_type rpm_error3;

   typedef double _rpm_error_sum3_type;
  _rpm_error_sum3_type rpm_error_sum3;

   typedef double _rpm_error4_type;
  _rpm_error4_type rpm_error4;

   typedef double _rpm_error_sum4_type;
  _rpm_error_sum4_type rpm_error_sum4;

   typedef double _rate_error_z_type;
  _rate_error_z_type rate_error_z;

   typedef double _rate_error_sum_z_type;
  _rate_error_sum_z_type rate_error_sum_z;

   typedef double _fbp_bodyacc_z_type;
  _fbp_bodyacc_z_type fbp_bodyacc_z;

   typedef double _fbi_bodyacc_z_type;
  _fbi_bodyacc_z_type fbi_bodyacc_z;

   typedef double _des_est_bodyrates_x_type;
  _des_est_bodyrates_x_type des_est_bodyrates_x;

   typedef double _des_est_bodyrates_y_type;
  _des_est_bodyrates_y_type des_est_bodyrates_y;

   typedef double _des_est_bodyrates_z_type;
  _des_est_bodyrates_z_type des_est_bodyrates_z;

   typedef double _acc_error1_type;
  _acc_error1_type acc_error1;

   typedef double _acc_error2_type;
  _acc_error2_type acc_error2;

   typedef double _acc_error3_type;
  _acc_error3_type acc_error3;

   typedef double _acc_error4_type;
  _acc_error4_type acc_error4;

   typedef double _acc_errorsum1_type;
  _acc_errorsum1_type acc_errorsum1;

   typedef double _acc_errorsum2_type;
  _acc_errorsum2_type acc_errorsum2;

   typedef double _acc_errorsum3_type;
  _acc_errorsum3_type acc_errorsum3;

   typedef double _acc_errorsum4_type;
  _acc_errorsum4_type acc_errorsum4;

   typedef double _window_ave1_type;
  _window_ave1_type window_ave1;

   typedef double _window_ave2_type;
  _window_ave2_type window_ave2;

   typedef double _window_ave3_type;
  _window_ave3_type window_ave3;

   typedef double _window_ave4_type;
  _window_ave4_type window_ave4;

   typedef double _pos_error_all_type;
  _pos_error_all_type pos_error_all;

   typedef double _pos_error_xy_type;
  _pos_error_xy_type pos_error_xy;

   typedef double _pos_error_rmse_type;
  _pos_error_rmse_type pos_error_rmse;

   typedef double _vel_error_all_type;
  _vel_error_all_type vel_error_all;

   typedef double _des_v_all_type;
  _des_v_all_type des_v_all;

   typedef double _ref_bodyrates_x_type;
  _ref_bodyrates_x_type ref_bodyrates_x;

   typedef double _ref_bodyrates_y_type;
  _ref_bodyrates_y_type ref_bodyrates_y;

   typedef double _ref_bodyrates_z_type;
  _ref_bodyrates_z_type ref_bodyrates_z;

   typedef double _extTotalAccIndi_x_type;
  _extTotalAccIndi_x_type extTotalAccIndi_x;

   typedef double _extTotalAccIndi_y_type;
  _extTotalAccIndi_y_type extTotalAccIndi_y;

   typedef double _extTotalAccIndi_z_type;
  _extTotalAccIndi_z_type extTotalAccIndi_z;

   typedef double _aw_x_type;
  _aw_x_type aw_x;

   typedef double _aw_y_type;
  _aw_y_type aw_y;

   typedef double _aw_z_type;
  _aw_z_type aw_z;

   typedef double _fb_a_x_fil_type;
  _fb_a_x_fil_type fb_a_x_fil;

   typedef double _fb_a_y_fil_type;
  _fb_a_y_fil_type fb_a_y_fil;

   typedef double _fb_a_z_fil_type;
  _fb_a_z_fil_type fb_a_z_fil;

   typedef double _extF_psi_type;
  _extF_psi_type extF_psi;

   typedef double _extF_theta_type;
  _extF_theta_type extF_theta;

   typedef double _des_Fq_psi_type;
  _des_Fq_psi_type des_Fq_psi;

   typedef double _des_Fq_theta_type;
  _des_Fq_theta_type des_Fq_theta;

   typedef double _indi_q_err_ang_type;
  _indi_q_err_ang_type indi_q_err_ang;

   typedef double _fb_F_x_type;
  _fb_F_x_type fb_F_x;

   typedef double _fb_F_y_type;
  _fb_F_y_type fb_F_y;

   typedef double _fb_F_z_type;
  _fb_F_z_type fb_F_z;

   typedef uint8_t _flag_type;
  _flag_type flag;

   typedef double _indi_acc_q_error_x_type;
  _indi_acc_q_error_x_type indi_acc_q_error_x;

   typedef double _indi_acc_q_error_y_type;
  _indi_acc_q_error_y_type indi_acc_q_error_y;

   typedef double _indi_acc_q_error_z_type;
  _indi_acc_q_error_z_type indi_acc_q_error_z;

   typedef double _F_error_type;
  _F_error_type F_error;

   typedef double _indi_acc_F_error_x_type;
  _indi_acc_F_error_x_type indi_acc_F_error_x;

   typedef double _indi_acc_F_error_y_type;
  _indi_acc_F_error_y_type indi_acc_F_error_y;

   typedef double _indi_acc_F_error_z_type;
  _indi_acc_F_error_z_type indi_acc_F_error_z;

   typedef double _indiF_x_type;
  _indiF_x_type indiF_x;

   typedef double _indiF_y_type;
  _indiF_y_type indiF_y;

   typedef double _indiF_z_type;
  _indiF_z_type indiF_z;

   typedef double _desFq_x_type;
  _desFq_x_type desFq_x;

   typedef double _desFq_y_type;
  _desFq_y_type desFq_y;

   typedef double _desFq_z_type;
  _desFq_z_type desFq_z;

   typedef double _fb_pv_x_type;
  _fb_pv_x_type fb_pv_x;

   typedef double _fb_pv_y_type;
  _fb_pv_y_type fb_pv_y;

   typedef double _fb_pv_z_type;
  _fb_pv_z_type fb_pv_z;

   typedef double _fb_q_x_type;
  _fb_q_x_type fb_q_x;

   typedef double _fb_q_y_type;
  _fb_q_y_type fb_q_y;

   typedef double _fb_q_z_type;
  _fb_q_z_type fb_q_z;

   typedef double _fb_Fq_x_type;
  _fb_Fq_x_type fb_Fq_x;

   typedef double _fb_Fq_y_type;
  _fb_Fq_y_type fb_Fq_y;

   typedef double _fb_Fq_z_type;
  _fb_Fq_z_type fb_Fq_z;

   typedef double _v_modi_x_type;
  _v_modi_x_type v_modi_x;

   typedef double _v_modi_y_type;
  _v_modi_y_type v_modi_y;

   typedef double _v_modi_z_type;
  _v_modi_z_type v_modi_z;

   typedef double _fb_Fq_error_fil_x_type;
  _fb_Fq_error_fil_x_type fb_Fq_error_fil_x;

   typedef double _fb_Fq_error_fil_y_type;
  _fb_Fq_error_fil_y_type fb_Fq_error_fil_y;

   typedef double _fb_Fq_error_fil_z_type;
  _fb_Fq_error_fil_z_type fb_Fq_error_fil_z;

   typedef double _FUpper_type;
  _FUpper_type FUpper;

   typedef double _FLower_type;
  _FLower_type FLower;

   typedef double _ref_rpm1_type;
  _ref_rpm1_type ref_rpm1;

   typedef double _ref_rpm2_type;
  _ref_rpm2_type ref_rpm2;

   typedef double _ref_rpm3_type;
  _ref_rpm3_type ref_rpm3;

   typedef double _ref_rpm4_type;
  _ref_rpm4_type ref_rpm4;

   typedef double _ref_torque_x_type;
  _ref_torque_x_type ref_torque_x;

   typedef double _ref_torque_y_type;
  _ref_torque_y_type ref_torque_y;

   typedef double _ref_torque_z_type;
  _ref_torque_z_type ref_torque_z;

   typedef double _indi_F_Limit_type;
  _indi_F_Limit_type indi_F_Limit;





  typedef boost::shared_ptr< ::quadrotor_msgs::Px4ctrlDebug_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotor_msgs::Px4ctrlDebug_<ContainerAllocator> const> ConstPtr;

}; // struct Px4ctrlDebug_

typedef ::quadrotor_msgs::Px4ctrlDebug_<std::allocator<void> > Px4ctrlDebug;

typedef boost::shared_ptr< ::quadrotor_msgs::Px4ctrlDebug > Px4ctrlDebugPtr;
typedef boost::shared_ptr< ::quadrotor_msgs::Px4ctrlDebug const> Px4ctrlDebugConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quadrotor_msgs::Px4ctrlDebug_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quadrotor_msgs::Px4ctrlDebug_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quadrotor_msgs::Px4ctrlDebug_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::Px4ctrlDebug_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.fb_a_x == rhs.fb_a_x &&
    lhs.fb_a_y == rhs.fb_a_y &&
    lhs.fb_a_z == rhs.fb_a_z &&
    lhs.des_p_x == rhs.des_p_x &&
    lhs.des_p_y == rhs.des_p_y &&
    lhs.des_p_z == rhs.des_p_z &&
    lhs.des_v_x == rhs.des_v_x &&
    lhs.des_v_y == rhs.des_v_y &&
    lhs.des_v_z == rhs.des_v_z &&
    lhs.des_a_x == rhs.des_a_x &&
    lhs.des_a_y == rhs.des_a_y &&
    lhs.des_a_z == rhs.des_a_z &&
    lhs.des_q_x == rhs.des_q_x &&
    lhs.des_q_y == rhs.des_q_y &&
    lhs.des_q_z == rhs.des_q_z &&
    lhs.des_q_w == rhs.des_q_w &&
    lhs.est_r == rhs.est_r &&
    lhs.est_p == rhs.est_p &&
    lhs.est_y == rhs.est_y &&
    lhs.ref_r == rhs.ref_r &&
    lhs.ref_p == rhs.ref_p &&
    lhs.ref_y == rhs.ref_y &&
    lhs.des_r == rhs.des_r &&
    lhs.des_p == rhs.des_p &&
    lhs.des_y == rhs.des_y &&
    lhs.exec_err_axisang_x == rhs.exec_err_axisang_x &&
    lhs.exec_err_axisang_y == rhs.exec_err_axisang_y &&
    lhs.exec_err_axisang_z == rhs.exec_err_axisang_z &&
    lhs.exec_err_axisang_ang == rhs.exec_err_axisang_ang &&
    lhs.fb_axisang_x == rhs.fb_axisang_x &&
    lhs.fb_axisang_y == rhs.fb_axisang_y &&
    lhs.fb_axisang_z == rhs.fb_axisang_z &&
    lhs.fb_axisang_ang == rhs.fb_axisang_ang &&
    lhs.fb_rate_x == rhs.fb_rate_x &&
    lhs.fb_rate_y == rhs.fb_rate_y &&
    lhs.fb_rate_z == rhs.fb_rate_z &&
    lhs.des_bodyrates_x == rhs.des_bodyrates_x &&
    lhs.des_bodyrates_y == rhs.des_bodyrates_y &&
    lhs.des_bodyrates_z == rhs.des_bodyrates_z &&
    lhs.des_bodyaccs_x == rhs.des_bodyaccs_x &&
    lhs.des_bodyaccs_y == rhs.des_bodyaccs_y &&
    lhs.des_bodyaccs_z == rhs.des_bodyaccs_z &&
    lhs.imu_af_x == rhs.imu_af_x &&
    lhs.imu_af_y == rhs.imu_af_y &&
    lhs.imu_af_z == rhs.imu_af_z &&
    lhs.imu_wf_x == rhs.imu_wf_x &&
    lhs.imu_wf_y == rhs.imu_wf_y &&
    lhs.imu_wf_z == rhs.imu_wf_z &&
    lhs.imu_dw_x == rhs.imu_dw_x &&
    lhs.imu_dw_y == rhs.imu_dw_y &&
    lhs.imu_dw_z == rhs.imu_dw_z &&
    lhs.rpm_f1 == rhs.rpm_f1 &&
    lhs.rpm_f2 == rhs.rpm_f2 &&
    lhs.rpm_f3 == rhs.rpm_f3 &&
    lhs.rpm_f4 == rhs.rpm_f4 &&
    lhs.cmd_rpm1 == rhs.cmd_rpm1 &&
    lhs.cmd_rpm2 == rhs.cmd_rpm2 &&
    lhs.cmd_rpm3 == rhs.cmd_rpm3 &&
    lhs.cmd_rpm4 == rhs.cmd_rpm4 &&
    lhs.ref_thrust1 == rhs.ref_thrust1 &&
    lhs.ref_thrust2 == rhs.ref_thrust2 &&
    lhs.ref_thrust3 == rhs.ref_thrust3 &&
    lhs.ref_thrust4 == rhs.ref_thrust4 &&
    lhs.des_rpm_ave == rhs.des_rpm_ave &&
    lhs.rpm_ave == rhs.rpm_ave &&
    lhs.des_yaw == rhs.des_yaw &&
    lhs.des_yaw_rate == rhs.des_yaw_rate &&
    lhs.des_yaw_acc == rhs.des_yaw_acc &&
    lhs.thro1 == rhs.thro1 &&
    lhs.thro2 == rhs.thro2 &&
    lhs.thro3 == rhs.thro3 &&
    lhs.thro4 == rhs.thro4 &&
    lhs.delta_q_ang == rhs.delta_q_ang &&
    lhs.des_q_ang == rhs.des_q_ang &&
    lhs.des_F == rhs.des_F &&
    lhs.indi_F == rhs.indi_F &&
    lhs.hover_percentage == rhs.hover_percentage &&
    lhs.thr_scale_compensate == rhs.thr_scale_compensate &&
    lhs.voltage == rhs.voltage &&
    lhs.ref_v_x == rhs.ref_v_x &&
    lhs.ref_v_y == rhs.ref_v_y &&
    lhs.ref_v_z == rhs.ref_v_z &&
    lhs.ref_a_x == rhs.ref_a_x &&
    lhs.ref_a_y == rhs.ref_a_y &&
    lhs.ref_a_z == rhs.ref_a_z &&
    lhs.ref_j_x == rhs.ref_j_x &&
    lhs.ref_j_y == rhs.ref_j_y &&
    lhs.ref_j_z == rhs.ref_j_z &&
    lhs.ref_s_x == rhs.ref_s_x &&
    lhs.ref_s_y == rhs.ref_s_y &&
    lhs.ref_s_z == rhs.ref_s_z &&
    lhs.x_pos_error == rhs.x_pos_error &&
    lhs.y_pos_error == rhs.y_pos_error &&
    lhs.z_pos_error == rhs.z_pos_error &&
    lhs.x_vel_error == rhs.x_vel_error &&
    lhs.y_vel_error == rhs.y_vel_error &&
    lhs.z_vel_error == rhs.z_vel_error &&
    lhs.ref_thr == rhs.ref_thr &&
    lhs.des_thr == rhs.des_thr &&
    lhs.est_thr == rhs.est_thr &&
    lhs.des_torque_x == rhs.des_torque_x &&
    lhs.des_torque_y == rhs.des_torque_y &&
    lhs.des_torque_z == rhs.des_torque_z &&
    lhs.cont_torque_x == rhs.cont_torque_x &&
    lhs.cont_torque_y == rhs.cont_torque_y &&
    lhs.cont_torque_z == rhs.cont_torque_z &&
    lhs.z_jwj == rhs.z_jwj &&
    lhs.fbp_thrust1 == rhs.fbp_thrust1 &&
    lhs.fbi_thrust1 == rhs.fbi_thrust1 &&
    lhs.fbp_thrust2 == rhs.fbp_thrust2 &&
    lhs.fbi_thrust2 == rhs.fbi_thrust2 &&
    lhs.fbp_thrust3 == rhs.fbp_thrust3 &&
    lhs.fbi_thrust3 == rhs.fbi_thrust3 &&
    lhs.fbp_thrust4 == rhs.fbp_thrust4 &&
    lhs.fbi_thrust4 == rhs.fbi_thrust4 &&
    lhs.fbp_thrust == rhs.fbp_thrust &&
    lhs.fbi_thrust == rhs.fbi_thrust &&
    lhs.fb_thrust == rhs.fb_thrust &&
    lhs.rpm_error1 == rhs.rpm_error1 &&
    lhs.rpm_error_sum1 == rhs.rpm_error_sum1 &&
    lhs.rpm_error2 == rhs.rpm_error2 &&
    lhs.rpm_error_sum2 == rhs.rpm_error_sum2 &&
    lhs.rpm_error3 == rhs.rpm_error3 &&
    lhs.rpm_error_sum3 == rhs.rpm_error_sum3 &&
    lhs.rpm_error4 == rhs.rpm_error4 &&
    lhs.rpm_error_sum4 == rhs.rpm_error_sum4 &&
    lhs.rate_error_z == rhs.rate_error_z &&
    lhs.rate_error_sum_z == rhs.rate_error_sum_z &&
    lhs.fbp_bodyacc_z == rhs.fbp_bodyacc_z &&
    lhs.fbi_bodyacc_z == rhs.fbi_bodyacc_z &&
    lhs.des_est_bodyrates_x == rhs.des_est_bodyrates_x &&
    lhs.des_est_bodyrates_y == rhs.des_est_bodyrates_y &&
    lhs.des_est_bodyrates_z == rhs.des_est_bodyrates_z &&
    lhs.acc_error1 == rhs.acc_error1 &&
    lhs.acc_error2 == rhs.acc_error2 &&
    lhs.acc_error3 == rhs.acc_error3 &&
    lhs.acc_error4 == rhs.acc_error4 &&
    lhs.acc_errorsum1 == rhs.acc_errorsum1 &&
    lhs.acc_errorsum2 == rhs.acc_errorsum2 &&
    lhs.acc_errorsum3 == rhs.acc_errorsum3 &&
    lhs.acc_errorsum4 == rhs.acc_errorsum4 &&
    lhs.window_ave1 == rhs.window_ave1 &&
    lhs.window_ave2 == rhs.window_ave2 &&
    lhs.window_ave3 == rhs.window_ave3 &&
    lhs.window_ave4 == rhs.window_ave4 &&
    lhs.pos_error_all == rhs.pos_error_all &&
    lhs.pos_error_xy == rhs.pos_error_xy &&
    lhs.pos_error_rmse == rhs.pos_error_rmse &&
    lhs.vel_error_all == rhs.vel_error_all &&
    lhs.des_v_all == rhs.des_v_all &&
    lhs.ref_bodyrates_x == rhs.ref_bodyrates_x &&
    lhs.ref_bodyrates_y == rhs.ref_bodyrates_y &&
    lhs.ref_bodyrates_z == rhs.ref_bodyrates_z &&
    lhs.extTotalAccIndi_x == rhs.extTotalAccIndi_x &&
    lhs.extTotalAccIndi_y == rhs.extTotalAccIndi_y &&
    lhs.extTotalAccIndi_z == rhs.extTotalAccIndi_z &&
    lhs.aw_x == rhs.aw_x &&
    lhs.aw_y == rhs.aw_y &&
    lhs.aw_z == rhs.aw_z &&
    lhs.fb_a_x_fil == rhs.fb_a_x_fil &&
    lhs.fb_a_y_fil == rhs.fb_a_y_fil &&
    lhs.fb_a_z_fil == rhs.fb_a_z_fil &&
    lhs.extF_psi == rhs.extF_psi &&
    lhs.extF_theta == rhs.extF_theta &&
    lhs.des_Fq_psi == rhs.des_Fq_psi &&
    lhs.des_Fq_theta == rhs.des_Fq_theta &&
    lhs.indi_q_err_ang == rhs.indi_q_err_ang &&
    lhs.fb_F_x == rhs.fb_F_x &&
    lhs.fb_F_y == rhs.fb_F_y &&
    lhs.fb_F_z == rhs.fb_F_z &&
    lhs.flag == rhs.flag &&
    lhs.indi_acc_q_error_x == rhs.indi_acc_q_error_x &&
    lhs.indi_acc_q_error_y == rhs.indi_acc_q_error_y &&
    lhs.indi_acc_q_error_z == rhs.indi_acc_q_error_z &&
    lhs.F_error == rhs.F_error &&
    lhs.indi_acc_F_error_x == rhs.indi_acc_F_error_x &&
    lhs.indi_acc_F_error_y == rhs.indi_acc_F_error_y &&
    lhs.indi_acc_F_error_z == rhs.indi_acc_F_error_z &&
    lhs.indiF_x == rhs.indiF_x &&
    lhs.indiF_y == rhs.indiF_y &&
    lhs.indiF_z == rhs.indiF_z &&
    lhs.desFq_x == rhs.desFq_x &&
    lhs.desFq_y == rhs.desFq_y &&
    lhs.desFq_z == rhs.desFq_z &&
    lhs.fb_pv_x == rhs.fb_pv_x &&
    lhs.fb_pv_y == rhs.fb_pv_y &&
    lhs.fb_pv_z == rhs.fb_pv_z &&
    lhs.fb_q_x == rhs.fb_q_x &&
    lhs.fb_q_y == rhs.fb_q_y &&
    lhs.fb_q_z == rhs.fb_q_z &&
    lhs.fb_Fq_x == rhs.fb_Fq_x &&
    lhs.fb_Fq_y == rhs.fb_Fq_y &&
    lhs.fb_Fq_z == rhs.fb_Fq_z &&
    lhs.v_modi_x == rhs.v_modi_x &&
    lhs.v_modi_y == rhs.v_modi_y &&
    lhs.v_modi_z == rhs.v_modi_z &&
    lhs.fb_Fq_error_fil_x == rhs.fb_Fq_error_fil_x &&
    lhs.fb_Fq_error_fil_y == rhs.fb_Fq_error_fil_y &&
    lhs.fb_Fq_error_fil_z == rhs.fb_Fq_error_fil_z &&
    lhs.FUpper == rhs.FUpper &&
    lhs.FLower == rhs.FLower &&
    lhs.ref_rpm1 == rhs.ref_rpm1 &&
    lhs.ref_rpm2 == rhs.ref_rpm2 &&
    lhs.ref_rpm3 == rhs.ref_rpm3 &&
    lhs.ref_rpm4 == rhs.ref_rpm4 &&
    lhs.ref_torque_x == rhs.ref_torque_x &&
    lhs.ref_torque_y == rhs.ref_torque_y &&
    lhs.ref_torque_z == rhs.ref_torque_z &&
    lhs.indi_F_Limit == rhs.indi_F_Limit;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quadrotor_msgs::Px4ctrlDebug_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::Px4ctrlDebug_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quadrotor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::Px4ctrlDebug_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::Px4ctrlDebug_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::Px4ctrlDebug_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::Px4ctrlDebug_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::Px4ctrlDebug_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::Px4ctrlDebug_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quadrotor_msgs::Px4ctrlDebug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "167f6f78f3c36c3f21cf2931478abb8f";
  }

  static const char* value(const ::quadrotor_msgs::Px4ctrlDebug_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x167f6f78f3c36c3fULL;
  static const uint64_t static_value2 = 0x21cf2931478abb8fULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotor_msgs::Px4ctrlDebug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quadrotor_msgs/Px4ctrlDebug";
  }

  static const char* value(const ::quadrotor_msgs::Px4ctrlDebug_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quadrotor_msgs::Px4ctrlDebug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"\n"
"\n"
"float64 fb_a_x\n"
"float64 fb_a_y\n"
"float64 fb_a_z\n"
"\n"
"float64 des_p_x\n"
"float64 des_p_y\n"
"float64 des_p_z\n"
"\n"
"float64 des_v_x\n"
"float64 des_v_y\n"
"float64 des_v_z\n"
"\n"
"float64 des_a_x\n"
"float64 des_a_y\n"
"float64 des_a_z\n"
"\n"
"\n"
"float64 des_q_x\n"
"float64 des_q_y\n"
"float64 des_q_z\n"
"float64 des_q_w\n"
"\n"
"float64 est_r\n"
"float64 est_p\n"
"float64 est_y\n"
"\n"
"float64 ref_r\n"
"float64 ref_p\n"
"float64 ref_y\n"
"\n"
"float64 des_r\n"
"float64 des_p\n"
"float64 des_y\n"
"\n"
"float64 exec_err_axisang_x\n"
"float64 exec_err_axisang_y\n"
"float64 exec_err_axisang_z\n"
"float64 exec_err_axisang_ang\n"
"\n"
"float64 fb_axisang_x\n"
"float64 fb_axisang_y\n"
"float64 fb_axisang_z\n"
"float64 fb_axisang_ang\n"
"\n"
"float64 fb_rate_x\n"
"float64 fb_rate_y\n"
"float64 fb_rate_z\n"
"\n"
"float64 des_bodyrates_x\n"
"float64 des_bodyrates_y\n"
"float64 des_bodyrates_z\n"
"\n"
"float64 des_bodyaccs_x\n"
"float64 des_bodyaccs_y\n"
"float64 des_bodyaccs_z\n"
"\n"
"float64 imu_af_x\n"
"float64 imu_af_y\n"
"float64 imu_af_z\n"
"\n"
"float64 imu_wf_x\n"
"float64 imu_wf_y\n"
"float64 imu_wf_z\n"
"\n"
"float64 imu_dw_x\n"
"float64 imu_dw_y\n"
"float64 imu_dw_z\n"
"\n"
"float64 rpm_f1\n"
"float64 rpm_f2\n"
"float64 rpm_f3\n"
"float64 rpm_f4\n"
"\n"
"float64 cmd_rpm1\n"
"float64 cmd_rpm2\n"
"float64 cmd_rpm3\n"
"float64 cmd_rpm4\n"
"\n"
"float64 ref_thrust1\n"
"float64 ref_thrust2\n"
"float64 ref_thrust3\n"
"float64 ref_thrust4\n"
"\n"
"float64 des_rpm_ave\n"
"float64 rpm_ave\n"
"\n"
"float64 des_yaw\n"
"float64 des_yaw_rate\n"
"float64 des_yaw_acc\n"
"\n"
"float64 thro1\n"
"float64 thro2\n"
"float64 thro3\n"
"float64 thro4\n"
"\n"
"float64 delta_q_ang\n"
"float64 des_q_ang\n"
"float64 des_F\n"
"float64 indi_F\n"
"float64 hover_percentage\n"
"float64 thr_scale_compensate\n"
"float64 voltage\n"
"\n"
"float64 ref_v_x\n"
"float64 ref_v_y\n"
"float64 ref_v_z\n"
"\n"
"float64 ref_a_x\n"
"float64 ref_a_y\n"
"float64 ref_a_z\n"
"\n"
"float64 ref_j_x\n"
"float64 ref_j_y\n"
"float64 ref_j_z\n"
"\n"
"float64 ref_s_x\n"
"float64 ref_s_y\n"
"float64 ref_s_z\n"
"\n"
"float64 x_pos_error\n"
"float64 y_pos_error \n"
"float64 z_pos_error \n"
"float64 x_vel_error \n"
"float64 y_vel_error \n"
"float64 z_vel_error \n"
"float64 ref_thr\n"
"float64 des_thr\n"
"float64 est_thr\n"
"float64 des_torque_x\n"
"float64 des_torque_y\n"
"float64 des_torque_z\n"
"float64 cont_torque_x\n"
"float64 cont_torque_y\n"
"float64 cont_torque_z\n"
"float64 z_jwj\n"
"\n"
"float64 fbp_thrust1\n"
"float64 fbi_thrust1\n"
"float64 fbp_thrust2\n"
"float64 fbi_thrust2\n"
"float64 fbp_thrust3\n"
"float64 fbi_thrust3\n"
"float64 fbp_thrust4\n"
"float64 fbi_thrust4\n"
"\n"
"float64 fbp_thrust\n"
"float64 fbi_thrust\n"
"float64 fb_thrust\n"
"\n"
"float64 rpm_error1\n"
"float64 rpm_error_sum1\n"
"float64 rpm_error2\n"
"float64 rpm_error_sum2\n"
"float64 rpm_error3\n"
"float64 rpm_error_sum3\n"
"float64 rpm_error4\n"
"float64 rpm_error_sum4\n"
"\n"
"float64 rate_error_z\n"
"float64 rate_error_sum_z\n"
"\n"
"float64 fbp_bodyacc_z\n"
"float64 fbi_bodyacc_z\n"
"\n"
"float64 des_est_bodyrates_x\n"
"float64 des_est_bodyrates_y\n"
"float64 des_est_bodyrates_z\n"
"\n"
"\n"
"float64 acc_error1\n"
"float64 acc_error2\n"
"float64 acc_error3\n"
"float64 acc_error4\n"
"\n"
"float64 acc_errorsum1\n"
"float64 acc_errorsum2\n"
"float64 acc_errorsum3\n"
"float64 acc_errorsum4\n"
"\n"
"float64 window_ave1\n"
"float64 window_ave2\n"
"float64 window_ave3\n"
"float64 window_ave4\n"
"\n"
"float64 pos_error_all\n"
"float64 pos_error_xy\n"
"float64 pos_error_rmse\n"
"float64 vel_error_all\n"
"float64 des_v_all\n"
"\n"
"float64 ref_bodyrates_x\n"
"float64 ref_bodyrates_y\n"
"float64 ref_bodyrates_z\n"
"\n"
"float64 extTotalAccIndi_x\n"
"float64 extTotalAccIndi_y\n"
"float64 extTotalAccIndi_z\n"
"\n"
"float64 aw_x\n"
"float64 aw_y\n"
"float64 aw_z\n"
"\n"
"float64 fb_a_x_fil\n"
"float64 fb_a_y_fil\n"
"float64 fb_a_z_fil\n"
"\n"
"float64 extF_psi\n"
"float64 extF_theta\n"
"\n"
"float64 des_Fq_psi\n"
"float64 des_Fq_theta\n"
"\n"
"float64 indi_q_err_ang\n"
"\n"
"float64 fb_F_x\n"
"float64 fb_F_y\n"
"float64 fb_F_z\n"
"\n"
"uint8 flag\n"
"\n"
"float64 indi_acc_q_error_x\n"
"float64 indi_acc_q_error_y\n"
"float64 indi_acc_q_error_z\n"
"float64 F_error\n"
"\n"
"float64 indi_acc_F_error_x\n"
"float64 indi_acc_F_error_y\n"
"float64 indi_acc_F_error_z\n"
"\n"
"float64 indiF_x\n"
"float64 indiF_y\n"
"float64 indiF_z\n"
"\n"
"float64 desFq_x\n"
"float64 desFq_y\n"
"float64 desFq_z\n"
"\n"
"float64 fb_pv_x\n"
"float64 fb_pv_y\n"
"float64 fb_pv_z\n"
"\n"
"float64 fb_q_x\n"
"float64 fb_q_y\n"
"float64 fb_q_z\n"
"\n"
"float64 fb_Fq_x\n"
"float64 fb_Fq_y\n"
"float64 fb_Fq_z\n"
"\n"
"float64 v_modi_x\n"
"float64 v_modi_y\n"
"float64 v_modi_z\n"
"\n"
"float64 fb_Fq_error_fil_x\n"
"float64 fb_Fq_error_fil_y\n"
"float64 fb_Fq_error_fil_z\n"
"\n"
"float64 FUpper\n"
"float64 FLower\n"
"float64 ref_rpm1\n"
"float64 ref_rpm2\n"
"float64 ref_rpm3\n"
"float64 ref_rpm4\n"
"float64 ref_torque_x\n"
"float64 ref_torque_y\n"
"float64 ref_torque_z\n"
"float64 indi_F_Limit\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::quadrotor_msgs::Px4ctrlDebug_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quadrotor_msgs::Px4ctrlDebug_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.fb_a_x);
      stream.next(m.fb_a_y);
      stream.next(m.fb_a_z);
      stream.next(m.des_p_x);
      stream.next(m.des_p_y);
      stream.next(m.des_p_z);
      stream.next(m.des_v_x);
      stream.next(m.des_v_y);
      stream.next(m.des_v_z);
      stream.next(m.des_a_x);
      stream.next(m.des_a_y);
      stream.next(m.des_a_z);
      stream.next(m.des_q_x);
      stream.next(m.des_q_y);
      stream.next(m.des_q_z);
      stream.next(m.des_q_w);
      stream.next(m.est_r);
      stream.next(m.est_p);
      stream.next(m.est_y);
      stream.next(m.ref_r);
      stream.next(m.ref_p);
      stream.next(m.ref_y);
      stream.next(m.des_r);
      stream.next(m.des_p);
      stream.next(m.des_y);
      stream.next(m.exec_err_axisang_x);
      stream.next(m.exec_err_axisang_y);
      stream.next(m.exec_err_axisang_z);
      stream.next(m.exec_err_axisang_ang);
      stream.next(m.fb_axisang_x);
      stream.next(m.fb_axisang_y);
      stream.next(m.fb_axisang_z);
      stream.next(m.fb_axisang_ang);
      stream.next(m.fb_rate_x);
      stream.next(m.fb_rate_y);
      stream.next(m.fb_rate_z);
      stream.next(m.des_bodyrates_x);
      stream.next(m.des_bodyrates_y);
      stream.next(m.des_bodyrates_z);
      stream.next(m.des_bodyaccs_x);
      stream.next(m.des_bodyaccs_y);
      stream.next(m.des_bodyaccs_z);
      stream.next(m.imu_af_x);
      stream.next(m.imu_af_y);
      stream.next(m.imu_af_z);
      stream.next(m.imu_wf_x);
      stream.next(m.imu_wf_y);
      stream.next(m.imu_wf_z);
      stream.next(m.imu_dw_x);
      stream.next(m.imu_dw_y);
      stream.next(m.imu_dw_z);
      stream.next(m.rpm_f1);
      stream.next(m.rpm_f2);
      stream.next(m.rpm_f3);
      stream.next(m.rpm_f4);
      stream.next(m.cmd_rpm1);
      stream.next(m.cmd_rpm2);
      stream.next(m.cmd_rpm3);
      stream.next(m.cmd_rpm4);
      stream.next(m.ref_thrust1);
      stream.next(m.ref_thrust2);
      stream.next(m.ref_thrust3);
      stream.next(m.ref_thrust4);
      stream.next(m.des_rpm_ave);
      stream.next(m.rpm_ave);
      stream.next(m.des_yaw);
      stream.next(m.des_yaw_rate);
      stream.next(m.des_yaw_acc);
      stream.next(m.thro1);
      stream.next(m.thro2);
      stream.next(m.thro3);
      stream.next(m.thro4);
      stream.next(m.delta_q_ang);
      stream.next(m.des_q_ang);
      stream.next(m.des_F);
      stream.next(m.indi_F);
      stream.next(m.hover_percentage);
      stream.next(m.thr_scale_compensate);
      stream.next(m.voltage);
      stream.next(m.ref_v_x);
      stream.next(m.ref_v_y);
      stream.next(m.ref_v_z);
      stream.next(m.ref_a_x);
      stream.next(m.ref_a_y);
      stream.next(m.ref_a_z);
      stream.next(m.ref_j_x);
      stream.next(m.ref_j_y);
      stream.next(m.ref_j_z);
      stream.next(m.ref_s_x);
      stream.next(m.ref_s_y);
      stream.next(m.ref_s_z);
      stream.next(m.x_pos_error);
      stream.next(m.y_pos_error);
      stream.next(m.z_pos_error);
      stream.next(m.x_vel_error);
      stream.next(m.y_vel_error);
      stream.next(m.z_vel_error);
      stream.next(m.ref_thr);
      stream.next(m.des_thr);
      stream.next(m.est_thr);
      stream.next(m.des_torque_x);
      stream.next(m.des_torque_y);
      stream.next(m.des_torque_z);
      stream.next(m.cont_torque_x);
      stream.next(m.cont_torque_y);
      stream.next(m.cont_torque_z);
      stream.next(m.z_jwj);
      stream.next(m.fbp_thrust1);
      stream.next(m.fbi_thrust1);
      stream.next(m.fbp_thrust2);
      stream.next(m.fbi_thrust2);
      stream.next(m.fbp_thrust3);
      stream.next(m.fbi_thrust3);
      stream.next(m.fbp_thrust4);
      stream.next(m.fbi_thrust4);
      stream.next(m.fbp_thrust);
      stream.next(m.fbi_thrust);
      stream.next(m.fb_thrust);
      stream.next(m.rpm_error1);
      stream.next(m.rpm_error_sum1);
      stream.next(m.rpm_error2);
      stream.next(m.rpm_error_sum2);
      stream.next(m.rpm_error3);
      stream.next(m.rpm_error_sum3);
      stream.next(m.rpm_error4);
      stream.next(m.rpm_error_sum4);
      stream.next(m.rate_error_z);
      stream.next(m.rate_error_sum_z);
      stream.next(m.fbp_bodyacc_z);
      stream.next(m.fbi_bodyacc_z);
      stream.next(m.des_est_bodyrates_x);
      stream.next(m.des_est_bodyrates_y);
      stream.next(m.des_est_bodyrates_z);
      stream.next(m.acc_error1);
      stream.next(m.acc_error2);
      stream.next(m.acc_error3);
      stream.next(m.acc_error4);
      stream.next(m.acc_errorsum1);
      stream.next(m.acc_errorsum2);
      stream.next(m.acc_errorsum3);
      stream.next(m.acc_errorsum4);
      stream.next(m.window_ave1);
      stream.next(m.window_ave2);
      stream.next(m.window_ave3);
      stream.next(m.window_ave4);
      stream.next(m.pos_error_all);
      stream.next(m.pos_error_xy);
      stream.next(m.pos_error_rmse);
      stream.next(m.vel_error_all);
      stream.next(m.des_v_all);
      stream.next(m.ref_bodyrates_x);
      stream.next(m.ref_bodyrates_y);
      stream.next(m.ref_bodyrates_z);
      stream.next(m.extTotalAccIndi_x);
      stream.next(m.extTotalAccIndi_y);
      stream.next(m.extTotalAccIndi_z);
      stream.next(m.aw_x);
      stream.next(m.aw_y);
      stream.next(m.aw_z);
      stream.next(m.fb_a_x_fil);
      stream.next(m.fb_a_y_fil);
      stream.next(m.fb_a_z_fil);
      stream.next(m.extF_psi);
      stream.next(m.extF_theta);
      stream.next(m.des_Fq_psi);
      stream.next(m.des_Fq_theta);
      stream.next(m.indi_q_err_ang);
      stream.next(m.fb_F_x);
      stream.next(m.fb_F_y);
      stream.next(m.fb_F_z);
      stream.next(m.flag);
      stream.next(m.indi_acc_q_error_x);
      stream.next(m.indi_acc_q_error_y);
      stream.next(m.indi_acc_q_error_z);
      stream.next(m.F_error);
      stream.next(m.indi_acc_F_error_x);
      stream.next(m.indi_acc_F_error_y);
      stream.next(m.indi_acc_F_error_z);
      stream.next(m.indiF_x);
      stream.next(m.indiF_y);
      stream.next(m.indiF_z);
      stream.next(m.desFq_x);
      stream.next(m.desFq_y);
      stream.next(m.desFq_z);
      stream.next(m.fb_pv_x);
      stream.next(m.fb_pv_y);
      stream.next(m.fb_pv_z);
      stream.next(m.fb_q_x);
      stream.next(m.fb_q_y);
      stream.next(m.fb_q_z);
      stream.next(m.fb_Fq_x);
      stream.next(m.fb_Fq_y);
      stream.next(m.fb_Fq_z);
      stream.next(m.v_modi_x);
      stream.next(m.v_modi_y);
      stream.next(m.v_modi_z);
      stream.next(m.fb_Fq_error_fil_x);
      stream.next(m.fb_Fq_error_fil_y);
      stream.next(m.fb_Fq_error_fil_z);
      stream.next(m.FUpper);
      stream.next(m.FLower);
      stream.next(m.ref_rpm1);
      stream.next(m.ref_rpm2);
      stream.next(m.ref_rpm3);
      stream.next(m.ref_rpm4);
      stream.next(m.ref_torque_x);
      stream.next(m.ref_torque_y);
      stream.next(m.ref_torque_z);
      stream.next(m.indi_F_Limit);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Px4ctrlDebug_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadrotor_msgs::Px4ctrlDebug_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quadrotor_msgs::Px4ctrlDebug_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_a_x: ";
    Printer<double>::stream(s, indent + "  ", v.fb_a_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_a_y: ";
    Printer<double>::stream(s, indent + "  ", v.fb_a_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_a_z: ";
    Printer<double>::stream(s, indent + "  ", v.fb_a_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_p_x: ";
    Printer<double>::stream(s, indent + "  ", v.des_p_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_p_y: ";
    Printer<double>::stream(s, indent + "  ", v.des_p_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_p_z: ";
    Printer<double>::stream(s, indent + "  ", v.des_p_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_v_x: ";
    Printer<double>::stream(s, indent + "  ", v.des_v_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_v_y: ";
    Printer<double>::stream(s, indent + "  ", v.des_v_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_v_z: ";
    Printer<double>::stream(s, indent + "  ", v.des_v_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_a_x: ";
    Printer<double>::stream(s, indent + "  ", v.des_a_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_a_y: ";
    Printer<double>::stream(s, indent + "  ", v.des_a_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_a_z: ";
    Printer<double>::stream(s, indent + "  ", v.des_a_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_q_x: ";
    Printer<double>::stream(s, indent + "  ", v.des_q_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_q_y: ";
    Printer<double>::stream(s, indent + "  ", v.des_q_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_q_z: ";
    Printer<double>::stream(s, indent + "  ", v.des_q_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_q_w: ";
    Printer<double>::stream(s, indent + "  ", v.des_q_w);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "est_r: ";
    Printer<double>::stream(s, indent + "  ", v.est_r);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "est_p: ";
    Printer<double>::stream(s, indent + "  ", v.est_p);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "est_y: ";
    Printer<double>::stream(s, indent + "  ", v.est_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_r: ";
    Printer<double>::stream(s, indent + "  ", v.ref_r);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_p: ";
    Printer<double>::stream(s, indent + "  ", v.ref_p);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_y: ";
    Printer<double>::stream(s, indent + "  ", v.ref_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_r: ";
    Printer<double>::stream(s, indent + "  ", v.des_r);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_p: ";
    Printer<double>::stream(s, indent + "  ", v.des_p);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_y: ";
    Printer<double>::stream(s, indent + "  ", v.des_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "exec_err_axisang_x: ";
    Printer<double>::stream(s, indent + "  ", v.exec_err_axisang_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "exec_err_axisang_y: ";
    Printer<double>::stream(s, indent + "  ", v.exec_err_axisang_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "exec_err_axisang_z: ";
    Printer<double>::stream(s, indent + "  ", v.exec_err_axisang_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "exec_err_axisang_ang: ";
    Printer<double>::stream(s, indent + "  ", v.exec_err_axisang_ang);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_axisang_x: ";
    Printer<double>::stream(s, indent + "  ", v.fb_axisang_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_axisang_y: ";
    Printer<double>::stream(s, indent + "  ", v.fb_axisang_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_axisang_z: ";
    Printer<double>::stream(s, indent + "  ", v.fb_axisang_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_axisang_ang: ";
    Printer<double>::stream(s, indent + "  ", v.fb_axisang_ang);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_rate_x: ";
    Printer<double>::stream(s, indent + "  ", v.fb_rate_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_rate_y: ";
    Printer<double>::stream(s, indent + "  ", v.fb_rate_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_rate_z: ";
    Printer<double>::stream(s, indent + "  ", v.fb_rate_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_bodyrates_x: ";
    Printer<double>::stream(s, indent + "  ", v.des_bodyrates_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_bodyrates_y: ";
    Printer<double>::stream(s, indent + "  ", v.des_bodyrates_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_bodyrates_z: ";
    Printer<double>::stream(s, indent + "  ", v.des_bodyrates_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_bodyaccs_x: ";
    Printer<double>::stream(s, indent + "  ", v.des_bodyaccs_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_bodyaccs_y: ";
    Printer<double>::stream(s, indent + "  ", v.des_bodyaccs_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_bodyaccs_z: ";
    Printer<double>::stream(s, indent + "  ", v.des_bodyaccs_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "imu_af_x: ";
    Printer<double>::stream(s, indent + "  ", v.imu_af_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "imu_af_y: ";
    Printer<double>::stream(s, indent + "  ", v.imu_af_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "imu_af_z: ";
    Printer<double>::stream(s, indent + "  ", v.imu_af_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "imu_wf_x: ";
    Printer<double>::stream(s, indent + "  ", v.imu_wf_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "imu_wf_y: ";
    Printer<double>::stream(s, indent + "  ", v.imu_wf_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "imu_wf_z: ";
    Printer<double>::stream(s, indent + "  ", v.imu_wf_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "imu_dw_x: ";
    Printer<double>::stream(s, indent + "  ", v.imu_dw_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "imu_dw_y: ";
    Printer<double>::stream(s, indent + "  ", v.imu_dw_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "imu_dw_z: ";
    Printer<double>::stream(s, indent + "  ", v.imu_dw_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rpm_f1: ";
    Printer<double>::stream(s, indent + "  ", v.rpm_f1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rpm_f2: ";
    Printer<double>::stream(s, indent + "  ", v.rpm_f2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rpm_f3: ";
    Printer<double>::stream(s, indent + "  ", v.rpm_f3);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rpm_f4: ";
    Printer<double>::stream(s, indent + "  ", v.rpm_f4);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_rpm1: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_rpm1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_rpm2: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_rpm2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_rpm3: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_rpm3);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_rpm4: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_rpm4);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_thrust1: ";
    Printer<double>::stream(s, indent + "  ", v.ref_thrust1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_thrust2: ";
    Printer<double>::stream(s, indent + "  ", v.ref_thrust2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_thrust3: ";
    Printer<double>::stream(s, indent + "  ", v.ref_thrust3);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_thrust4: ";
    Printer<double>::stream(s, indent + "  ", v.ref_thrust4);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_rpm_ave: ";
    Printer<double>::stream(s, indent + "  ", v.des_rpm_ave);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rpm_ave: ";
    Printer<double>::stream(s, indent + "  ", v.rpm_ave);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_yaw: ";
    Printer<double>::stream(s, indent + "  ", v.des_yaw);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_yaw_rate: ";
    Printer<double>::stream(s, indent + "  ", v.des_yaw_rate);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_yaw_acc: ";
    Printer<double>::stream(s, indent + "  ", v.des_yaw_acc);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "thro1: ";
    Printer<double>::stream(s, indent + "  ", v.thro1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "thro2: ";
    Printer<double>::stream(s, indent + "  ", v.thro2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "thro3: ";
    Printer<double>::stream(s, indent + "  ", v.thro3);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "thro4: ";
    Printer<double>::stream(s, indent + "  ", v.thro4);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "delta_q_ang: ";
    Printer<double>::stream(s, indent + "  ", v.delta_q_ang);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_q_ang: ";
    Printer<double>::stream(s, indent + "  ", v.des_q_ang);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_F: ";
    Printer<double>::stream(s, indent + "  ", v.des_F);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "indi_F: ";
    Printer<double>::stream(s, indent + "  ", v.indi_F);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "hover_percentage: ";
    Printer<double>::stream(s, indent + "  ", v.hover_percentage);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "thr_scale_compensate: ";
    Printer<double>::stream(s, indent + "  ", v.thr_scale_compensate);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "voltage: ";
    Printer<double>::stream(s, indent + "  ", v.voltage);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_v_x: ";
    Printer<double>::stream(s, indent + "  ", v.ref_v_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_v_y: ";
    Printer<double>::stream(s, indent + "  ", v.ref_v_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_v_z: ";
    Printer<double>::stream(s, indent + "  ", v.ref_v_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_a_x: ";
    Printer<double>::stream(s, indent + "  ", v.ref_a_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_a_y: ";
    Printer<double>::stream(s, indent + "  ", v.ref_a_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_a_z: ";
    Printer<double>::stream(s, indent + "  ", v.ref_a_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_j_x: ";
    Printer<double>::stream(s, indent + "  ", v.ref_j_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_j_y: ";
    Printer<double>::stream(s, indent + "  ", v.ref_j_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_j_z: ";
    Printer<double>::stream(s, indent + "  ", v.ref_j_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_s_x: ";
    Printer<double>::stream(s, indent + "  ", v.ref_s_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_s_y: ";
    Printer<double>::stream(s, indent + "  ", v.ref_s_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_s_z: ";
    Printer<double>::stream(s, indent + "  ", v.ref_s_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x_pos_error: ";
    Printer<double>::stream(s, indent + "  ", v.x_pos_error);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y_pos_error: ";
    Printer<double>::stream(s, indent + "  ", v.y_pos_error);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "z_pos_error: ";
    Printer<double>::stream(s, indent + "  ", v.z_pos_error);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x_vel_error: ";
    Printer<double>::stream(s, indent + "  ", v.x_vel_error);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y_vel_error: ";
    Printer<double>::stream(s, indent + "  ", v.y_vel_error);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "z_vel_error: ";
    Printer<double>::stream(s, indent + "  ", v.z_vel_error);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_thr: ";
    Printer<double>::stream(s, indent + "  ", v.ref_thr);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_thr: ";
    Printer<double>::stream(s, indent + "  ", v.des_thr);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "est_thr: ";
    Printer<double>::stream(s, indent + "  ", v.est_thr);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_torque_x: ";
    Printer<double>::stream(s, indent + "  ", v.des_torque_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_torque_y: ";
    Printer<double>::stream(s, indent + "  ", v.des_torque_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_torque_z: ";
    Printer<double>::stream(s, indent + "  ", v.des_torque_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cont_torque_x: ";
    Printer<double>::stream(s, indent + "  ", v.cont_torque_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cont_torque_y: ";
    Printer<double>::stream(s, indent + "  ", v.cont_torque_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cont_torque_z: ";
    Printer<double>::stream(s, indent + "  ", v.cont_torque_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "z_jwj: ";
    Printer<double>::stream(s, indent + "  ", v.z_jwj);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fbp_thrust1: ";
    Printer<double>::stream(s, indent + "  ", v.fbp_thrust1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fbi_thrust1: ";
    Printer<double>::stream(s, indent + "  ", v.fbi_thrust1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fbp_thrust2: ";
    Printer<double>::stream(s, indent + "  ", v.fbp_thrust2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fbi_thrust2: ";
    Printer<double>::stream(s, indent + "  ", v.fbi_thrust2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fbp_thrust3: ";
    Printer<double>::stream(s, indent + "  ", v.fbp_thrust3);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fbi_thrust3: ";
    Printer<double>::stream(s, indent + "  ", v.fbi_thrust3);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fbp_thrust4: ";
    Printer<double>::stream(s, indent + "  ", v.fbp_thrust4);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fbi_thrust4: ";
    Printer<double>::stream(s, indent + "  ", v.fbi_thrust4);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fbp_thrust: ";
    Printer<double>::stream(s, indent + "  ", v.fbp_thrust);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fbi_thrust: ";
    Printer<double>::stream(s, indent + "  ", v.fbi_thrust);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_thrust: ";
    Printer<double>::stream(s, indent + "  ", v.fb_thrust);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rpm_error1: ";
    Printer<double>::stream(s, indent + "  ", v.rpm_error1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rpm_error_sum1: ";
    Printer<double>::stream(s, indent + "  ", v.rpm_error_sum1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rpm_error2: ";
    Printer<double>::stream(s, indent + "  ", v.rpm_error2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rpm_error_sum2: ";
    Printer<double>::stream(s, indent + "  ", v.rpm_error_sum2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rpm_error3: ";
    Printer<double>::stream(s, indent + "  ", v.rpm_error3);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rpm_error_sum3: ";
    Printer<double>::stream(s, indent + "  ", v.rpm_error_sum3);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rpm_error4: ";
    Printer<double>::stream(s, indent + "  ", v.rpm_error4);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rpm_error_sum4: ";
    Printer<double>::stream(s, indent + "  ", v.rpm_error_sum4);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rate_error_z: ";
    Printer<double>::stream(s, indent + "  ", v.rate_error_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rate_error_sum_z: ";
    Printer<double>::stream(s, indent + "  ", v.rate_error_sum_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fbp_bodyacc_z: ";
    Printer<double>::stream(s, indent + "  ", v.fbp_bodyacc_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fbi_bodyacc_z: ";
    Printer<double>::stream(s, indent + "  ", v.fbi_bodyacc_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_est_bodyrates_x: ";
    Printer<double>::stream(s, indent + "  ", v.des_est_bodyrates_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_est_bodyrates_y: ";
    Printer<double>::stream(s, indent + "  ", v.des_est_bodyrates_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_est_bodyrates_z: ";
    Printer<double>::stream(s, indent + "  ", v.des_est_bodyrates_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "acc_error1: ";
    Printer<double>::stream(s, indent + "  ", v.acc_error1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "acc_error2: ";
    Printer<double>::stream(s, indent + "  ", v.acc_error2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "acc_error3: ";
    Printer<double>::stream(s, indent + "  ", v.acc_error3);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "acc_error4: ";
    Printer<double>::stream(s, indent + "  ", v.acc_error4);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "acc_errorsum1: ";
    Printer<double>::stream(s, indent + "  ", v.acc_errorsum1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "acc_errorsum2: ";
    Printer<double>::stream(s, indent + "  ", v.acc_errorsum2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "acc_errorsum3: ";
    Printer<double>::stream(s, indent + "  ", v.acc_errorsum3);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "acc_errorsum4: ";
    Printer<double>::stream(s, indent + "  ", v.acc_errorsum4);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "window_ave1: ";
    Printer<double>::stream(s, indent + "  ", v.window_ave1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "window_ave2: ";
    Printer<double>::stream(s, indent + "  ", v.window_ave2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "window_ave3: ";
    Printer<double>::stream(s, indent + "  ", v.window_ave3);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "window_ave4: ";
    Printer<double>::stream(s, indent + "  ", v.window_ave4);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pos_error_all: ";
    Printer<double>::stream(s, indent + "  ", v.pos_error_all);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pos_error_xy: ";
    Printer<double>::stream(s, indent + "  ", v.pos_error_xy);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pos_error_rmse: ";
    Printer<double>::stream(s, indent + "  ", v.pos_error_rmse);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vel_error_all: ";
    Printer<double>::stream(s, indent + "  ", v.vel_error_all);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_v_all: ";
    Printer<double>::stream(s, indent + "  ", v.des_v_all);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_bodyrates_x: ";
    Printer<double>::stream(s, indent + "  ", v.ref_bodyrates_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_bodyrates_y: ";
    Printer<double>::stream(s, indent + "  ", v.ref_bodyrates_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_bodyrates_z: ";
    Printer<double>::stream(s, indent + "  ", v.ref_bodyrates_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "extTotalAccIndi_x: ";
    Printer<double>::stream(s, indent + "  ", v.extTotalAccIndi_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "extTotalAccIndi_y: ";
    Printer<double>::stream(s, indent + "  ", v.extTotalAccIndi_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "extTotalAccIndi_z: ";
    Printer<double>::stream(s, indent + "  ", v.extTotalAccIndi_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "aw_x: ";
    Printer<double>::stream(s, indent + "  ", v.aw_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "aw_y: ";
    Printer<double>::stream(s, indent + "  ", v.aw_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "aw_z: ";
    Printer<double>::stream(s, indent + "  ", v.aw_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_a_x_fil: ";
    Printer<double>::stream(s, indent + "  ", v.fb_a_x_fil);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_a_y_fil: ";
    Printer<double>::stream(s, indent + "  ", v.fb_a_y_fil);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_a_z_fil: ";
    Printer<double>::stream(s, indent + "  ", v.fb_a_z_fil);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "extF_psi: ";
    Printer<double>::stream(s, indent + "  ", v.extF_psi);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "extF_theta: ";
    Printer<double>::stream(s, indent + "  ", v.extF_theta);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_Fq_psi: ";
    Printer<double>::stream(s, indent + "  ", v.des_Fq_psi);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "des_Fq_theta: ";
    Printer<double>::stream(s, indent + "  ", v.des_Fq_theta);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "indi_q_err_ang: ";
    Printer<double>::stream(s, indent + "  ", v.indi_q_err_ang);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_F_x: ";
    Printer<double>::stream(s, indent + "  ", v.fb_F_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_F_y: ";
    Printer<double>::stream(s, indent + "  ", v.fb_F_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_F_z: ";
    Printer<double>::stream(s, indent + "  ", v.fb_F_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flag);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "indi_acc_q_error_x: ";
    Printer<double>::stream(s, indent + "  ", v.indi_acc_q_error_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "indi_acc_q_error_y: ";
    Printer<double>::stream(s, indent + "  ", v.indi_acc_q_error_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "indi_acc_q_error_z: ";
    Printer<double>::stream(s, indent + "  ", v.indi_acc_q_error_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "F_error: ";
    Printer<double>::stream(s, indent + "  ", v.F_error);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "indi_acc_F_error_x: ";
    Printer<double>::stream(s, indent + "  ", v.indi_acc_F_error_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "indi_acc_F_error_y: ";
    Printer<double>::stream(s, indent + "  ", v.indi_acc_F_error_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "indi_acc_F_error_z: ";
    Printer<double>::stream(s, indent + "  ", v.indi_acc_F_error_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "indiF_x: ";
    Printer<double>::stream(s, indent + "  ", v.indiF_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "indiF_y: ";
    Printer<double>::stream(s, indent + "  ", v.indiF_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "indiF_z: ";
    Printer<double>::stream(s, indent + "  ", v.indiF_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "desFq_x: ";
    Printer<double>::stream(s, indent + "  ", v.desFq_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "desFq_y: ";
    Printer<double>::stream(s, indent + "  ", v.desFq_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "desFq_z: ";
    Printer<double>::stream(s, indent + "  ", v.desFq_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_pv_x: ";
    Printer<double>::stream(s, indent + "  ", v.fb_pv_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_pv_y: ";
    Printer<double>::stream(s, indent + "  ", v.fb_pv_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_pv_z: ";
    Printer<double>::stream(s, indent + "  ", v.fb_pv_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_q_x: ";
    Printer<double>::stream(s, indent + "  ", v.fb_q_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_q_y: ";
    Printer<double>::stream(s, indent + "  ", v.fb_q_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_q_z: ";
    Printer<double>::stream(s, indent + "  ", v.fb_q_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_Fq_x: ";
    Printer<double>::stream(s, indent + "  ", v.fb_Fq_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_Fq_y: ";
    Printer<double>::stream(s, indent + "  ", v.fb_Fq_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_Fq_z: ";
    Printer<double>::stream(s, indent + "  ", v.fb_Fq_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "v_modi_x: ";
    Printer<double>::stream(s, indent + "  ", v.v_modi_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "v_modi_y: ";
    Printer<double>::stream(s, indent + "  ", v.v_modi_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "v_modi_z: ";
    Printer<double>::stream(s, indent + "  ", v.v_modi_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_Fq_error_fil_x: ";
    Printer<double>::stream(s, indent + "  ", v.fb_Fq_error_fil_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_Fq_error_fil_y: ";
    Printer<double>::stream(s, indent + "  ", v.fb_Fq_error_fil_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fb_Fq_error_fil_z: ";
    Printer<double>::stream(s, indent + "  ", v.fb_Fq_error_fil_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "FUpper: ";
    Printer<double>::stream(s, indent + "  ", v.FUpper);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "FLower: ";
    Printer<double>::stream(s, indent + "  ", v.FLower);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_rpm1: ";
    Printer<double>::stream(s, indent + "  ", v.ref_rpm1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_rpm2: ";
    Printer<double>::stream(s, indent + "  ", v.ref_rpm2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_rpm3: ";
    Printer<double>::stream(s, indent + "  ", v.ref_rpm3);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_rpm4: ";
    Printer<double>::stream(s, indent + "  ", v.ref_rpm4);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_torque_x: ";
    Printer<double>::stream(s, indent + "  ", v.ref_torque_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_torque_y: ";
    Printer<double>::stream(s, indent + "  ", v.ref_torque_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_torque_z: ";
    Printer<double>::stream(s, indent + "  ", v.ref_torque_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "indi_F_Limit: ";
    Printer<double>::stream(s, indent + "  ", v.indi_F_Limit);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUADROTOR_MSGS_MESSAGE_PX4CTRLDEBUG_H
