// Generated by gencpp from file quadrotor_msgs/Rpms.msg
// DO NOT EDIT!


#ifndef QUADROTOR_MSGS_MESSAGE_RPMS_H
#define QUADROTOR_MSGS_MESSAGE_RPMS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace quadrotor_msgs
{
template <class ContainerAllocator>
struct Rpms_
{
  typedef Rpms_<ContainerAllocator> Type;

  Rpms_()
    : rpm0(0.0)
    , rpm1(0.0)
    , rpm2(0.0)
    , rpm3(0.0)  {
    }
  Rpms_(const ContainerAllocator& _alloc)
    : rpm0(0.0)
    , rpm1(0.0)
    , rpm2(0.0)
    , rpm3(0.0)  {
  (void)_alloc;
    }



   typedef double _rpm0_type;
  _rpm0_type rpm0;

   typedef double _rpm1_type;
  _rpm1_type rpm1;

   typedef double _rpm2_type;
  _rpm2_type rpm2;

   typedef double _rpm3_type;
  _rpm3_type rpm3;





  typedef boost::shared_ptr< ::quadrotor_msgs::Rpms_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotor_msgs::Rpms_<ContainerAllocator> const> ConstPtr;

}; // struct Rpms_

typedef ::quadrotor_msgs::Rpms_<std::allocator<void> > Rpms;

typedef boost::shared_ptr< ::quadrotor_msgs::Rpms > RpmsPtr;
typedef boost::shared_ptr< ::quadrotor_msgs::Rpms const> RpmsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quadrotor_msgs::Rpms_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quadrotor_msgs::Rpms_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quadrotor_msgs::Rpms_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::Rpms_<ContainerAllocator2> & rhs)
{
  return lhs.rpm0 == rhs.rpm0 &&
    lhs.rpm1 == rhs.rpm1 &&
    lhs.rpm2 == rhs.rpm2 &&
    lhs.rpm3 == rhs.rpm3;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quadrotor_msgs::Rpms_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::Rpms_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quadrotor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::Rpms_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::Rpms_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::Rpms_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::Rpms_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::Rpms_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::Rpms_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quadrotor_msgs::Rpms_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f34c377dbbd6cd5c05fde291e41b791";
  }

  static const char* value(const ::quadrotor_msgs::Rpms_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f34c377dbbd6cd5ULL;
  static const uint64_t static_value2 = 0xc05fde291e41b791ULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotor_msgs::Rpms_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quadrotor_msgs/Rpms";
  }

  static const char* value(const ::quadrotor_msgs::Rpms_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quadrotor_msgs::Rpms_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 rpm0\n"
"float64 rpm1\n"
"float64 rpm2\n"
"float64 rpm3\n"
;
  }

  static const char* value(const ::quadrotor_msgs::Rpms_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quadrotor_msgs::Rpms_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rpm0);
      stream.next(m.rpm1);
      stream.next(m.rpm2);
      stream.next(m.rpm3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Rpms_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadrotor_msgs::Rpms_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quadrotor_msgs::Rpms_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "rpm0: ";
    Printer<double>::stream(s, indent + "  ", v.rpm0);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rpm1: ";
    Printer<double>::stream(s, indent + "  ", v.rpm1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rpm2: ";
    Printer<double>::stream(s, indent + "  ", v.rpm2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rpm3: ";
    Printer<double>::stream(s, indent + "  ", v.rpm3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUADROTOR_MSGS_MESSAGE_RPMS_H
