// Generated by gencpp from file quadrotor_msgs/SimState.msg
// DO NOT EDIT!


#ifndef QUADROTOR_MSGS_MESSAGE_SIMSTATE_H
#define QUADROTOR_MSGS_MESSAGE_SIMSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace quadrotor_msgs
{
template <class ContainerAllocator>
struct SimState_
{
  typedef SimState_<ContainerAllocator> Type;

  SimState_()
    : header()
    , srpy()
    , sq()  {
    }
  SimState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , srpy(_alloc)
    , sq(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _srpy_type;
  _srpy_type srpy;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _sq_type;
  _sq_type sq;





  typedef boost::shared_ptr< ::quadrotor_msgs::SimState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotor_msgs::SimState_<ContainerAllocator> const> ConstPtr;

}; // struct SimState_

typedef ::quadrotor_msgs::SimState_<std::allocator<void> > SimState;

typedef boost::shared_ptr< ::quadrotor_msgs::SimState > SimStatePtr;
typedef boost::shared_ptr< ::quadrotor_msgs::SimState const> SimStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quadrotor_msgs::SimState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quadrotor_msgs::SimState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quadrotor_msgs::SimState_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::SimState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.srpy == rhs.srpy &&
    lhs.sq == rhs.sq;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quadrotor_msgs::SimState_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::SimState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quadrotor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::SimState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::SimState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::SimState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::SimState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::SimState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::SimState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quadrotor_msgs::SimState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "644e11e25552c02543ecd03ed7f77057";
  }

  static const char* value(const ::quadrotor_msgs::SimState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x644e11e25552c025ULL;
  static const uint64_t static_value2 = 0x43ecd03ed7f77057ULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotor_msgs::SimState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quadrotor_msgs/SimState";
  }

  static const char* value(const ::quadrotor_msgs::SimState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quadrotor_msgs::SimState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"geometry_msgs/Vector3 srpy\n"
"geometry_msgs/Vector3 sq\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::quadrotor_msgs::SimState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quadrotor_msgs::SimState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.srpy);
      stream.next(m.sq);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SimState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadrotor_msgs::SimState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quadrotor_msgs::SimState_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "srpy: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.srpy);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "sq: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.sq);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUADROTOR_MSGS_MESSAGE_SIMSTATE_H
