// Generated by gencpp from file quadrotor_msgs/SO3Command.msg
// DO NOT EDIT!


#ifndef QUADROTOR_MSGS_MESSAGE_SO3COMMAND_H
#define QUADROTOR_MSGS_MESSAGE_SO3COMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Quaternion.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <quadrotor_msgs/AuxCommand.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace quadrotor_msgs
{
template <class ContainerAllocator>
struct SO3Command_
{
  typedef SO3Command_<ContainerAllocator> Type;

  SO3Command_()
    : header()
    , id(0)
    , force()
    , orientation()
    , omg()
    , domg()
    , aux()
    , ref_p()
    , ref_v()
    , ref_a()
    , ref_q()
    , ref_rpy()
    , ref_F(0.0)
    , ref_qt(0.0)
    , ref_qy(0.0)  {
    }
  SO3Command_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0)
    , force(_alloc)
    , orientation(_alloc)
    , omg(_alloc)
    , domg(_alloc)
    , aux(_alloc)
    , ref_p(_alloc)
    , ref_v(_alloc)
    , ref_a(_alloc)
    , ref_q(_alloc)
    , ref_rpy(_alloc)
    , ref_F(0.0)
    , ref_qt(0.0)
    , ref_qy(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _id_type;
  _id_type id;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _force_type;
  _force_type force;

   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _orientation_type;
  _orientation_type orientation;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _omg_type;
  _omg_type omg;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _domg_type;
  _domg_type domg;

   typedef  ::quadrotor_msgs::AuxCommand_<ContainerAllocator>  _aux_type;
  _aux_type aux;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _ref_p_type;
  _ref_p_type ref_p;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _ref_v_type;
  _ref_v_type ref_v;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _ref_a_type;
  _ref_a_type ref_a;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _ref_q_type;
  _ref_q_type ref_q;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _ref_rpy_type;
  _ref_rpy_type ref_rpy;

   typedef double _ref_F_type;
  _ref_F_type ref_F;

   typedef double _ref_qt_type;
  _ref_qt_type ref_qt;

   typedef double _ref_qy_type;
  _ref_qy_type ref_qy;





  typedef boost::shared_ptr< ::quadrotor_msgs::SO3Command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotor_msgs::SO3Command_<ContainerAllocator> const> ConstPtr;

}; // struct SO3Command_

typedef ::quadrotor_msgs::SO3Command_<std::allocator<void> > SO3Command;

typedef boost::shared_ptr< ::quadrotor_msgs::SO3Command > SO3CommandPtr;
typedef boost::shared_ptr< ::quadrotor_msgs::SO3Command const> SO3CommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quadrotor_msgs::SO3Command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quadrotor_msgs::SO3Command_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quadrotor_msgs::SO3Command_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::SO3Command_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.id == rhs.id &&
    lhs.force == rhs.force &&
    lhs.orientation == rhs.orientation &&
    lhs.omg == rhs.omg &&
    lhs.domg == rhs.domg &&
    lhs.aux == rhs.aux &&
    lhs.ref_p == rhs.ref_p &&
    lhs.ref_v == rhs.ref_v &&
    lhs.ref_a == rhs.ref_a &&
    lhs.ref_q == rhs.ref_q &&
    lhs.ref_rpy == rhs.ref_rpy &&
    lhs.ref_F == rhs.ref_F &&
    lhs.ref_qt == rhs.ref_qt &&
    lhs.ref_qy == rhs.ref_qy;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quadrotor_msgs::SO3Command_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::SO3Command_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quadrotor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::SO3Command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::SO3Command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::SO3Command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::SO3Command_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::SO3Command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::SO3Command_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quadrotor_msgs::SO3Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cdd2dd735e73a1d9a730f9dbe0796283";
  }

  static const char* value(const ::quadrotor_msgs::SO3Command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcdd2dd735e73a1d9ULL;
  static const uint64_t static_value2 = 0xa730f9dbe0796283ULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotor_msgs::SO3Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quadrotor_msgs/SO3Command";
  }

  static const char* value(const ::quadrotor_msgs::SO3Command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quadrotor_msgs::SO3Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint8 id\n"
"geometry_msgs/Vector3 force\n"
"geometry_msgs/Quaternion orientation\n"
"geometry_msgs/Vector3 omg\n"
"geometry_msgs/Vector3 domg\n"
"quadrotor_msgs/AuxCommand aux\n"
"geometry_msgs/Vector3 ref_p\n"
"geometry_msgs/Vector3 ref_v\n"
"geometry_msgs/Vector3 ref_a\n"
"geometry_msgs/Vector3 ref_q\n"
"geometry_msgs/Vector3 ref_rpy\n"
"float64 ref_F\n"
"float64 ref_qt\n"
"float64 ref_qy\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: quadrotor_msgs/AuxCommand\n"
"float64 current_yaw\n"
"float64 kf_correction\n"
"float64[2] angle_corrections# Trims for roll, pitch\n"
"bool enable_motors\n"
"bool use_external_yaw\n"
;
  }

  static const char* value(const ::quadrotor_msgs::SO3Command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quadrotor_msgs::SO3Command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.force);
      stream.next(m.orientation);
      stream.next(m.omg);
      stream.next(m.domg);
      stream.next(m.aux);
      stream.next(m.ref_p);
      stream.next(m.ref_v);
      stream.next(m.ref_a);
      stream.next(m.ref_q);
      stream.next(m.ref_rpy);
      stream.next(m.ref_F);
      stream.next(m.ref_qt);
      stream.next(m.ref_qy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SO3Command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadrotor_msgs::SO3Command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quadrotor_msgs::SO3Command_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "force: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.force);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "orientation: ";
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.orientation);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "omg: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.omg);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "domg: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.domg);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "aux: ";
    Printer< ::quadrotor_msgs::AuxCommand_<ContainerAllocator> >::stream(s, indent + "  ", v.aux);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_p: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.ref_p);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_v: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.ref_v);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_a: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.ref_a);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_q: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.ref_q);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_rpy: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.ref_rpy);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_F: ";
    Printer<double>::stream(s, indent + "  ", v.ref_F);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_qt: ";
    Printer<double>::stream(s, indent + "  ", v.ref_qt);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_qy: ";
    Printer<double>::stream(s, indent + "  ", v.ref_qy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUADROTOR_MSGS_MESSAGE_SO3COMMAND_H
