// Generated by gencpp from file quadrotor_msgs/trigger.msg
// DO NOT EDIT!


#ifndef QUADROTOR_MSGS_MESSAGE_TRIGGER_H
#define QUADROTOR_MSGS_MESSAGE_TRIGGER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace quadrotor_msgs
{
template <class ContainerAllocator>
struct trigger_
{
  typedef trigger_<ContainerAllocator> Type;

  trigger_()
    : trigger_cmd(0)  {
    }
  trigger_(const ContainerAllocator& _alloc)
    : trigger_cmd(0)  {
  (void)_alloc;
    }



   typedef uint8_t _trigger_cmd_type;
  _trigger_cmd_type trigger_cmd;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(triggerTakeOff)
  #undef triggerTakeOff
#endif
#if defined(_WIN32) && defined(triggerSwitchControl)
  #undef triggerSwitchControl
#endif
#if defined(_WIN32) && defined(triggerFlight)
  #undef triggerFlight
#endif

  enum {
    triggerTakeOff = 1u,
    triggerSwitchControl = 2u,
    triggerFlight = 3u,
  };


  typedef boost::shared_ptr< ::quadrotor_msgs::trigger_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotor_msgs::trigger_<ContainerAllocator> const> ConstPtr;

}; // struct trigger_

typedef ::quadrotor_msgs::trigger_<std::allocator<void> > trigger;

typedef boost::shared_ptr< ::quadrotor_msgs::trigger > triggerPtr;
typedef boost::shared_ptr< ::quadrotor_msgs::trigger const> triggerConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quadrotor_msgs::trigger_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quadrotor_msgs::trigger_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quadrotor_msgs::trigger_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::trigger_<ContainerAllocator2> & rhs)
{
  return lhs.trigger_cmd == rhs.trigger_cmd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quadrotor_msgs::trigger_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::trigger_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quadrotor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::trigger_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::trigger_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::trigger_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::trigger_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::trigger_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::trigger_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quadrotor_msgs::trigger_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8009a0fa43f357a00d4ef52b41eda254";
  }

  static const char* value(const ::quadrotor_msgs::trigger_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8009a0fa43f357a0ULL;
  static const uint64_t static_value2 = 0x0d4ef52b41eda254ULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotor_msgs::trigger_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quadrotor_msgs/trigger";
  }

  static const char* value(const ::quadrotor_msgs::trigger_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quadrotor_msgs::trigger_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 triggerTakeOff = 1\n"
"uint8 triggerSwitchControl = 2\n"
"uint8 triggerFlight = 3\n"
"uint8 trigger_cmd\n"
;
  }

  static const char* value(const ::quadrotor_msgs::trigger_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quadrotor_msgs::trigger_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.trigger_cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct trigger_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadrotor_msgs::trigger_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quadrotor_msgs::trigger_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "trigger_cmd: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.trigger_cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUADROTOR_MSGS_MESSAGE_TRIGGER_H
