# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from quadrotor_msgs/CorridorPolytope.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class CorridorPolytope(genpy.Message):
  _md5sum = "f1ee3021eb38c109bf2fef158ffb37a4"
  _type = "quadrotor_msgs/CorridorPolytope"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint32 path_begin
uint32 path_end
geometry_msgs/Vector3[] normals
float64[] offsets
geometry_msgs/Point[] vertices
bool clearance_bridge
float64 complexity
float64 local_extent
float64 minimum_system_margin
float64 maximum_system_margin

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['path_begin','path_end','normals','offsets','vertices','clearance_bridge','complexity','local_extent','minimum_system_margin','maximum_system_margin']
  _slot_types = ['uint32','uint32','geometry_msgs/Vector3[]','float64[]','geometry_msgs/Point[]','bool','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       path_begin,path_end,normals,offsets,vertices,clearance_bridge,complexity,local_extent,minimum_system_margin,maximum_system_margin

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CorridorPolytope, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.path_begin is None:
        self.path_begin = 0
      if self.path_end is None:
        self.path_end = 0
      if self.normals is None:
        self.normals = []
      if self.offsets is None:
        self.offsets = []
      if self.vertices is None:
        self.vertices = []
      if self.clearance_bridge is None:
        self.clearance_bridge = False
      if self.complexity is None:
        self.complexity = 0.
      if self.local_extent is None:
        self.local_extent = 0.
      if self.minimum_system_margin is None:
        self.minimum_system_margin = 0.
      if self.maximum_system_margin is None:
        self.maximum_system_margin = 0.
    else:
      self.path_begin = 0
      self.path_end = 0
      self.normals = []
      self.offsets = []
      self.vertices = []
      self.clearance_bridge = False
      self.complexity = 0.
      self.local_extent = 0.
      self.minimum_system_margin = 0.
      self.maximum_system_margin = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2I().pack(_x.path_begin, _x.path_end))
      length = len(self.normals)
      buff.write(_struct_I.pack(length))
      for val1 in self.normals:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.offsets)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.offsets))
      length = len(self.vertices)
      buff.write(_struct_I.pack(length))
      for val1 in self.vertices:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      _x = self
      buff.write(_get_struct_B4d().pack(_x.clearance_bridge, _x.complexity, _x.local_extent, _x.minimum_system_margin, _x.maximum_system_margin))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.normals is None:
        self.normals = None
      if self.vertices is None:
        self.vertices = None
      end = 0
      _x = self
      start = end
      end += 8
      (_x.path_begin, _x.path_end,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.normals = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Vector3()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.normals.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.offsets = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.vertices = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.vertices.append(val1)
      _x = self
      start = end
      end += 33
      (_x.clearance_bridge, _x.complexity, _x.local_extent, _x.minimum_system_margin, _x.maximum_system_margin,) = _get_struct_B4d().unpack(str[start:end])
      self.clearance_bridge = bool(self.clearance_bridge)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2I().pack(_x.path_begin, _x.path_end))
      length = len(self.normals)
      buff.write(_struct_I.pack(length))
      for val1 in self.normals:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.offsets)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.offsets.tostring())
      length = len(self.vertices)
      buff.write(_struct_I.pack(length))
      for val1 in self.vertices:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      _x = self
      buff.write(_get_struct_B4d().pack(_x.clearance_bridge, _x.complexity, _x.local_extent, _x.minimum_system_margin, _x.maximum_system_margin))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.normals is None:
        self.normals = None
      if self.vertices is None:
        self.vertices = None
      end = 0
      _x = self
      start = end
      end += 8
      (_x.path_begin, _x.path_end,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.normals = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Vector3()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.normals.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.offsets = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.vertices = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.vertices.append(val1)
      _x = self
      start = end
      end += 33
      (_x.clearance_bridge, _x.complexity, _x.local_extent, _x.minimum_system_margin, _x.maximum_system_margin,) = _get_struct_B4d().unpack(str[start:end])
      self.clearance_bridge = bool(self.clearance_bridge)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_B4d = None
def _get_struct_B4d():
    global _struct_B4d
    if _struct_B4d is None:
        _struct_B4d = struct.Struct("<B4d")
    return _struct_B4d
