# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from quadrotor_msgs/IndiState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class IndiState(genpy.Message):
  _md5sum = "3911a5b39960e03dbb9636a0eb9cd311"
  _type = "quadrotor_msgs/IndiState"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
float64 indiF
float64 indiqt
float64 indiqy
geometry_msgs/Vector3 indiq
geometry_msgs/Vector3 drpy
geometry_msgs/Vector3 cp
geometry_msgs/Vector3 cv
geometry_msgs/Vector3 ca
geometry_msgs/Vector3 cq
geometry_msgs/Vector3 cF 
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['header','indiF','indiqt','indiqy','indiq','drpy','cp','cv','ca','cq','cF']
  _slot_types = ['std_msgs/Header','float64','float64','float64','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,indiF,indiqt,indiqy,indiq,drpy,cp,cv,ca,cq,cF

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(IndiState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.indiF is None:
        self.indiF = 0.
      if self.indiqt is None:
        self.indiqt = 0.
      if self.indiqy is None:
        self.indiqy = 0.
      if self.indiq is None:
        self.indiq = geometry_msgs.msg.Vector3()
      if self.drpy is None:
        self.drpy = geometry_msgs.msg.Vector3()
      if self.cp is None:
        self.cp = geometry_msgs.msg.Vector3()
      if self.cv is None:
        self.cv = geometry_msgs.msg.Vector3()
      if self.ca is None:
        self.ca = geometry_msgs.msg.Vector3()
      if self.cq is None:
        self.cq = geometry_msgs.msg.Vector3()
      if self.cF is None:
        self.cF = geometry_msgs.msg.Vector3()
    else:
      self.header = std_msgs.msg.Header()
      self.indiF = 0.
      self.indiqt = 0.
      self.indiqy = 0.
      self.indiq = geometry_msgs.msg.Vector3()
      self.drpy = geometry_msgs.msg.Vector3()
      self.cp = geometry_msgs.msg.Vector3()
      self.cv = geometry_msgs.msg.Vector3()
      self.ca = geometry_msgs.msg.Vector3()
      self.cq = geometry_msgs.msg.Vector3()
      self.cF = geometry_msgs.msg.Vector3()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_24d().pack(_x.indiF, _x.indiqt, _x.indiqy, _x.indiq.x, _x.indiq.y, _x.indiq.z, _x.drpy.x, _x.drpy.y, _x.drpy.z, _x.cp.x, _x.cp.y, _x.cp.z, _x.cv.x, _x.cv.y, _x.cv.z, _x.ca.x, _x.ca.y, _x.ca.z, _x.cq.x, _x.cq.y, _x.cq.z, _x.cF.x, _x.cF.y, _x.cF.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.indiq is None:
        self.indiq = geometry_msgs.msg.Vector3()
      if self.drpy is None:
        self.drpy = geometry_msgs.msg.Vector3()
      if self.cp is None:
        self.cp = geometry_msgs.msg.Vector3()
      if self.cv is None:
        self.cv = geometry_msgs.msg.Vector3()
      if self.ca is None:
        self.ca = geometry_msgs.msg.Vector3()
      if self.cq is None:
        self.cq = geometry_msgs.msg.Vector3()
      if self.cF is None:
        self.cF = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 192
      (_x.indiF, _x.indiqt, _x.indiqy, _x.indiq.x, _x.indiq.y, _x.indiq.z, _x.drpy.x, _x.drpy.y, _x.drpy.z, _x.cp.x, _x.cp.y, _x.cp.z, _x.cv.x, _x.cv.y, _x.cv.z, _x.ca.x, _x.ca.y, _x.ca.z, _x.cq.x, _x.cq.y, _x.cq.z, _x.cF.x, _x.cF.y, _x.cF.z,) = _get_struct_24d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_24d().pack(_x.indiF, _x.indiqt, _x.indiqy, _x.indiq.x, _x.indiq.y, _x.indiq.z, _x.drpy.x, _x.drpy.y, _x.drpy.z, _x.cp.x, _x.cp.y, _x.cp.z, _x.cv.x, _x.cv.y, _x.cv.z, _x.ca.x, _x.ca.y, _x.ca.z, _x.cq.x, _x.cq.y, _x.cq.z, _x.cF.x, _x.cF.y, _x.cF.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.indiq is None:
        self.indiq = geometry_msgs.msg.Vector3()
      if self.drpy is None:
        self.drpy = geometry_msgs.msg.Vector3()
      if self.cp is None:
        self.cp = geometry_msgs.msg.Vector3()
      if self.cv is None:
        self.cv = geometry_msgs.msg.Vector3()
      if self.ca is None:
        self.ca = geometry_msgs.msg.Vector3()
      if self.cq is None:
        self.cq = geometry_msgs.msg.Vector3()
      if self.cF is None:
        self.cF = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 192
      (_x.indiF, _x.indiqt, _x.indiqy, _x.indiq.x, _x.indiq.y, _x.indiq.z, _x.drpy.x, _x.drpy.y, _x.drpy.z, _x.cp.x, _x.cp.y, _x.cp.z, _x.cv.x, _x.cv.y, _x.cv.z, _x.ca.x, _x.ca.y, _x.ca.z, _x.cq.x, _x.cq.y, _x.cq.z, _x.cF.x, _x.cF.y, _x.cF.z,) = _get_struct_24d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_24d = None
def _get_struct_24d():
    global _struct_24d
    if _struct_24d is None:
        _struct_24d = struct.Struct("<24d")
    return _struct_24d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
