# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from quadrotor_msgs/SO3Command.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import quadrotor_msgs.msg
import std_msgs.msg

class SO3Command(genpy.Message):
  _md5sum = "cdd2dd735e73a1d9a730f9dbe0796283"
  _type = "quadrotor_msgs/SO3Command"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
uint8 id
geometry_msgs/Vector3 force
geometry_msgs/Quaternion orientation
geometry_msgs/Vector3 omg
geometry_msgs/Vector3 domg
quadrotor_msgs/AuxCommand aux
geometry_msgs/Vector3 ref_p
geometry_msgs/Vector3 ref_v
geometry_msgs/Vector3 ref_a
geometry_msgs/Vector3 ref_q
geometry_msgs/Vector3 ref_rpy
float64 ref_F
float64 ref_qt
float64 ref_qy


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: quadrotor_msgs/AuxCommand
float64 current_yaw
float64 kf_correction
float64[2] angle_corrections# Trims for roll, pitch
bool enable_motors
bool use_external_yaw
"""
  __slots__ = ['header','id','force','orientation','omg','domg','aux','ref_p','ref_v','ref_a','ref_q','ref_rpy','ref_F','ref_qt','ref_qy']
  _slot_types = ['std_msgs/Header','uint8','geometry_msgs/Vector3','geometry_msgs/Quaternion','geometry_msgs/Vector3','geometry_msgs/Vector3','quadrotor_msgs/AuxCommand','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,id,force,orientation,omg,domg,aux,ref_p,ref_v,ref_a,ref_q,ref_rpy,ref_F,ref_qt,ref_qy

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SO3Command, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.id is None:
        self.id = 0
      if self.force is None:
        self.force = geometry_msgs.msg.Vector3()
      if self.orientation is None:
        self.orientation = geometry_msgs.msg.Quaternion()
      if self.omg is None:
        self.omg = geometry_msgs.msg.Vector3()
      if self.domg is None:
        self.domg = geometry_msgs.msg.Vector3()
      if self.aux is None:
        self.aux = quadrotor_msgs.msg.AuxCommand()
      if self.ref_p is None:
        self.ref_p = geometry_msgs.msg.Vector3()
      if self.ref_v is None:
        self.ref_v = geometry_msgs.msg.Vector3()
      if self.ref_a is None:
        self.ref_a = geometry_msgs.msg.Vector3()
      if self.ref_q is None:
        self.ref_q = geometry_msgs.msg.Vector3()
      if self.ref_rpy is None:
        self.ref_rpy = geometry_msgs.msg.Vector3()
      if self.ref_F is None:
        self.ref_F = 0.
      if self.ref_qt is None:
        self.ref_qt = 0.
      if self.ref_qy is None:
        self.ref_qy = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.id = 0
      self.force = geometry_msgs.msg.Vector3()
      self.orientation = geometry_msgs.msg.Quaternion()
      self.omg = geometry_msgs.msg.Vector3()
      self.domg = geometry_msgs.msg.Vector3()
      self.aux = quadrotor_msgs.msg.AuxCommand()
      self.ref_p = geometry_msgs.msg.Vector3()
      self.ref_v = geometry_msgs.msg.Vector3()
      self.ref_a = geometry_msgs.msg.Vector3()
      self.ref_q = geometry_msgs.msg.Vector3()
      self.ref_rpy = geometry_msgs.msg.Vector3()
      self.ref_F = 0.
      self.ref_qt = 0.
      self.ref_qy = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B15d().pack(_x.id, _x.force.x, _x.force.y, _x.force.z, _x.orientation.x, _x.orientation.y, _x.orientation.z, _x.orientation.w, _x.omg.x, _x.omg.y, _x.omg.z, _x.domg.x, _x.domg.y, _x.domg.z, _x.aux.current_yaw, _x.aux.kf_correction))
      buff.write(_get_struct_2d().pack(*self.aux.angle_corrections))
      _x = self
      buff.write(_get_struct_2B18d().pack(_x.aux.enable_motors, _x.aux.use_external_yaw, _x.ref_p.x, _x.ref_p.y, _x.ref_p.z, _x.ref_v.x, _x.ref_v.y, _x.ref_v.z, _x.ref_a.x, _x.ref_a.y, _x.ref_a.z, _x.ref_q.x, _x.ref_q.y, _x.ref_q.z, _x.ref_rpy.x, _x.ref_rpy.y, _x.ref_rpy.z, _x.ref_F, _x.ref_qt, _x.ref_qy))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.force is None:
        self.force = geometry_msgs.msg.Vector3()
      if self.orientation is None:
        self.orientation = geometry_msgs.msg.Quaternion()
      if self.omg is None:
        self.omg = geometry_msgs.msg.Vector3()
      if self.domg is None:
        self.domg = geometry_msgs.msg.Vector3()
      if self.aux is None:
        self.aux = quadrotor_msgs.msg.AuxCommand()
      if self.ref_p is None:
        self.ref_p = geometry_msgs.msg.Vector3()
      if self.ref_v is None:
        self.ref_v = geometry_msgs.msg.Vector3()
      if self.ref_a is None:
        self.ref_a = geometry_msgs.msg.Vector3()
      if self.ref_q is None:
        self.ref_q = geometry_msgs.msg.Vector3()
      if self.ref_rpy is None:
        self.ref_rpy = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 121
      (_x.id, _x.force.x, _x.force.y, _x.force.z, _x.orientation.x, _x.orientation.y, _x.orientation.z, _x.orientation.w, _x.omg.x, _x.omg.y, _x.omg.z, _x.domg.x, _x.domg.y, _x.domg.z, _x.aux.current_yaw, _x.aux.kf_correction,) = _get_struct_B15d().unpack(str[start:end])
      start = end
      end += 16
      self.aux.angle_corrections = _get_struct_2d().unpack(str[start:end])
      _x = self
      start = end
      end += 146
      (_x.aux.enable_motors, _x.aux.use_external_yaw, _x.ref_p.x, _x.ref_p.y, _x.ref_p.z, _x.ref_v.x, _x.ref_v.y, _x.ref_v.z, _x.ref_a.x, _x.ref_a.y, _x.ref_a.z, _x.ref_q.x, _x.ref_q.y, _x.ref_q.z, _x.ref_rpy.x, _x.ref_rpy.y, _x.ref_rpy.z, _x.ref_F, _x.ref_qt, _x.ref_qy,) = _get_struct_2B18d().unpack(str[start:end])
      self.aux.enable_motors = bool(self.aux.enable_motors)
      self.aux.use_external_yaw = bool(self.aux.use_external_yaw)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B15d().pack(_x.id, _x.force.x, _x.force.y, _x.force.z, _x.orientation.x, _x.orientation.y, _x.orientation.z, _x.orientation.w, _x.omg.x, _x.omg.y, _x.omg.z, _x.domg.x, _x.domg.y, _x.domg.z, _x.aux.current_yaw, _x.aux.kf_correction))
      buff.write(self.aux.angle_corrections.tostring())
      _x = self
      buff.write(_get_struct_2B18d().pack(_x.aux.enable_motors, _x.aux.use_external_yaw, _x.ref_p.x, _x.ref_p.y, _x.ref_p.z, _x.ref_v.x, _x.ref_v.y, _x.ref_v.z, _x.ref_a.x, _x.ref_a.y, _x.ref_a.z, _x.ref_q.x, _x.ref_q.y, _x.ref_q.z, _x.ref_rpy.x, _x.ref_rpy.y, _x.ref_rpy.z, _x.ref_F, _x.ref_qt, _x.ref_qy))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.force is None:
        self.force = geometry_msgs.msg.Vector3()
      if self.orientation is None:
        self.orientation = geometry_msgs.msg.Quaternion()
      if self.omg is None:
        self.omg = geometry_msgs.msg.Vector3()
      if self.domg is None:
        self.domg = geometry_msgs.msg.Vector3()
      if self.aux is None:
        self.aux = quadrotor_msgs.msg.AuxCommand()
      if self.ref_p is None:
        self.ref_p = geometry_msgs.msg.Vector3()
      if self.ref_v is None:
        self.ref_v = geometry_msgs.msg.Vector3()
      if self.ref_a is None:
        self.ref_a = geometry_msgs.msg.Vector3()
      if self.ref_q is None:
        self.ref_q = geometry_msgs.msg.Vector3()
      if self.ref_rpy is None:
        self.ref_rpy = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 121
      (_x.id, _x.force.x, _x.force.y, _x.force.z, _x.orientation.x, _x.orientation.y, _x.orientation.z, _x.orientation.w, _x.omg.x, _x.omg.y, _x.omg.z, _x.domg.x, _x.domg.y, _x.domg.z, _x.aux.current_yaw, _x.aux.kf_correction,) = _get_struct_B15d().unpack(str[start:end])
      start = end
      end += 16
      self.aux.angle_corrections = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=2)
      _x = self
      start = end
      end += 146
      (_x.aux.enable_motors, _x.aux.use_external_yaw, _x.ref_p.x, _x.ref_p.y, _x.ref_p.z, _x.ref_v.x, _x.ref_v.y, _x.ref_v.z, _x.ref_a.x, _x.ref_a.y, _x.ref_a.z, _x.ref_q.x, _x.ref_q.y, _x.ref_q.z, _x.ref_rpy.x, _x.ref_rpy.y, _x.ref_rpy.z, _x.ref_F, _x.ref_qt, _x.ref_qy,) = _get_struct_2B18d().unpack(str[start:end])
      self.aux.enable_motors = bool(self.aux.enable_motors)
      self.aux.use_external_yaw = bool(self.aux.use_external_yaw)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B18d = None
def _get_struct_2B18d():
    global _struct_2B18d
    if _struct_2B18d is None:
        _struct_2B18d = struct.Struct("<2B18d")
    return _struct_2B18d
_struct_2d = None
def _get_struct_2d():
    global _struct_2d
    if _struct_2d is None:
        _struct_2d = struct.Struct("<2d")
    return _struct_2d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_B15d = None
def _get_struct_B15d():
    global _struct_B15d
    if _struct_B15d is None:
        _struct_B15d = struct.Struct("<B15d")
    return _struct_B15d
