# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from grid_path_searcher/AstarPathPoint.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class AstarPathPoint(genpy.Message):
  _md5sum = "d8313e5fbfae9cb5949798e6a59c10b3"
  _type = "grid_path_searcher/AstarPathPoint"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Point position
float64 angle_deg
float64 clearance_m
float64 arc_length_m
float64 curvature
float64 complexity
float64 desired_spacing_m
bool selected_as_waypoint

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['position','angle_deg','clearance_m','arc_length_m','curvature','complexity','desired_spacing_m','selected_as_waypoint']
  _slot_types = ['geometry_msgs/Point','float64','float64','float64','float64','float64','float64','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       position,angle_deg,clearance_m,arc_length_m,curvature,complexity,desired_spacing_m,selected_as_waypoint

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AstarPathPoint, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.angle_deg is None:
        self.angle_deg = 0.
      if self.clearance_m is None:
        self.clearance_m = 0.
      if self.arc_length_m is None:
        self.arc_length_m = 0.
      if self.curvature is None:
        self.curvature = 0.
      if self.complexity is None:
        self.complexity = 0.
      if self.desired_spacing_m is None:
        self.desired_spacing_m = 0.
      if self.selected_as_waypoint is None:
        self.selected_as_waypoint = False
    else:
      self.position = geometry_msgs.msg.Point()
      self.angle_deg = 0.
      self.clearance_m = 0.
      self.arc_length_m = 0.
      self.curvature = 0.
      self.complexity = 0.
      self.desired_spacing_m = 0.
      self.selected_as_waypoint = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_9dB().pack(_x.position.x, _x.position.y, _x.position.z, _x.angle_deg, _x.clearance_m, _x.arc_length_m, _x.curvature, _x.complexity, _x.desired_spacing_m, _x.selected_as_waypoint))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 73
      (_x.position.x, _x.position.y, _x.position.z, _x.angle_deg, _x.clearance_m, _x.arc_length_m, _x.curvature, _x.complexity, _x.desired_spacing_m, _x.selected_as_waypoint,) = _get_struct_9dB().unpack(str[start:end])
      self.selected_as_waypoint = bool(self.selected_as_waypoint)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_9dB().pack(_x.position.x, _x.position.y, _x.position.z, _x.angle_deg, _x.clearance_m, _x.arc_length_m, _x.curvature, _x.complexity, _x.desired_spacing_m, _x.selected_as_waypoint))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 73
      (_x.position.x, _x.position.y, _x.position.z, _x.angle_deg, _x.clearance_m, _x.arc_length_m, _x.curvature, _x.complexity, _x.desired_spacing_m, _x.selected_as_waypoint,) = _get_struct_9dB().unpack(str[start:end])
      self.selected_as_waypoint = bool(self.selected_as_waypoint)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_9dB = None
def _get_struct_9dB():
    global _struct_9dB
    if _struct_9dB is None:
        _struct_9dB = struct.Struct("<9dB")
    return _struct_9dB
